/*==============================================================================
$Header: //components/rel/avs.adsp/2.8.5/elite/utils/devcfg/config/elite_devcfg_8996.c#2 $
$DateTime: 2017/11/22 05:58:28 $
$Author: pwbldsvc $
$Change: 14902617 $
$Revision: #2 $

FILE: elite_devcfg_8996.c 

DESCRIPTION: 8996 Device Config

Copyright (c) 2016 QUALCOMM Technologies, Inc.  All Rights Reserved.
QUALCOMM Technologies, Inc Proprietary.  Export of this technology or software is regulated
by the U.S. Government, Diversion contrary to U.S. law prohibited.
==============================================================================*/

/*=====================================================================
 Includes
 ======================================================================*/
#include "elite_thrd_prio.h"
#include "../../../../../qdsp6/tp/inc/tp.h"


/* For Qurt, lower number is high priority and vice versa 
where as for For qurt_elite, higher number is high priority.
That is why priorities are inverted from 255 here */

#define ELITETHREAD_STAT_AFE_PORT_MANAGER_PRIO        (255 - (AVS_HIGH_PRIO_HIGH + 1))
#define ELITETHREAD_STAT_AFE_FBSP_EXCUR_PRIO          (255 - (AVS_VERY_LOW_PRIO_HIGH + 10))
#define ELITETHREAD_AVTIMER_SERVER_PRIO               (255 - (IST_HIGH + 0))
#define ELITETHREAD_DEFAULT_IST_PRIO                  (255 - (IST_HIGH + 1))
#define ELITETHREAD_DYNA_AFE_INTERNAL_BT_PRIO         (255 - (IST_HIGH + 1))
#define ELITETHREAD_STAT_AFE_VFR_PRIO                 (255 - (AVS_CRITICAL_PRIO_HIGH + 0))
#define ELITETHREAD_STAT_VOICE_TIMER_SVC_PRIO         (255 - (AVS_CRITICAL_PRIO_HIGH + 1))
#define ELITETHREAD_STAT_VOICE_DELIVERY_SVC_PRIO      (255 - (AVS_CRITICAL_PRIO_HIGH + 2))
#define ELITETHREAD_MVM_HIGH_PRIO                     (255 - (AVS_HIGH_PRIO_HIGH + 0))
#define ELITETHREAD_DYNA_AFE_INTERNAL_FM_PRIO         (255 - (AVS_HIGH_PRIO_HIGH + 1))
#define ELITETHREAD_STAT_VOICE_MIXER_SVC_PRIO         (255 - (AVS_HIGH_PRIO_HIGH + 2))
#define ELITETHREAD_STAT_AFE_DEV_SVC_PRIO             (255 - (AVS_HIGH_PRIO_HIGH + 4))
#define ELITETHREAD_STAT_VOICE_STREAM_SVC_PRIO        (255 - (AVS_HIGH_PRIO_HIGH + 5))
#define ELITETHREAD_STAT_AUDIO_STREAM_SVC_PRIO        (255 - (AVS_HIGH_PRIO_HIGH + 7))
#define ELITETHREAD_STAT_AUDIO_DEV_SVC_PRIO           (255 - (AVS_HIGH_PRIO_HIGH + 7))
#define ELITETHREAD_STAT_ADSP_CORE_SVC_PRIO           (255 - (AVS_HIGH_PRIO_HIGH + 7))
#define ELITETHREAD_STAT_AFE_CDC_INT_SVC_PRIO         (255 - (AVS_HIGH_PRIO_HIGH + 7))
#define ELITETHREAD_DYNA_MIXER_SVC_PRIO               (255 - (AVS_HIGH_PRIO_HIGH + 8))
#define ELITETHREAD_DYNA_MTMX_PSPD_SVC_PRIO           (255 - (AVS_HIGH_PRIO_HIGH + 8))
#define ELITETHREAD_DYNA_STREAM_ROUTER_SVC_PRIO       (255 - (AVS_HIGH_PRIO_HIGH + 8))
#define ELITETHREAD_MVM_MED_PRIO                      (255 - (AVS_MEDIUM_PRIO_HIGH + 0))
#define ELITETHREAD_CVD_VFR_PRIO                      (255 - (AVS_MEDIUM_PRIO_HIGH + 1))
#define ELITETHREAD_CVP_LOW_PRIO                      (255 - (AVS_MEDIUM_PRIO_HIGH + 2))
#define ELITETHREAD_CVS_MAILBOX_TIMER_PRIO            (255 - (AVS_MEDIUM_PRIO_HIGH + 3))
#define ELITETHREAD_DYNA_LL_PP_SVC_PRIO               (255 - (AVS_MEDIUM_PRIO_HIGH + 4))
#define ELITETHREAD_DYNA_LL_DEC_SVC_PRIO              (255 - (AVS_MEDIUM_PRIO_HIGH + 6))
#define ELITETHREAD_DYNA_LL_ENC_SVC_PRIO              (255 - (AVS_MEDIUM_PRIO_HIGH + 6))
#define ELITETHREAD_DYNA_VOICE_DEC_PRIO               (255 - (AVS_MEDIUM_PRIO_HIGH + 7))
#define ELITETHREAD_DYNA_VOICE_PROC_RX_PRIO           (255 - (AVS_MEDIUM_PRIO_HIGH + 8))
#define ELITETHREAD_DYNA_VOICE_PROC_TX_PRIO           (255 - (AVS_MEDIUM_PRIO_HIGH + 9))
#define ELITETHREAD_MVM_LOW_PRIO                      (255 - (AVS_MEDIUM_PRIO_HIGH + 9))
#define ELITETHREAD_DYNA_VOICE_ENC_PRIO               (255 - (AVS_MEDIUM_PRIO_HIGH + 10))
#define ELITETHREAD_DYNA_PP_SVC_PRIO                  (255 - (AVS_MEDIUM_PRIO_HIGH + 11))
#define ELITETHREAD_DYNA_DEC_SVC_PRIO                 (255 - (AVS_MEDIUM_PRIO_HIGH + 12))
#define ELITETHREAD_DYNA_SWITCH_SVC_PRIO              (255 - (AVS_MEDIUM_PRIO_HIGH + 12))
#define ELITETHREAD_DYNA_ENC_SVC_PRIO                 (255 - (AVS_MEDIUM_PRIO_HIGH + 12))
#define ELITETHREAD_DYNA_LSM_SVC_PRIO                 (255 - (AVS_MEDIUM_PRIO_HIGH + 12))
#define ELITETHREAD_AUDENCDEC_TEST_PRIO               (255 - (AVS_MEDIUM_PRIO_LOW + 0))
#define ELITETHREAD_COMMON_TEST_PRIO                  (255 - (AVS_MEDIUM_PRIO_LOW + 0))
#define ELITETHREAD_AMDB_THREADPOOL_PRIO              (255 - (AVS_MEDIUM_PRIO_LOW + 0))
#define ELITETHREAD_STAT_LSM_SVC_PRIO                 (255 - (AVS_LOW_PRIO_HIGH + 1))
#define ELITETHREAD_STAT_AFE_SW_MAD_PRIO              (255 - (AVS_VERY_LOW_PRIO_HIGH + 0))
#define ELITETHREAD_STAT_AFE_AANC_PRIO                (255 - (AVS_VERY_LOW_PRIO_HIGH + 0))
#define ELITETHREAD_STAT_AFE_SW_DUTY_CYCLE_PRIO       (255 - (AVS_VERY_LOW_PRIO_HIGH + 0))
#define ELITETHREAD_CVD_CAL_LOGGER_PRIO               (255 - (AVS_VERY_LOW_PRIO_LOW + 0))



static elite_thrd_prio_struct_t thrd_priorities[] =
{
    {ELITETHREAD_STAT_AFE_PORT_MANAGER_PRIO_ID, ELITETHREAD_STAT_AFE_PORT_MANAGER_PRIO},
    {ELITETHREAD_STAT_AFE_FBSP_EXCUR_PRIO_ID, ELITETHREAD_STAT_AFE_FBSP_EXCUR_PRIO},
    {ELITETHREAD_AVTIMER_SERVER_PRIO_ID, ELITETHREAD_AVTIMER_SERVER_PRIO},
    {ELITETHREAD_DEFAULT_IST_PRIO_ID, ELITETHREAD_DEFAULT_IST_PRIO},
    {ELITETHREAD_DYNA_AFE_INTERNAL_BT_PRIO_ID, ELITETHREAD_DYNA_AFE_INTERNAL_BT_PRIO},
    {ELITETHREAD_STAT_AFE_VFR_PRIO_ID, ELITETHREAD_STAT_AFE_VFR_PRIO},
    {ELITETHREAD_STAT_VOICE_TIMER_SVC_PRIO_ID, ELITETHREAD_STAT_VOICE_TIMER_SVC_PRIO},
    {ELITETHREAD_STAT_VOICE_DELIVERY_SVC_PRIO_ID, ELITETHREAD_STAT_VOICE_DELIVERY_SVC_PRIO},
    {ELITETHREAD_MVM_HIGH_PRIO_ID, ELITETHREAD_MVM_HIGH_PRIO},
    {ELITETHREAD_DYNA_AFE_INTERNAL_FM_PRIO_ID, ELITETHREAD_DYNA_AFE_INTERNAL_FM_PRIO},
    {ELITETHREAD_STAT_VOICE_MIXER_SVC_PRIO_ID, ELITETHREAD_STAT_VOICE_MIXER_SVC_PRIO},
    {ELITETHREAD_STAT_AFE_DEV_SVC_PRIO_ID, ELITETHREAD_STAT_AFE_DEV_SVC_PRIO},
    {ELITETHREAD_STAT_VOICE_STREAM_SVC_PRIO_ID, ELITETHREAD_STAT_VOICE_STREAM_SVC_PRIO},
    {ELITETHREAD_STAT_AUDIO_STREAM_SVC_PRIO_ID, ELITETHREAD_STAT_AUDIO_STREAM_SVC_PRIO},
    {ELITETHREAD_STAT_AUDIO_DEV_SVC_PRIO_ID, ELITETHREAD_STAT_AUDIO_DEV_SVC_PRIO},
    {ELITETHREAD_STAT_ADSP_CORE_SVC_PRIO_ID, ELITETHREAD_STAT_ADSP_CORE_SVC_PRIO},
    {ELITETHREAD_STAT_AFE_CDC_INT_SVC_PRIO_ID, ELITETHREAD_STAT_AFE_CDC_INT_SVC_PRIO},
    {ELITETHREAD_DYNA_MIXER_SVC_PRIO_ID, ELITETHREAD_DYNA_MIXER_SVC_PRIO},
    {ELITETHREAD_DYNA_MTMX_PSPD_SVC_PRIO_ID, ELITETHREAD_DYNA_MTMX_PSPD_SVC_PRIO},
    {ELITETHREAD_DYNA_STREAM_ROUTER_SVC_PRIO_ID, ELITETHREAD_DYNA_STREAM_ROUTER_SVC_PRIO},
    {ELITETHREAD_MVM_MED_PRIO_ID, ELITETHREAD_MVM_MED_PRIO},
    {ELITETHREAD_CVD_VFR_PRIO_ID, ELITETHREAD_CVD_VFR_PRIO},
    {ELITETHREAD_CVP_LOW_PRIO_ID, ELITETHREAD_CVP_LOW_PRIO},
    {ELITETHREAD_CVS_MAILBOX_TIMER_PRIO_ID, ELITETHREAD_CVS_MAILBOX_TIMER_PRIO},
    {ELITETHREAD_DYNA_VOICE_DEC_PRIO_ID, ELITETHREAD_DYNA_VOICE_DEC_PRIO},
    {ELITETHREAD_DYNA_VOICE_PROC_RX_PRIO_ID, ELITETHREAD_DYNA_VOICE_PROC_RX_PRIO},
    {ELITETHREAD_DYNA_VOICE_PROC_TX_PRIO_ID, ELITETHREAD_DYNA_VOICE_PROC_TX_PRIO},
    {ELITETHREAD_MVM_LOW_PRIO_ID, ELITETHREAD_MVM_LOW_PRIO},
    {ELITETHREAD_DYNA_VOICE_ENC_PRIO_ID, ELITETHREAD_DYNA_VOICE_ENC_PRIO},
    {ELITETHREAD_DYNA_LL_PP_SVC_PRIO_ID, ELITETHREAD_DYNA_LL_PP_SVC_PRIO},
    {ELITETHREAD_DYNA_LL_DEC_SVC_PRIO_ID, ELITETHREAD_DYNA_LL_DEC_SVC_PRIO},
    {ELITETHREAD_DYNA_LL_ENC_SVC_PRIO_ID, ELITETHREAD_DYNA_LL_ENC_SVC_PRIO},
    {ELITETHREAD_DYNA_PP_SVC_PRIO_ID, ELITETHREAD_DYNA_PP_SVC_PRIO},
    {ELITETHREAD_DYNA_DEC_SVC_PRIO_ID, ELITETHREAD_DYNA_DEC_SVC_PRIO},
    {ELITETHREAD_DYNA_SWITCH_SVC_PRIO_ID, ELITETHREAD_DYNA_SWITCH_SVC_PRIO},
    {ELITETHREAD_DYNA_ENC_SVC_PRIO_ID, ELITETHREAD_DYNA_ENC_SVC_PRIO},
    {ELITETHREAD_DYNA_LSM_SVC_PRIO_ID, ELITETHREAD_DYNA_LSM_SVC_PRIO},
    {ELITETHREAD_AUDENCDEC_TEST_PRIO_ID, ELITETHREAD_AUDENCDEC_TEST_PRIO},
    {ELITETHREAD_COMMON_TEST_PRIO_ID, ELITETHREAD_COMMON_TEST_PRIO},
    {ELITETHREAD_AMDB_THREADPOOL_PRIO_ID, ELITETHREAD_AMDB_THREADPOOL_PRIO},
    {ELITETHREAD_STAT_LSM_SVC_PRIO_ID, ELITETHREAD_STAT_LSM_SVC_PRIO},
    {ELITETHREAD_STAT_AFE_SW_MAD_PRIO_ID, ELITETHREAD_STAT_AFE_SW_MAD_PRIO},
    {ELITETHREAD_STAT_AFE_AANC_PRIO_ID, ELITETHREAD_STAT_AFE_AANC_PRIO},
    {ELITETHREAD_STAT_AFE_SW_DUTY_CYCLE_PRIO_ID, ELITETHREAD_STAT_AFE_SW_DUTY_CYCLE_PRIO},
    {ELITETHREAD_CVD_CAL_LOGGER_PRIO_ID, ELITETHREAD_CVD_CAL_LOGGER_PRIO}

};

/* Max number of threads in Elite for this chipset */
#define ELITE_NUM_THRDS (sizeof(thrd_priorities)/sizeof(thrd_priorities[0]))

elite_thrd_prio_prop_struct_t elite_thrd_prio_prop =
{ 
    ELITE_NUM_THRDS, thrd_priorities
};
