/*==============================================================================
$Header: //components/rel/avs.adsp/2.8.5/elite/utils/devcfg/config/elite_devcfg_8909.c#1 $
$DateTime: 2017/11/07 23:00:25 $
$Author: pwbldsvc $
$Change: 14795016 $
$Revision: #1 $

FILE: lpasshwio_devcfg_9x55.c 

DESCRIPTION: 9x55 Device Config

Copyright 2015 QUALCOMM Technologies, Inc. (QTI).
All Rights Reserved.
QUALCOMM Proprietary/GTDR
==============================================================================*/

/*=====================================================================
 Includes
 ======================================================================*/
#include "elite_thrd_prio.h"

/* For Qurt, lower number is high priority and vice versa 
where as for For qurt_elite, higher number is high priority.
That is why priorities are inverted from 255 here */

#define ELITETHREAD_AVTIMER_SERVER_PRIO               (255 - 64)
#define ELITETHREAD_DEFAULT_IST_PRIO                  (255 - 65)
#define ELITETHREAD_STAT_AFE_VFR_PRIO                 (255 - 71)
#define ELITETHREAD_STAT_VOICE_TIMER_SVC_PRIO         (255 - 74)
#define ELITETHREAD_STAT_VOICE_DELIVERY_SVC_PRIO      (255 - 74)
#define ELITETHREAD_DYNA_AFE_INTERNAL_BT_PRIO         (255 - 40)
#define ELITETHREAD_DYNA_AFE_INTERNAL_FM_PRIO         (255 - 78)
#define ELITETHREAD_STAT_AFE_PORT_MANAGER_PRIO        (255 - 78)
#define ELITETHREAD_STAT_VOICE_MIXER_SVC_PRIO         (255 - 79)
#define ELITETHREAD_STAT_AFE_PSEUDOPORT_PRIO          (255 - 86)
#define ELITETHREAD_STAT_AFE_DEV_SVC_PRIO             (255 - 118)
#define ELITETHREAD_STAT_VOICE_STREAM_SVC_PRIO	      (255 - 80)
#define ELITETHREAD_STAT_AUDIO_STREAM_SVC_PRIO        (255 - 118)
#define ELITETHREAD_STAT_AUDIO_DEV_SVC_PRIO           (255 - 118)
#define ELITETHREAD_STAT_ADSP_CORE_SVC_PRIO           (255 - 118)
#define ELITETHREAD_STAT_AFE_CDC_INT_SVC_PRIO         (255 - 83)
#define ELITETHREAD_DYNA_MIXER_SVC_PRIO               (255 - 83)
#define ELITETHREAD_DYNA_STREAM_ROUTER_SVC_PRIO       (255 - 83)
#define ELITETHREAD_CVS_PRIO	                      (255 - 82)
#define ELITETHREAD_CVP_PRIO	                      (255 - 119)
#define ELITETHREAD_DYNA_VOICE_DEC_PRIO               (255 - 120)
#define ELITETHREAD_DYNA_VOICE_PROC_RX_PRIO           (255 - 121)
#define ELITETHREAD_DYNA_VOICE_PROC_TX_PRIO           (255 - 123)
#define ELITETHREAD_DYNA_VOICE_ENC_PRIO               (255 - 122)
#define ELITETHREAD_DYNA_LL_PP_SVC_PRIO               (255 - 87)
#define ELITETHREAD_DYNA_LL_DEC_SVC_PRIO              (255 - 87)
#define ELITETHREAD_DYNA_LL_ENC_SVC_PRIO              (255 - 87)
#define ELITETHREAD_DYNA_PP_SVC_PRIO                  (255 - 160)
#define ELITETHREAD_DYNA_DEC_SVC_PRIO                 (255 - 161)
#define ELITETHREAD_DYNA_SWITCH_SVC_PRIO              (255 - 161)
#define ELITETHREAD_DYNA_ENC_SVC_PRIO                 (255 - 161)
#define ELITETHREAD_DYNA_LSM_SVC_PRIO                 (255 - 161)
#define ELITETHREAD_MVM_PRIO                          (255 - 120)
#define ELITETHREAD_STAT_ULTRASOUND_STREAM_SVC_PRIO   (255 - 161)
#define ELITETHREAD_STAT_LSM_SVC_PRIO                 (255 - 163)
#define ELITETHREAD_STAT_AFE_SW_MAD_PRIO              (255 - 164)
#define ELITETHREAD_STAT_AFE_AANC_PRIO                (255 - 164)
#define ELITETHREAD_STAT_AFE_FBSP_EXCUR_PRIO          (255 - 164)
#define ELITETHREAD_STAT_AFE_SW_DUTY_CYCLE_PRIO       (255 - 164)

/* The following set of thread priority present in ADSP only, are 
derived from their corresponding peers in MDSP. Might need to revisit
 */
#define ELITETHREAD_CVP_LOW_PRIO                      ELITETHREAD_CVP_PRIO
#define ELITETHREAD_CVS_MAILBOX_TIMER_PRIO            ELITETHREAD_CVS_PRIO
#define ELITETHREAD_MVM_HIGH_PRIO                     ELITETHREAD_MVM_PRIO
#define ELITETHREAD_MVM_LOW_PRIO                      ELITETHREAD_MVM_PRIO
#define ELITETHREAD_MVM_MED_PRIO                      ELITETHREAD_MVM_PRIO

/* The following set of thread priorities are present in ADSP only
   Hardcoding the same values as ADSP for now. Might need to revisit
 */
#define ELITETHREAD_AMDB_THREADPOOL_PRIO	      (255 - 69)	 	
#define ELITETHREAD_AUDENCDEC_TEST_PRIO		      (255 - 69)
#define ELITETHREAD_COMMON_TEST_PRIO                  (255 - 69)
#define ELITETHREAD_CVD_CAL_LOGGER_PRIO               (255 - 109)
#define ELITETHREAD_CVD_VFR_PRIO                      (255 - 51)
#define ELITETHREAD_DYNA_MTMX_PSPD_SVC_PRIO           (255 - 38)


static elite_thrd_prio_struct_t thrd_priorities[] =
{
    {ELITETHREAD_STAT_AFE_PORT_MANAGER_PRIO_ID, ELITETHREAD_STAT_AFE_PORT_MANAGER_PRIO},
    {ELITETHREAD_STAT_AFE_FBSP_EXCUR_PRIO_ID, ELITETHREAD_STAT_AFE_FBSP_EXCUR_PRIO},
    {ELITETHREAD_AVTIMER_SERVER_PRIO_ID, ELITETHREAD_AVTIMER_SERVER_PRIO},
    {ELITETHREAD_DEFAULT_IST_PRIO_ID, ELITETHREAD_DEFAULT_IST_PRIO},
    {ELITETHREAD_DYNA_AFE_INTERNAL_BT_PRIO_ID, ELITETHREAD_DYNA_AFE_INTERNAL_BT_PRIO},
    {ELITETHREAD_STAT_AFE_VFR_PRIO_ID, ELITETHREAD_STAT_AFE_VFR_PRIO},
    {ELITETHREAD_STAT_VOICE_TIMER_SVC_PRIO_ID, ELITETHREAD_STAT_VOICE_TIMER_SVC_PRIO},
    {ELITETHREAD_STAT_VOICE_DELIVERY_SVC_PRIO_ID, ELITETHREAD_STAT_VOICE_DELIVERY_SVC_PRIO},
    {ELITETHREAD_MVM_HIGH_PRIO_ID, ELITETHREAD_MVM_HIGH_PRIO},
    {ELITETHREAD_DYNA_AFE_INTERNAL_FM_PRIO_ID, ELITETHREAD_DYNA_AFE_INTERNAL_FM_PRIO},
    {ELITETHREAD_STAT_VOICE_MIXER_SVC_PRIO_ID, ELITETHREAD_STAT_VOICE_MIXER_SVC_PRIO},
    {ELITETHREAD_STAT_AFE_DEV_SVC_PRIO_ID, ELITETHREAD_STAT_AFE_DEV_SVC_PRIO},
    {ELITETHREAD_STAT_VOICE_STREAM_SVC_PRIO_ID, ELITETHREAD_STAT_VOICE_STREAM_SVC_PRIO},
    {ELITETHREAD_STAT_AUDIO_STREAM_SVC_PRIO_ID, ELITETHREAD_STAT_AUDIO_STREAM_SVC_PRIO},
    {ELITETHREAD_STAT_AUDIO_DEV_SVC_PRIO_ID, ELITETHREAD_STAT_AUDIO_DEV_SVC_PRIO},
    {ELITETHREAD_STAT_ADSP_CORE_SVC_PRIO_ID, ELITETHREAD_STAT_ADSP_CORE_SVC_PRIO},
    {ELITETHREAD_STAT_AFE_CDC_INT_SVC_PRIO_ID, ELITETHREAD_STAT_AFE_CDC_INT_SVC_PRIO},
    {ELITETHREAD_DYNA_MIXER_SVC_PRIO_ID, ELITETHREAD_DYNA_MIXER_SVC_PRIO},
    {ELITETHREAD_DYNA_MTMX_PSPD_SVC_PRIO_ID, ELITETHREAD_DYNA_MTMX_PSPD_SVC_PRIO},
    {ELITETHREAD_DYNA_STREAM_ROUTER_SVC_PRIO_ID, ELITETHREAD_DYNA_STREAM_ROUTER_SVC_PRIO},
    {ELITETHREAD_MVM_MED_PRIO_ID, ELITETHREAD_MVM_MED_PRIO},
    {ELITETHREAD_CVD_VFR_PRIO_ID, ELITETHREAD_CVD_VFR_PRIO},
    {ELITETHREAD_CVP_LOW_PRIO_ID, ELITETHREAD_CVP_LOW_PRIO},
    {ELITETHREAD_CVS_MAILBOX_TIMER_PRIO_ID, ELITETHREAD_CVS_MAILBOX_TIMER_PRIO},
    {ELITETHREAD_DYNA_VOICE_DEC_PRIO_ID, ELITETHREAD_DYNA_VOICE_DEC_PRIO},
    {ELITETHREAD_DYNA_VOICE_PROC_RX_PRIO_ID, ELITETHREAD_DYNA_VOICE_PROC_RX_PRIO},
    {ELITETHREAD_DYNA_VOICE_PROC_TX_PRIO_ID, ELITETHREAD_DYNA_VOICE_PROC_TX_PRIO},
    {ELITETHREAD_MVM_LOW_PRIO_ID, ELITETHREAD_MVM_LOW_PRIO},
    {ELITETHREAD_DYNA_VOICE_ENC_PRIO_ID, ELITETHREAD_DYNA_VOICE_ENC_PRIO},
    {ELITETHREAD_DYNA_LL_PP_SVC_PRIO_ID, ELITETHREAD_DYNA_LL_PP_SVC_PRIO},
    {ELITETHREAD_DYNA_LL_DEC_SVC_PRIO_ID, ELITETHREAD_DYNA_LL_DEC_SVC_PRIO},
    {ELITETHREAD_DYNA_LL_ENC_SVC_PRIO_ID, ELITETHREAD_DYNA_LL_ENC_SVC_PRIO},
    {ELITETHREAD_DYNA_PP_SVC_PRIO_ID, ELITETHREAD_DYNA_PP_SVC_PRIO},
    {ELITETHREAD_DYNA_DEC_SVC_PRIO_ID, ELITETHREAD_DYNA_DEC_SVC_PRIO},
    {ELITETHREAD_DYNA_SWITCH_SVC_PRIO_ID, ELITETHREAD_DYNA_SWITCH_SVC_PRIO},
    {ELITETHREAD_DYNA_ENC_SVC_PRIO_ID, ELITETHREAD_DYNA_ENC_SVC_PRIO},
    {ELITETHREAD_DYNA_LSM_SVC_PRIO_ID, ELITETHREAD_DYNA_LSM_SVC_PRIO},
    {ELITETHREAD_AUDENCDEC_TEST_PRIO_ID, ELITETHREAD_AUDENCDEC_TEST_PRIO},
    {ELITETHREAD_COMMON_TEST_PRIO_ID, ELITETHREAD_COMMON_TEST_PRIO},
    {ELITETHREAD_AMDB_THREADPOOL_PRIO_ID, ELITETHREAD_AMDB_THREADPOOL_PRIO},
    {ELITETHREAD_STAT_LSM_SVC_PRIO_ID, ELITETHREAD_STAT_LSM_SVC_PRIO},
    {ELITETHREAD_STAT_AFE_SW_MAD_PRIO_ID, ELITETHREAD_STAT_AFE_SW_MAD_PRIO},
    {ELITETHREAD_STAT_AFE_AANC_PRIO_ID, ELITETHREAD_STAT_AFE_AANC_PRIO},
    {ELITETHREAD_STAT_AFE_SW_DUTY_CYCLE_PRIO_ID, ELITETHREAD_STAT_AFE_SW_DUTY_CYCLE_PRIO},
    {ELITETHREAD_CVD_CAL_LOGGER_PRIO_ID, ELITETHREAD_CVD_CAL_LOGGER_PRIO}
};

/* Max number of threads in Elite for this chipset */
#define ELITE_NUM_THRDS (sizeof(thrd_priorities)/sizeof(thrd_priorities[0]))

elite_thrd_prio_prop_struct_t elite_thrd_prio_prop =
{ 
    ELITE_NUM_THRDS, thrd_priorities
};

