#include "AEEStdDef.idl"

// Interface used by the ADSP to send log messages back to the APPS (reverse invoke)
interface adspmsgd_apps {
    enum Level{
        LOW,
        MEDIUM,
        HIGH,
        ERROR,
        FATAL
    };

    typedef sequence <octet> octetSeq;

    long log(in octetSeq log_message_buffer);
};
