#pragma once
// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"
#include "IHdcpTransmitter.h"
#include "INotifyHdcp.h"

// Copyright (c) 2017 Qualcomm Technologies, Inc.  All Rights Reserved.

// Qualcomm Technologies Proprietary and Confidential.

#define IOPSSink_OP_getHdcpTransmitter 0

static inline int32_t
IOPSSink_release(Object self)
{
  return Object_invoke(self, Object_OP_release, 0, 0);
}

static inline int32_t
IOPSSink_retain(Object self)
{
  return Object_invoke(self, Object_OP_retain, 0, 0);
}

static inline int32_t
IOPSSink_getHdcpTransmitter(Object self, uint32_t deviceId_val, Object notify_val, Object *hdcpTx_ptr)
{
  ObjectArg a[3];
  a[0].b = (ObjectBuf) { &deviceId_val, sizeof(uint32_t) };
  a[1].o = notify_val;

  int32_t result = Object_invoke(self, IOPSSink_OP_getHdcpTransmitter, a, ObjectCounts_pack(1, 0, 1, 1));

  *hdcpTx_ptr = a[2].o;

  return result;
}



