//////////////////////////////////////////////////////////////////////////////
// LPASS_ADDRESS_FILE.h generated by: GenArmCHeader.pl
//////////////////////////////////////////////////////////////////////////////
// **** W A R N I N G ****  THIS FILE IS AUTO GENERATED!! PLEASE DO NOT EDIT!!
//////////////////////////////////////////////////////////////////////////////
// Copyright (c) 2012-2015,2017 QUALCOMM Technologies, Incorporated.
// All Rights Reserved.
// QUALCOMM Technologies Proprietary.
//////////////////////////////////////////////////////////////////////////////
// RCS File        : -USE CVS LOG-
// Revision        : -USE CVS LOG-
// Last Check In   : -USE CVS LOG-
//////////////////////////////////////////////////////////////////////////////
// Description     : Constants related to Hardware Registers
//
// Byte Addresses are used for all BASES and ADDRESSES
//////////////////////////////////////////////////////////////////////////////
#ifndef _LPASS_ADDRESS_FILE_TCSR_HAL_V1_H_

#define _LPASS_ADDRESS_FILE_TCSR_HAL_V1_H_

#define LPASS_LPASS_TCSR_BASE       (0x09080000)

#define LPASS_HW_VERSION                          (0x09080000)
#define   LPASS_HW_VERSION___RWC                    QCSR_REG_RO    
#define   LPASS_HW_VERSION___POR                 0x40000000
#define   LPASS_HW_VERSION__MAJOR___POR          0x4
#define   LPASS_HW_VERSION__MINOR___POR          0x000
#define   LPASS_HW_VERSION__STEP___POR           0x0000
#define   LPASS_HW_VERSION__MAJOR___M            0xF0000000
#define   LPASS_HW_VERSION__MAJOR___S                         28
#define   LPASS_HW_VERSION__MINOR___M            0x0FFF0000
#define   LPASS_HW_VERSION__MINOR___S                         16
#define   LPASS_HW_VERSION__STEP___M             0x0000FFFF
#define   LPASS_HW_VERSION__STEP___S                           0
#define   LPASS_HW_VERSION___M                   0xFFFFFFFF   
#define   LPASS_HW_VERSION___S                                 0


#define LPASS_AUDIO_CORE_LPAIF_CODEC_SPKR_MODE_MUXSEL (0x09089000)
#define   LPASS_AUDIO_CORE_LPAIF_CODEC_SPKR_MODE_MUXSEL___RWC QCSR_REG_RW    
#define   LPASS_AUDIO_CORE_LPAIF_CODEC_SPKR_MODE_MUXSEL___POR 0x00000000
#define   LPASS_AUDIO_CORE_LPAIF_CODEC_SPKR_MODE_MUXSEL__SEL___POR 0x0
#define   LPASS_AUDIO_CORE_LPAIF_CODEC_SPKR_MODE_MUXSEL__SEL___M 0x00000001
#define   LPASS_AUDIO_CORE_LPAIF_CODEC_SPKR_MODE_MUXSEL__SEL___S               0
#define   LPASS_AUDIO_CORE_LPAIF_CODEC_SPKR_MODE_MUXSEL___M 0x00000001   
#define   LPASS_AUDIO_CORE_LPAIF_CODEC_SPKR_MODE_MUXSEL___S               0

#define LPASS_AUDIO_CORE_LPAIF_PRI_MODE_MUXSEL    (0x0908A000)
#define   LPASS_AUDIO_CORE_LPAIF_PRI_MODE_MUXSEL___RWC QCSR_REG_RW    
#define   LPASS_AUDIO_CORE_LPAIF_PRI_MODE_MUXSEL___POR 0x00000000
#define   LPASS_AUDIO_CORE_LPAIF_PRI_MODE_MUXSEL__SEL___POR 0x0
#define   LPASS_AUDIO_CORE_LPAIF_PRI_MODE_MUXSEL__SEL___M 0x00000001
#define   LPASS_AUDIO_CORE_LPAIF_PRI_MODE_MUXSEL__SEL___S               0
#define   LPASS_AUDIO_CORE_LPAIF_PRI_MODE_MUXSEL___M 0x00000001   
#define   LPASS_AUDIO_CORE_LPAIF_PRI_MODE_MUXSEL___S               0

#define LPASS_AUDIO_CORE_LPAIF_SEC_MODE_MUXSEL    (0x0908B000)
#define   LPASS_AUDIO_CORE_LPAIF_SEC_MODE_MUXSEL___RWC QCSR_REG_RW    
#define   LPASS_AUDIO_CORE_LPAIF_SEC_MODE_MUXSEL___POR 0x00000000
#define   LPASS_AUDIO_CORE_LPAIF_SEC_MODE_MUXSEL__SEL___POR 0x0
#define   LPASS_AUDIO_CORE_LPAIF_SEC_MODE_MUXSEL__SEL___M 0x00000001
#define   LPASS_AUDIO_CORE_LPAIF_SEC_MODE_MUXSEL__SEL___S               0
#define   LPASS_AUDIO_CORE_LPAIF_SEC_MODE_MUXSEL___M 0x00000001   
#define   LPASS_AUDIO_CORE_LPAIF_SEC_MODE_MUXSEL___S               0

#define LPASS_AUDIO_CORE_LPAIF_TER_MODE_MUXSEL    (0x0908C000)
#define   LPASS_AUDIO_CORE_LPAIF_TER_MODE_MUXSEL___RWC QCSR_REG_RW    
#define   LPASS_AUDIO_CORE_LPAIF_TER_MODE_MUXSEL___POR 0x00000000
#define   LPASS_AUDIO_CORE_LPAIF_TER_MODE_MUXSEL__SEL___POR 0x0
#define   LPASS_AUDIO_CORE_LPAIF_TER_MODE_MUXSEL__SEL___M 0x00000001
#define   LPASS_AUDIO_CORE_LPAIF_TER_MODE_MUXSEL__SEL___S               0
#define   LPASS_AUDIO_CORE_LPAIF_TER_MODE_MUXSEL___M 0x00000001   
#define   LPASS_AUDIO_CORE_LPAIF_TER_MODE_MUXSEL___S               0

#define LPASS_AUDIO_CORE_LPAIF_QUAD_MODE_MUXSEL   (0x0908D000)
#define   LPASS_AUDIO_CORE_LPAIF_QUAD_MODE_MUXSEL___RWC QCSR_REG_RW    
#define   LPASS_AUDIO_CORE_LPAIF_QUAD_MODE_MUXSEL___POR 0x00000000
#define   LPASS_AUDIO_CORE_LPAIF_QUAD_MODE_MUXSEL__SEL___POR 0x0
#define   LPASS_AUDIO_CORE_LPAIF_QUAD_MODE_MUXSEL__SEL___M 0x00000001
#define   LPASS_AUDIO_CORE_LPAIF_QUAD_MODE_MUXSEL__SEL___S               0
#define   LPASS_AUDIO_CORE_LPAIF_QUAD_MODE_MUXSEL___M 0x00000001   
#define   LPASS_AUDIO_CORE_LPAIF_QUAD_MODE_MUXSEL___S               0


#endif