#include "AEEStdDef.idl"
#include "remote.idl"

const long _const_adspmsgd_adsp1_handle = 5;

// Interface used by APPS to initialize the adspmsgd service on the ADSP (forward invoke)
interface adspmsgd_adsp1 : remote_handle64 {
    long init2();
    long deinit();
};
