/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.6 at Mon Mar 19 17:24:01 2018. */

#ifndef PB_SNS_FACING_PB_H_INCLUDED
#define PB_SNS_FACING_PB_H_INCLUDED
#include "pb.h"

#include "sns_std_sensor.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _sns_facing_msgid {
    SNS_FACING_MSGID_SNS_FACING_EVENT = 1024
} sns_facing_msgid;
#define _sns_facing_msgid_MIN SNS_FACING_MSGID_SNS_FACING_EVENT
#define _sns_facing_msgid_MAX SNS_FACING_MSGID_SNS_FACING_EVENT
#define _sns_facing_msgid_ARRAYSIZE ((sns_facing_msgid)(SNS_FACING_MSGID_SNS_FACING_EVENT+1))
#define sns_facing_msgid_SNS_FACING_MSGID_SNS_FACING_EVENT SNS_FACING_MSGID_SNS_FACING_EVENT

typedef enum _sns_facing_event_state {
    SNS_FACING_EVENT_STATE_UNKNOWN = 0,
    SNS_FACING_EVENT_STATE_UP = 1,
    SNS_FACING_EVENT_STATE_DOWN = 2,
    SNS_FACING_EVENT_STATE_NEUTRAL = 3
} sns_facing_event_state;
#define _sns_facing_event_state_MIN SNS_FACING_EVENT_STATE_UNKNOWN
#define _sns_facing_event_state_MAX SNS_FACING_EVENT_STATE_NEUTRAL
#define _sns_facing_event_state_ARRAYSIZE ((sns_facing_event_state)(SNS_FACING_EVENT_STATE_NEUTRAL+1))
#define sns_facing_event_state_SNS_FACING_EVENT_STATE_UNKNOWN SNS_FACING_EVENT_STATE_UNKNOWN
#define sns_facing_event_state_SNS_FACING_EVENT_STATE_UP SNS_FACING_EVENT_STATE_UP
#define sns_facing_event_state_SNS_FACING_EVENT_STATE_DOWN SNS_FACING_EVENT_STATE_DOWN
#define sns_facing_event_state_SNS_FACING_EVENT_STATE_NEUTRAL SNS_FACING_EVENT_STATE_NEUTRAL

/* Struct definitions */
typedef struct _sns_facing_event {
    sns_facing_event_state state;
/* @@protoc_insertion_point(struct:sns_facing_event) */
} sns_facing_event;

/* Default values for struct fields */
extern const sns_facing_event_state sns_facing_event_state_default;

/* Initializer values for message structs */
#define sns_facing_event_init_default            {SNS_FACING_EVENT_STATE_UNKNOWN}
#define sns_facing_event_init_zero               {(sns_facing_event_state)0}

/* Field tags (for use in manual encoding/decoding) */
#define sns_facing_event_state_tag               1

/* Struct field encoding specification for nanopb */
extern const pb_field_t sns_facing_event_fields[2];

/* Maximum encoded size of messages (where known) */
#define sns_facing_event_size                    2

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define SNS_FACING_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
