/*===========================================================================

FILE:        ul_data.c

DESCRIPTION: This file implements the target-specific NPA Bus subnodes

   Copyright (c) 2017 QUALCOMM Technologies, Incorporated.
             All Rights Reserved
             QUALCOMM Proprietary/GTDR
-------------------------------------------------------------------------------

$Header: //components/rel/core.qdsp6/2.1/settings/systemdrivers/icb/config/cdsp/sdm845/ul_data.c#1 $ 
$DateTime: 2017/07/21 22:10:47 $
$Author: pwbldsvc $
$Change: 13907704 $

                      EDIT HISTORY FOR FILE

 Autogenerated for target: CDSP
 This file was generated using Autogen script: 
 gen.py

 when         who     what, where, why
 ----------   ---     -----------------------------------------------------------
 2017/04/13 Autogen  Autogenerated version

=============================================================================*/
#include "ul_i.h"
#include "ul_tree.h"
#include "icb_soc_data.h"

/****************************************************************************/
/*                              COMPUTE_DSP RSC                             */
/****************************************************************************/

/****************************************************************************/
/*                              BUSES                                       */
/****************************************************************************/
/**** Bus: cdsp_noc ****/
static HAL_noc_InfoType cdsp_noc_hal_info =
{
  0,        /* Base address */
  3, /* Number of masters with QoS */ 
  0x0, /* QoS offset */
  0x100, /* QoS block size */
};

static icb_bus_def_type bus_cdsp_noc =
{
  "+TURING_CDSP_NOC", /* HWIO base name */
  0, /* base address */
  0x2000, /* HWIO region size */
  ICB_BUS_NOC, /* Bus type */
  (void *)&cdsp_noc_hal_info, /* Bus info structure */
  0,    /* No enable/disable config clocks. */
  NULL,
  NULL,
  0,    /* No power domains. */
  NULL,
  NULL,
};

/**** Bus: config_noc ****/
static HAL_noc_InfoType config_noc_hal_info =
{
  0,        /* Base address */
  0, /* Number of masters with QoS */ 
  0x0, /* QoS offset */
  0x0, /* QoS block size */
};

static icb_bus_def_type bus_config_noc =
{
  NULL, /* HWIO base: +CNOC_SERVICE_NETWORK unused, no qos to configure */
  0, /* base address */
  0x6000, /* HWIO region size */
  ICB_BUS_NOC, /* Bus type */
  (void *)&config_noc_hal_info, /* Bus info structure */
  0,    /* No enable/disable config clocks. */
  NULL,
  NULL,
  0,    /* No power domains. */
  NULL,
  NULL,
};

/**** Bus: dc_noc ****/
static HAL_noc_InfoType dc_noc_hal_info =
{
  0,        /* Base address */
  0, /* Number of masters with QoS */ 
  0x0, /* QoS offset */
  0x0, /* QoS block size */
};

static icb_bus_def_type bus_dc_noc =
{
  NULL, /* HWIO base: DC_NOC_DC_NOC unused, no qos to configure */
  0, /* base address */
  0x1000, /* HWIO region size */
  ICB_BUS_NOC, /* Bus type */
  (void *)&dc_noc_hal_info, /* Bus info structure */
  0,    /* No enable/disable config clocks. */
  NULL,
  NULL,
  0,    /* No power domains. */
  NULL,
  NULL,
};

/**** Bus: mc_virt ****/

static icb_bus_def_type bus_mc_virt =
{
  NULL, /* HWIO base unused for virtual bus */
  0, /* base address */
  0x0, /* HWIO region size */
  ICB_BUS_VIRT, /* Bus type */
  NULL, /* Bus info structure */
  0,    /* No enable/disable config clocks. */
  NULL,
  NULL,
  0,    /* No power domains. */
  NULL,
  NULL,
};

/**** Bus: mem_noc ****/
static HAL_noc_InfoType mem_noc_hal_info =
{
  0,        /* Base address */
  7, /* Number of masters with QoS */ 
  0x10000, /* QoS offset */
  0x1000, /* QoS block size */
};

static icb_bus_def_type bus_mem_noc =
{
  "+MEMNOC_MEM_NOC", /* HWIO base name */
  0, /* base address */
  0x28000, /* HWIO region size */
  ICB_BUS_NOC, /* Bus type */
  (void *)&mem_noc_hal_info, /* Bus info structure */
  0,    /* No enable/disable config clocks. */
  NULL,
  NULL,
  0,    /* No power domains. */
  NULL,
  NULL,
};

/**** Bus: system_noc ****/
static HAL_noc_InfoType system_noc_hal_info =
{
  0,        /* Base address */
  0, /* Number of masters with QoS */ 
  0x9000, /* QoS offset */
  0x1000, /* QoS block size */
};

static icb_bus_def_type bus_system_noc =
{
  NULL, /* HWIO base: SYSTEM_NOC unused, no qos to configure */
  0, /* base address */
  0x19000, /* HWIO region size */
  ICB_BUS_NOC, /* Bus type */
  (void *)&system_noc_hal_info, /* Bus info structure */
  0,    /* No enable/disable config clocks. */
  NULL,
  NULL,
  0,    /* No power domains. */
  NULL,
  NULL,
};

/**** Bus: vapss_noc ****/
static HAL_noc_InfoType vapss_noc_hal_info =
{
  0,        /* Base address */
  0, /* Number of masters with QoS */ 
  0x0, /* QoS offset */
  0x0, /* QoS block size */
};

static icb_bus_def_type bus_vapss_noc =
{
  NULL, /* HWIO base: VAPSS_NOC unused, no qos to configure */
  0, /* base address */
  0x2000, /* HWIO region size */
  ICB_BUS_NOC, /* Bus type */
  (void *)&vapss_noc_hal_info, /* Bus info structure */
  0,    /* No enable/disable config clocks. */
  NULL,
  NULL,
  0,    /* No power domains. */
  NULL,
  NULL,
};

/****************************************************************************/
/*                              HW NODES                                    */
/****************************************************************************/
static icb_hw_request_type *hw_node_acv_requests[1];
static icb_hw_request_type *hw_node_acv_queries[1];

static icb_hw_node_type hw_node_acv =
{
  "ACV",
  ICB_HW_NODE_KIND_VECTOR,
  0, /* hw_id */
  0, /* width */
  0, /* bw_unit */
  0, /* clk_id */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* node state */
  0x8, /* output state */
  { NULL, ICB_HW_VECTOR_REQUEST, NULL, false }, /* node request */
  { NULL, NULL, 0, false }, /* active/wake rpm request */
  { NULL, NULL, 0, false }, /* sleep rpm request */
  { 0, 1, hw_node_acv_requests }, /* request list */
  { 0, 1, hw_node_acv_queries }, /* query list */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* query state */
};

static icb_hw_node_type hw_node_alc =
{
  "ALC",
  ICB_HW_NODE_KIND_RAW,
  0, /* hw_id */
  0, /* width */
  0, /* bw_unit */
  0, /* clk_id */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* node state */
  0, /* output state */
  { NULL, ICB_HW_NO_REQUEST, NULL, false }, /* node request */
  { NULL, NULL, 0, false }, /* active/wake rpm request */
  { NULL, NULL, 0, false }, /* sleep rpm request */
  { 0, 0, NULL }, /* request list */
  { 0, 0, NULL }, /* query list */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* query state */
};

static icb_hw_request_type *hw_node_mc0_requests[1];
static icb_hw_request_type *hw_node_mc0_queries[1];

static icb_hw_node_type hw_node_mc0 =
{
  "MC0",
  ICB_HW_NODE_KIND_BANDWIDTH,
  0, /* hw_id */
  0, /* width */
  0, /* bw_unit */
  0, /* clk_id */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* node state */
  0, /* output state */
  { NULL, ICB_HW_BANDWIDTH_REQUEST, NULL, false }, /* node request */
  { NULL, NULL, 0, false }, /* active/wake rpm request */
  { NULL, NULL, 0, false }, /* sleep rpm request */
  { 0, 1, hw_node_mc0_requests }, /* request list */
  { 0, 1, hw_node_mc0_queries }, /* query list */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* query state */
};

static icb_hw_request_type *hw_node_sh0_requests[1];
static icb_hw_request_type *hw_node_sh0_queries[1];

static icb_hw_node_type hw_node_sh0 =
{
  "SH0",
  ICB_HW_NODE_KIND_BANDWIDTH,
  0, /* hw_id */
  0, /* width */
  0, /* bw_unit */
  0, /* clk_id */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* node state */
  0, /* output state */
  { NULL, ICB_HW_BANDWIDTH_REQUEST, NULL, false }, /* node request */
  { NULL, NULL, 0, false }, /* active/wake rpm request */
  { NULL, NULL, 0, false }, /* sleep rpm request */
  { 0, 1, hw_node_sh0_requests }, /* request list */
  { 0, 1, hw_node_sh0_queries }, /* query list */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* query state */
};

static icb_hw_request_type *hw_node_cn0_requests[60];
static icb_hw_request_type *hw_node_cn0_queries[60];

static icb_hw_node_type hw_node_cn0 =
{
  "CN0",
  ICB_HW_NODE_KIND_BANDWIDTH,
  0, /* hw_id */
  0, /* width */
  0, /* bw_unit */
  0, /* clk_id */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* node state */
  0, /* output state */
  { NULL, ICB_HW_BANDWIDTH_REQUEST, NULL, false }, /* node request */
  { NULL, NULL, 0, false }, /* active/wake rpm request */
  { NULL, NULL, 0, false }, /* sleep rpm request */
  { 0, 60, hw_node_cn0_requests }, /* request list */
  { 0, 60, hw_node_cn0_queries }, /* query list */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* query state */
};

static icb_hw_request_type *hw_node_sh1_requests[1];
static icb_hw_request_type *hw_node_sh1_queries[1];

static icb_hw_node_type hw_node_sh1 =
{
  "SH1",
  ICB_HW_NODE_KIND_BANDWIDTH,
  0, /* hw_id */
  0, /* width */
  0, /* bw_unit */
  0, /* clk_id */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* node state */
  0, /* output state */
  { NULL, ICB_HW_BANDWIDTH_REQUEST, NULL, false }, /* node request */
  { NULL, NULL, 0, false }, /* active/wake rpm request */
  { NULL, NULL, 0, false }, /* sleep rpm request */
  { 0, 1, hw_node_sh1_requests }, /* request list */
  { 0, 1, hw_node_sh1_queries }, /* query list */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* query state */
};

static icb_hw_request_type *hw_node_sh2_requests[1];
static icb_hw_request_type *hw_node_sh2_queries[1];

static icb_hw_node_type hw_node_sh2 =
{
  "SH2",
  ICB_HW_NODE_KIND_BANDWIDTH,
  0, /* hw_id */
  0, /* width */
  0, /* bw_unit */
  0, /* clk_id */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* node state */
  0, /* output state */
  { NULL, ICB_HW_BANDWIDTH_REQUEST, NULL, false }, /* node request */
  { NULL, NULL, 0, false }, /* active/wake rpm request */
  { NULL, NULL, 0, false }, /* sleep rpm request */
  { 0, 1, hw_node_sh2_requests }, /* request list */
  { 0, 1, hw_node_sh2_queries }, /* query list */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* query state */
};

static icb_hw_request_type *hw_node_sh4_requests[1];
static icb_hw_request_type *hw_node_sh4_queries[1];

static icb_hw_node_type hw_node_sh4 =
{
  "SH4",
  ICB_HW_NODE_KIND_BANDWIDTH,
  0, /* hw_id */
  0, /* width */
  0, /* bw_unit */
  0, /* clk_id */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* node state */
  0, /* output state */
  { NULL, ICB_HW_BANDWIDTH_REQUEST, NULL, false }, /* node request */
  { NULL, NULL, 0, false }, /* active/wake rpm request */
  { NULL, NULL, 0, false }, /* sleep rpm request */
  { 0, 1, hw_node_sh4_requests }, /* request list */
  { 0, 1, hw_node_sh4_queries }, /* query list */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* query state */
};

static icb_hw_request_type *hw_node_sn1_requests[1];
static icb_hw_request_type *hw_node_sn1_queries[1];

static icb_hw_node_type hw_node_sn1 =
{
  "SN1",
  ICB_HW_NODE_KIND_BANDWIDTH,
  0, /* hw_id */
  0, /* width */
  0, /* bw_unit */
  0, /* clk_id */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* node state */
  0, /* output state */
  { NULL, ICB_HW_BANDWIDTH_REQUEST, NULL, false }, /* node request */
  { NULL, NULL, 0, false }, /* active/wake rpm request */
  { NULL, NULL, 0, false }, /* sleep rpm request */
  { 0, 1, hw_node_sn1_requests }, /* request list */
  { 0, 1, hw_node_sn1_queries }, /* query list */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* query state */
};

static icb_hw_request_type *hw_node_sn3_requests[1];
static icb_hw_request_type *hw_node_sn3_queries[1];

static icb_hw_node_type hw_node_sn3 =
{
  "SN3",
  ICB_HW_NODE_KIND_BANDWIDTH,
  0, /* hw_id */
  0, /* width */
  0, /* bw_unit */
  0, /* clk_id */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* node state */
  0, /* output state */
  { NULL, ICB_HW_BANDWIDTH_REQUEST, NULL, false }, /* node request */
  { NULL, NULL, 0, false }, /* active/wake rpm request */
  { NULL, NULL, 0, false }, /* sleep rpm request */
  { 0, 1, hw_node_sn3_requests }, /* request list */
  { 0, 1, hw_node_sn3_queries }, /* query list */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* query state */
};

static icb_hw_request_type *hw_node_sn5_requests[1];
static icb_hw_request_type *hw_node_sn5_queries[1];

static icb_hw_node_type hw_node_sn5 =
{
  "SN5",
  ICB_HW_NODE_KIND_BANDWIDTH,
  0, /* hw_id */
  0, /* width */
  0, /* bw_unit */
  0, /* clk_id */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* node state */
  0, /* output state */
  { NULL, ICB_HW_BANDWIDTH_REQUEST, NULL, false }, /* node request */
  { NULL, NULL, 0, false }, /* active/wake rpm request */
  { NULL, NULL, 0, false }, /* sleep rpm request */
  { 0, 1, hw_node_sn5_requests }, /* request list */
  { 0, 1, hw_node_sn5_queries }, /* query list */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* query state */
};

static icb_hw_request_type *hw_node_sn15_requests[1];
static icb_hw_request_type *hw_node_sn15_queries[1];

static icb_hw_node_type hw_node_sn15 =
{
  "SN15",
  ICB_HW_NODE_KIND_BANDWIDTH,
  0, /* hw_id */
  0, /* width */
  0, /* bw_unit */
  0, /* clk_id */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* node state */
  0, /* output state */
  { NULL, ICB_HW_BANDWIDTH_REQUEST, NULL, false }, /* node request */
  { NULL, NULL, 0, false }, /* active/wake rpm request */
  { NULL, NULL, 0, false }, /* sleep rpm request */
  { 0, 1, hw_node_sn15_requests }, /* request list */
  { 0, 1, hw_node_sn15_queries }, /* query list */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* query state */
};

/****************************************************************************/
/*                              MASTERS                                     */
/****************************************************************************/
/**** Master: llcc_mc ****/
/* master definition */
static icb_master_def_type master_llcc_mc =
{
  "llcc_mc",
  ICBID_MASTER_LLCC, /* master id */
  &bus_mc_virt, /* bus */
  4, /* width in bytes */
  0, /* number of qos ports */
  NULL, /* qos ports */
  4, /* Number of ports for aggregation purposes */
  false, /* Locally managed QoS? */
  NULL, /* qos policy */
  NULL, /* qos policy override */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* node state */
  { NULL, ICB_MASTER_BW_REQUEST, NULL, false }, /* Bandwidth request structure */
  { NULL, ICB_MASTER_LATENCY_REQUEST, NULL, false }, /* Latency request structure */
  { ICB_MASTER_HW_REQUEST, NULL }, /* Hardware request structure */
  { 0, 0, NULL }, /* request list */
  0,
  NULL, /* no bw nodes */
  0,
  NULL, /* no latency nodes */
  { NULL, 0 }, /* notification list */
  { 0, 0, NULL }, /* query list */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* query state */
};

/**** Master: q6_client_0 ****/
/* master definition */
static icb_master_def_type master_q6_client_0 =
{
  "q6_client_0",
  ICBID_MASTER_CDSP_HCP_TCM, /* master id */
  &bus_vapss_noc, /* bus */
  16, /* width in bytes */
  0, /* number of qos ports */
  NULL, /* qos ports */
  1, /* Number of ports for aggregation purposes */
  false, /* Locally managed QoS? */
  NULL, /* qos policy */
  NULL, /* qos policy override */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* node state */
  { NULL, ICB_MASTER_BW_REQUEST, NULL, false }, /* Bandwidth request structure */
  { NULL, ICB_MASTER_LATENCY_REQUEST, NULL, false }, /* Latency request structure */
  { ICB_MASTER_HW_REQUEST, NULL }, /* Hardware request structure */
  { 0, 0, NULL }, /* request list */
  0,
  NULL, /* no bw nodes */
  0,
  NULL, /* no latency nodes */
  { NULL, 0 }, /* notification list */
  { 0, 0, NULL }, /* query list */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* query state */
};

/**** Master: q6_client_1 ****/
/* master definition */
static icb_master_def_type master_q6_client_1 =
{
  "q6_client_1",
  ICBID_MASTER_CDSP_DMA_TCM, /* master id */
  &bus_vapss_noc, /* bus */
  16, /* width in bytes */
  0, /* number of qos ports */
  NULL, /* qos ports */
  1, /* Number of ports for aggregation purposes */
  false, /* Locally managed QoS? */
  NULL, /* qos policy */
  NULL, /* qos policy override */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* node state */
  { NULL, ICB_MASTER_BW_REQUEST, NULL, false }, /* Bandwidth request structure */
  { NULL, ICB_MASTER_LATENCY_REQUEST, NULL, false }, /* Latency request structure */
  { ICB_MASTER_HW_REQUEST, NULL }, /* Hardware request structure */
  { 0, 0, NULL }, /* request list */
  0,
  NULL, /* no bw nodes */
  0,
  NULL, /* no latency nodes */
  { NULL, 0 }, /* notification list */
  { 0, 0, NULL }, /* query list */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* query state */
};

/**** Master: qhm_cdsp_noc_cfg ****/
/* master definition */
static icb_master_def_type master_qhm_cdsp_noc_cfg =
{
  "qhm_cdsp_noc_cfg",
  ICBID_MASTER_CDSP_NOC_CFG, /* master id */
  &bus_cdsp_noc, /* bus */
  4, /* width in bytes */
  0, /* number of qos ports */
  NULL, /* qos ports */
  1, /* Number of ports for aggregation purposes */
  false, /* Locally managed QoS? */
  NULL, /* qos policy */
  NULL, /* qos policy override */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* node state */
  { NULL, ICB_MASTER_BW_REQUEST, NULL, false }, /* Bandwidth request structure */
  { NULL, ICB_MASTER_LATENCY_REQUEST, NULL, false }, /* Latency request structure */
  { ICB_MASTER_HW_REQUEST, NULL }, /* Hardware request structure */
  { 0, 0, NULL }, /* request list */
  0,
  NULL, /* no bw nodes */
  0,
  NULL, /* no latency nodes */
  { NULL, 0 }, /* notification list */
  { 0, 0, NULL }, /* query list */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* query state */
};

/**** Master: qhm_cnoc ****/
/* master definition */
static icb_master_def_type master_qhm_cnoc =
{
  "qhm_cnoc",
  ICBID_MASTER_CNOC_DC_NOC, /* master id */
  &bus_dc_noc, /* bus */
  4, /* width in bytes */
  0, /* number of qos ports */
  NULL, /* qos ports */
  1, /* Number of ports for aggregation purposes */
  false, /* Locally managed QoS? */
  NULL, /* qos policy */
  NULL, /* qos policy override */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* node state */
  { NULL, ICB_MASTER_BW_REQUEST, NULL, false }, /* Bandwidth request structure */
  { NULL, ICB_MASTER_LATENCY_REQUEST, NULL, false }, /* Latency request structure */
  { ICB_MASTER_HW_REQUEST, NULL }, /* Hardware request structure */
  { 0, 0, NULL }, /* request list */
  0,
  NULL, /* no bw nodes */
  0,
  NULL, /* no latency nodes */
  { NULL, 0 }, /* notification list */
  { 0, 0, NULL }, /* query list */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* query state */
};

/**** Master: qhm_memnoc_cfg ****/
/* master definition */
static icb_master_def_type master_qhm_memnoc_cfg =
{
  "qhm_memnoc_cfg",
  ICBID_MASTER_MEM_NOC_CFG, /* master id */
  &bus_mem_noc, /* bus */
  4, /* width in bytes */
  0, /* number of qos ports */
  NULL, /* qos ports */
  1, /* Number of ports for aggregation purposes */
  false, /* Locally managed QoS? */
  NULL, /* qos policy */
  NULL, /* qos policy override */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* node state */
  { NULL, ICB_MASTER_BW_REQUEST, NULL, false }, /* Bandwidth request structure */
  { NULL, ICB_MASTER_LATENCY_REQUEST, NULL, false }, /* Latency request structure */
  { ICB_MASTER_HW_REQUEST, NULL }, /* Hardware request structure */
  { 0, 0, NULL }, /* request list */
  0,
  NULL, /* no bw nodes */
  0,
  NULL, /* no latency nodes */
  { NULL, 0 }, /* notification list */
  { 0, 0, NULL }, /* query list */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* query state */
};

/**** Master: qhm_vapss_noc_cfg ****/
/* master definition */
static icb_master_def_type master_qhm_vapss_noc_cfg =
{
  "qhm_vapss_noc_cfg",
  ICBID_MASTER_VAPSS_NOC_CFG, /* master id */
  &bus_vapss_noc, /* bus */
  4, /* width in bytes */
  0, /* number of qos ports */
  NULL, /* qos ports */
  1, /* Number of ports for aggregation purposes */
  false, /* Locally managed QoS? */
  NULL, /* qos policy */
  NULL, /* qos policy override */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* node state */
  { NULL, ICB_MASTER_BW_REQUEST, NULL, false }, /* Bandwidth request structure */
  { NULL, ICB_MASTER_LATENCY_REQUEST, NULL, false }, /* Latency request structure */
  { ICB_MASTER_HW_REQUEST, NULL }, /* Hardware request structure */
  { 0, 0, NULL }, /* request list */
  0,
  NULL, /* no bw nodes */
  0,
  NULL, /* no latency nodes */
  { NULL, 0 }, /* notification list */
  { 0, 0, NULL }, /* query list */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* query state */
};

/**** Master: qnm_cdsp ****/
static uint32_t master_qnm_cdsp_qos_ports[1] =
{
  6, /* port 0 */
};

/* master port default settings */
static icb_noc_master_policy_type master_qnm_cdsp_defaults =
{
  0, /**< default_priority */
  /**< limiter */
  {
    0, /**< bandwidth */
    0, /**< saturation */
  },
  false, /**< limiter_enabled */
  /**< regulator */
  {
    0, /**< low priority */
    0, /**< high priority */
    0, /**< bandwidth */
    0, /**< saturation */
  },
  /**< regulator_mode */
  {
    false, /**< read enable */
    false, /**< write enable */
  },
  true, /**< urgency_forwarding_enabled */
  false, /**< is_applied */
};

static icb_qos_policy_type master_qnm_cdsp_qos_policy =
{
  &master_qnm_cdsp_defaults,
};

static icb_hw_node_type *master_qnm_cdsp_bws[] =
{
  &hw_node_sh4,
};

/* master definition */
static icb_master_def_type master_qnm_cdsp =
{
  "qnm_cdsp",
  ICBID_MASTER_CDSP, /* master id */
  &bus_mem_noc, /* bus */
  32, /* width in bytes */
  1, /* number of qos ports */
  master_qnm_cdsp_qos_ports, /* qos ports */
  1, /* Number of ports for aggregation purposes */
  true, /* Locally managed QoS? */
  &master_qnm_cdsp_qos_policy, /* qos policy */
  NULL, /* qos policy override */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* node state */
  { NULL, ICB_MASTER_BW_REQUEST, NULL, false }, /* Bandwidth request structure */
  { NULL, ICB_MASTER_LATENCY_REQUEST, NULL, false }, /* Latency request structure */
  { ICB_MASTER_HW_REQUEST, NULL }, /* Hardware request structure */
  { 0, 0, NULL }, /* request list */
  1,
  master_qnm_cdsp_bws, /* bw nodes */
  0,
  NULL, /* no latency nodes */
  { NULL, 0 }, /* notification list */
  { 0, 0, NULL }, /* query list */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* query state */
};

/**** Master: qnm_memnoc ****/
static icb_hw_node_type *master_qnm_memnoc_bws[] =
{
  &hw_node_sn15,
};

/* master definition */
static icb_master_def_type master_qnm_memnoc =
{
  "qnm_memnoc",
  ICBID_MASTER_MEM_NOC_SNOC, /* master id */
  &bus_system_noc, /* bus */
  8, /* width in bytes */
  0, /* number of qos ports */
  NULL, /* qos ports */
  1, /* Number of ports for aggregation purposes */
  false, /* Locally managed QoS? */
  NULL, /* qos policy */
  NULL, /* qos policy override */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* node state */
  { NULL, ICB_MASTER_BW_REQUEST, NULL, false }, /* Bandwidth request structure */
  { NULL, ICB_MASTER_LATENCY_REQUEST, NULL, false }, /* Latency request structure */
  { ICB_MASTER_HW_REQUEST, NULL }, /* Hardware request structure */
  { 0, 0, NULL }, /* request list */
  1,
  master_qnm_memnoc_bws, /* bw nodes */
  0,
  NULL, /* no latency nodes */
  { NULL, 0 }, /* notification list */
  { 0, 0, NULL }, /* query list */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* query state */
};

/**** Master: qnm_snoc ****/
static icb_hw_node_type *master_qnm_snoc_bws[] =
{
  &hw_node_cn0,
};

/* master definition */
static icb_master_def_type master_qnm_snoc =
{
  "qnm_snoc",
  ICBID_MASTER_SNOC_CNOC, /* master id */
  &bus_config_noc, /* bus */
  8, /* width in bytes */
  0, /* number of qos ports */
  NULL, /* qos ports */
  1, /* Number of ports for aggregation purposes */
  false, /* Locally managed QoS? */
  NULL, /* qos policy */
  NULL, /* qos policy override */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* node state */
  { NULL, ICB_MASTER_BW_REQUEST, NULL, false }, /* Bandwidth request structure */
  { NULL, ICB_MASTER_LATENCY_REQUEST, NULL, false }, /* Latency request structure */
  { ICB_MASTER_HW_REQUEST, NULL }, /* Hardware request structure */
  { 0, 0, NULL }, /* request list */
  1,
  master_qnm_snoc_bws, /* bw nodes */
  0,
  NULL, /* no latency nodes */
  { NULL, 0 }, /* notification list */
  { 0, 0, NULL }, /* query list */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* query state */
};

/**** Master: qxm_q6 ****/
static uint32_t master_qxm_q6_qos_ports[1] =
{
  0, /* port 0 */
};

/* master port default settings */
static icb_noc_master_policy_type master_qxm_q6_defaults =
{
  0, /**< default_priority */
  /**< limiter */
  {
    0, /**< bandwidth */
    0, /**< saturation */
  },
  false, /**< limiter_enabled */
  /**< regulator */
  {
    0, /**< low priority */
    0, /**< high priority */
    0, /**< bandwidth */
    0, /**< saturation */
  },
  /**< regulator_mode */
  {
    false, /**< read enable */
    false, /**< write enable */
  },
  true, /**< urgency_forwarding_enabled */
  false, /**< is_applied */
};

static icb_qos_policy_type master_qxm_q6_qos_policy =
{
  &master_qxm_q6_defaults,
};

/* master definition */
static icb_master_def_type master_qxm_q6 =
{
  "qxm_q6",
  ICBID_MASTER_CDSP_PROC, /* master id */
  &bus_cdsp_noc, /* bus */
  32, /* width in bytes */
  1, /* number of qos ports */
  master_qxm_q6_qos_ports, /* qos ports */
  1, /* Number of ports for aggregation purposes */
  true, /* Locally managed QoS? */
  &master_qxm_q6_qos_policy, /* qos policy */
  NULL, /* qos policy override */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* node state */
  { NULL, ICB_MASTER_BW_REQUEST, NULL, false }, /* Bandwidth request structure */
  { NULL, ICB_MASTER_LATENCY_REQUEST, NULL, false }, /* Latency request structure */
  { ICB_MASTER_HW_REQUEST, NULL }, /* Hardware request structure */
  { 0, 0, NULL }, /* request list */
  0,
  NULL, /* no bw nodes */
  0,
  NULL, /* no latency nodes */
  { NULL, 0 }, /* notification list */
  { 0, 0, NULL }, /* query list */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* query state */
};

/**** Master: qxm_vapss_0 ****/
static uint32_t master_qxm_vapss_0_qos_ports[1] =
{
  1, /* port 0 */
};

/* master port default settings */
static icb_noc_master_policy_type master_qxm_vapss_0_defaults =
{
  1, /**< default_priority */
  /**< limiter */
  {
    0, /**< bandwidth */
    0, /**< saturation */
  },
  false, /**< limiter_enabled */
  /**< regulator */
  {
    0, /**< low priority */
    0, /**< high priority */
    0, /**< bandwidth */
    0, /**< saturation */
  },
  /**< regulator_mode */
  {
    false, /**< read enable */
    false, /**< write enable */
  },
  false, /**< urgency_forwarding_enabled */
  false, /**< is_applied */
};

static icb_qos_policy_type master_qxm_vapss_0_qos_policy =
{
  &master_qxm_vapss_0_defaults,
};

/* master definition */
static icb_master_def_type master_qxm_vapss_0 =
{
  "qxm_vapss_0",
  ICBID_MASTER_VAPSS_CDSP_0, /* master id */
  &bus_cdsp_noc, /* bus */
  16, /* width in bytes */
  1, /* number of qos ports */
  master_qxm_vapss_0_qos_ports, /* qos ports */
  1, /* Number of ports for aggregation purposes */
  true, /* Locally managed QoS? */
  &master_qxm_vapss_0_qos_policy, /* qos policy */
  NULL, /* qos policy override */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* node state */
  { NULL, ICB_MASTER_BW_REQUEST, NULL, false }, /* Bandwidth request structure */
  { NULL, ICB_MASTER_LATENCY_REQUEST, NULL, false }, /* Latency request structure */
  { ICB_MASTER_HW_REQUEST, NULL }, /* Hardware request structure */
  { 0, 0, NULL }, /* request list */
  0,
  NULL, /* no bw nodes */
  0,
  NULL, /* no latency nodes */
  { NULL, 0 }, /* notification list */
  { 0, 0, NULL }, /* query list */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* query state */
};

/**** Master: qxm_vapss_1 ****/
static uint32_t master_qxm_vapss_1_qos_ports[1] =
{
  2, /* port 0 */
};

/* master port default settings */
static icb_noc_master_policy_type master_qxm_vapss_1_defaults =
{
  1, /**< default_priority */
  /**< limiter */
  {
    0, /**< bandwidth */
    0, /**< saturation */
  },
  false, /**< limiter_enabled */
  /**< regulator */
  {
    0, /**< low priority */
    0, /**< high priority */
    0, /**< bandwidth */
    0, /**< saturation */
  },
  /**< regulator_mode */
  {
    false, /**< read enable */
    false, /**< write enable */
  },
  false, /**< urgency_forwarding_enabled */
  false, /**< is_applied */
};

static icb_qos_policy_type master_qxm_vapss_1_qos_policy =
{
  &master_qxm_vapss_1_defaults,
};

/* master definition */
static icb_master_def_type master_qxm_vapss_1 =
{
  "qxm_vapss_1",
  ICBID_MASTER_VAPSS_CDSP_1, /* master id */
  &bus_cdsp_noc, /* bus */
  16, /* width in bytes */
  1, /* number of qos ports */
  master_qxm_vapss_1_qos_ports, /* qos ports */
  1, /* Number of ports for aggregation purposes */
  true, /* Locally managed QoS? */
  &master_qxm_vapss_1_qos_policy, /* qos policy */
  NULL, /* qos policy override */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* node state */
  { NULL, ICB_MASTER_BW_REQUEST, NULL, false }, /* Bandwidth request structure */
  { NULL, ICB_MASTER_LATENCY_REQUEST, NULL, false }, /* Latency request structure */
  { ICB_MASTER_HW_REQUEST, NULL }, /* Hardware request structure */
  { 0, 0, NULL }, /* request list */
  0,
  NULL, /* no bw nodes */
  0,
  NULL, /* no latency nodes */
  { NULL, 0 }, /* notification list */
  { 0, 0, NULL }, /* query list */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* query state */
};

/**** Master: sys_client_0 ****/
/* master definition */
static icb_master_def_type master_sys_client_0 =
{
  "sys_client_0",
  ICBID_MASTER_CDSP_HCP, /* master id */
  &bus_vapss_noc, /* bus */
  16, /* width in bytes */
  0, /* number of qos ports */
  NULL, /* qos ports */
  1, /* Number of ports for aggregation purposes */
  false, /* Locally managed QoS? */
  NULL, /* qos policy */
  NULL, /* qos policy override */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* node state */
  { NULL, ICB_MASTER_BW_REQUEST, NULL, false }, /* Bandwidth request structure */
  { NULL, ICB_MASTER_LATENCY_REQUEST, NULL, false }, /* Latency request structure */
  { ICB_MASTER_HW_REQUEST, NULL }, /* Hardware request structure */
  { 0, 0, NULL }, /* request list */
  0,
  NULL, /* no bw nodes */
  0,
  NULL, /* no latency nodes */
  { NULL, 0 }, /* notification list */
  { 0, 0, NULL }, /* query list */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* query state */
};

/**** Master: sys_client_1 ****/
/* master definition */
static icb_master_def_type master_sys_client_1 =
{
  "sys_client_1",
  ICBID_MASTER_CDSP_DMA, /* master id */
  &bus_vapss_noc, /* bus */
  16, /* width in bytes */
  0, /* number of qos ports */
  NULL, /* qos ports */
  1, /* Number of ports for aggregation purposes */
  false, /* Locally managed QoS? */
  NULL, /* qos policy */
  NULL, /* qos policy override */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* node state */
  { NULL, ICB_MASTER_BW_REQUEST, NULL, false }, /* Bandwidth request structure */
  { NULL, ICB_MASTER_LATENCY_REQUEST, NULL, false }, /* Latency request structure */
  { ICB_MASTER_HW_REQUEST, NULL }, /* Hardware request structure */
  { 0, 0, NULL }, /* request list */
  0,
  NULL, /* no bw nodes */
  0,
  NULL, /* no latency nodes */
  { NULL, 0 }, /* notification list */
  { 0, 0, NULL }, /* query list */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* query state */
};

/****************************************************************************/
/*                              SLAVES                                      */
/****************************************************************************/
/**** Slave: ebi ****/
static icb_hw_node_type *slave_ebi_bws[] =
{
  &hw_node_mc0,
  &hw_node_acv,
};

static icb_slave_def_type slave_ebi =
{
  "ebi",
  ICBID_SLAVE_EBI1, /* id */
  &bus_mc_virt, /* bus */
  4, /* width in bytes */
  4, /* number of aggregation ports */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* node state */
  { NULL, ICB_SLAVE_BW_REQUEST, NULL, false }, /* Bandwidth request structure */
  { ICB_SLAVE_HW_REQUEST, NULL }, /* Hardware request structure */
  { 0, 0, NULL }, /* request list */
  2,
  slave_ebi_bws, /* bw nodes */
  { NULL, 0 }, /* notification list */
  { 0, 0, NULL }, /* query list */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* query state */
};

/**** Slave: qhs_aop ****/
static icb_hw_node_type *slave_qhs_aop_bws[] =
{
  &hw_node_cn0,
};

static icb_slave_def_type slave_qhs_aop =
{
  "qhs_aop",
  ICBID_SLAVE_AOP, /* id */
  &bus_config_noc, /* bus */
  4, /* width in bytes */
  1, /* number of aggregation ports */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* node state */
  { NULL, ICB_SLAVE_BW_REQUEST, NULL, false }, /* Bandwidth request structure */
  { ICB_SLAVE_HW_REQUEST, NULL }, /* Hardware request structure */
  { 0, 0, NULL }, /* request list */
  1,
  slave_qhs_aop_bws, /* bw nodes */
  { NULL, 0 }, /* notification list */
  { 0, 0, NULL }, /* query list */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* query state */
};

/**** Slave: qhs_aoss ****/
static icb_hw_node_type *slave_qhs_aoss_bws[] =
{
  &hw_node_cn0,
};

static icb_slave_def_type slave_qhs_aoss =
{
  "qhs_aoss",
  ICBID_SLAVE_AOSS, /* id */
  &bus_config_noc, /* bus */
  4, /* width in bytes */
  1, /* number of aggregation ports */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* node state */
  { NULL, ICB_SLAVE_BW_REQUEST, NULL, false }, /* Bandwidth request structure */
  { ICB_SLAVE_HW_REQUEST, NULL }, /* Hardware request structure */
  { 0, 0, NULL }, /* request list */
  1,
  slave_qhs_aoss_bws, /* bw nodes */
  { NULL, 0 }, /* notification list */
  { 0, 0, NULL }, /* query list */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* query state */
};

/**** Slave: qhs_clk_ctl ****/
static icb_hw_node_type *slave_qhs_clk_ctl_bws[] =
{
  &hw_node_cn0,
};

static icb_slave_def_type slave_qhs_clk_ctl =
{
  "qhs_clk_ctl",
  ICBID_SLAVE_CLK_CTL, /* id */
  &bus_config_noc, /* bus */
  4, /* width in bytes */
  1, /* number of aggregation ports */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* node state */
  { NULL, ICB_SLAVE_BW_REQUEST, NULL, false }, /* Bandwidth request structure */
  { ICB_SLAVE_HW_REQUEST, NULL }, /* Hardware request structure */
  { 0, 0, NULL }, /* request list */
  1,
  slave_qhs_clk_ctl_bws, /* bw nodes */
  { NULL, 0 }, /* notification list */
  { 0, 0, NULL }, /* query list */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* query state */
};

/**** Slave: qhs_dcc_cfg ****/
static icb_hw_node_type *slave_qhs_dcc_cfg_bws[] =
{
  &hw_node_cn0,
};

static icb_slave_def_type slave_qhs_dcc_cfg =
{
  "qhs_dcc_cfg",
  ICBID_SLAVE_DCC_CFG, /* id */
  &bus_config_noc, /* bus */
  4, /* width in bytes */
  1, /* number of aggregation ports */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* node state */
  { NULL, ICB_SLAVE_BW_REQUEST, NULL, false }, /* Bandwidth request structure */
  { ICB_SLAVE_HW_REQUEST, NULL }, /* Hardware request structure */
  { 0, 0, NULL }, /* request list */
  1,
  slave_qhs_dcc_cfg_bws, /* bw nodes */
  { NULL, 0 }, /* notification list */
  { 0, 0, NULL }, /* query list */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* query state */
};

/**** Slave: qhs_llcc ****/
static icb_slave_def_type slave_qhs_llcc =
{
  "qhs_llcc",
  ICBID_SLAVE_LLCC_CFG, /* id */
  &bus_dc_noc, /* bus */
  4, /* width in bytes */
  1, /* number of aggregation ports */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* node state */
  { NULL, ICB_SLAVE_BW_REQUEST, NULL, false }, /* Bandwidth request structure */
  { ICB_SLAVE_HW_REQUEST, NULL }, /* Hardware request structure */
  { 0, 0, NULL }, /* request list */
  0,
  NULL, /* no bw nodes */
  { NULL, 0 }, /* notification list */
  { 0, 0, NULL }, /* query list */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* query state */
};

/**** Slave: qhs_mdsp_ms_mpu_cfg ****/
static icb_slave_def_type slave_qhs_mdsp_ms_mpu_cfg =
{
  "qhs_mdsp_ms_mpu_cfg",
  ICBID_SLAVE_MSS_PROC_MS_MPU_CFG, /* id */
  &bus_mem_noc, /* bus */
  4, /* width in bytes */
  1, /* number of aggregation ports */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* node state */
  { NULL, ICB_SLAVE_BW_REQUEST, NULL, false }, /* Bandwidth request structure */
  { ICB_SLAVE_HW_REQUEST, NULL }, /* Hardware request structure */
  { 0, 0, NULL }, /* request list */
  0,
  NULL, /* no bw nodes */
  { NULL, 0 }, /* notification list */
  { 0, 0, NULL }, /* query list */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* query state */
};

/**** Slave: qhs_memnoc ****/
static icb_slave_def_type slave_qhs_memnoc =
{
  "qhs_memnoc",
  ICBID_SLAVE_MEM_NOC_CFG, /* id */
  &bus_dc_noc, /* bus */
  4, /* width in bytes */
  1, /* number of aggregation ports */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* node state */
  { NULL, ICB_SLAVE_BW_REQUEST, NULL, false }, /* Bandwidth request structure */
  { ICB_SLAVE_HW_REQUEST, NULL }, /* Hardware request structure */
  { 0, 0, NULL }, /* request list */
  0,
  NULL, /* no bw nodes */
  { NULL, 0 }, /* notification list */
  { 0, 0, NULL }, /* query list */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* query state */
};

/**** Slave: qhs_prng ****/
static icb_hw_node_type *slave_qhs_prng_bws[] =
{
  &hw_node_cn0,
};

static icb_slave_def_type slave_qhs_prng =
{
  "qhs_prng",
  ICBID_SLAVE_PRNG, /* id */
  &bus_config_noc, /* bus */
  4, /* width in bytes */
  1, /* number of aggregation ports */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* node state */
  { NULL, ICB_SLAVE_BW_REQUEST, NULL, false }, /* Bandwidth request structure */
  { ICB_SLAVE_HW_REQUEST, NULL }, /* Hardware request structure */
  { 0, 0, NULL }, /* request list */
  1,
  slave_qhs_prng_bws, /* bw nodes */
  { NULL, 0 }, /* notification list */
  { 0, 0, NULL }, /* query list */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* query state */
};

/**** Slave: qhs_tcsr ****/
static icb_hw_node_type *slave_qhs_tcsr_bws[] =
{
  &hw_node_cn0,
};

static icb_slave_def_type slave_qhs_tcsr =
{
  "qhs_tcsr",
  ICBID_SLAVE_TCSR, /* id */
  &bus_config_noc, /* bus */
  4, /* width in bytes */
  1, /* number of aggregation ports */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* node state */
  { NULL, ICB_SLAVE_BW_REQUEST, NULL, false }, /* Bandwidth request structure */
  { ICB_SLAVE_HW_REQUEST, NULL }, /* Hardware request structure */
  { 0, 0, NULL }, /* request list */
  1,
  slave_qhs_tcsr_bws, /* bw nodes */
  { NULL, 0 }, /* notification list */
  { 0, 0, NULL }, /* query list */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* query state */
};

/**** Slave: qhs_tlmm_north ****/
static icb_hw_node_type *slave_qhs_tlmm_north_bws[] =
{
  &hw_node_cn0,
};

static icb_slave_def_type slave_qhs_tlmm_north =
{
  "qhs_tlmm_north",
  ICBID_SLAVE_TLMM_NORTH, /* id */
  &bus_config_noc, /* bus */
  4, /* width in bytes */
  1, /* number of aggregation ports */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* node state */
  { NULL, ICB_SLAVE_BW_REQUEST, NULL, false }, /* Bandwidth request structure */
  { ICB_SLAVE_HW_REQUEST, NULL }, /* Hardware request structure */
  { 0, 0, NULL }, /* request list */
  1,
  slave_qhs_tlmm_north_bws, /* bw nodes */
  { NULL, 0 }, /* notification list */
  { 0, 0, NULL }, /* query list */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* query state */
};

/**** Slave: qhs_tlmm_south ****/
static icb_hw_node_type *slave_qhs_tlmm_south_bws[] =
{
  &hw_node_cn0,
};

static icb_slave_def_type slave_qhs_tlmm_south =
{
  "qhs_tlmm_south",
  ICBID_SLAVE_TLMM_SOUTH, /* id */
  &bus_config_noc, /* bus */
  4, /* width in bytes */
  1, /* number of aggregation ports */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* node state */
  { NULL, ICB_SLAVE_BW_REQUEST, NULL, false }, /* Bandwidth request structure */
  { ICB_SLAVE_HW_REQUEST, NULL }, /* Hardware request structure */
  { 0, 0, NULL }, /* request list */
  1,
  slave_qhs_tlmm_south_bws, /* bw nodes */
  { NULL, 0 }, /* notification list */
  { 0, 0, NULL }, /* query list */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* query state */
};

/**** Slave: qns_apps_io ****/
static icb_hw_node_type *slave_qns_apps_io_bws[] =
{
  &hw_node_sh1,
};

static icb_slave_def_type slave_qns_apps_io =
{
  "qns_apps_io",
  ICBID_SLAVE_MEM_NOC_GNOC, /* id */
  &bus_mem_noc, /* bus */
  32, /* width in bytes */
  1, /* number of aggregation ports */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* node state */
  { NULL, ICB_SLAVE_BW_REQUEST, NULL, false }, /* Bandwidth request structure */
  { ICB_SLAVE_HW_REQUEST, NULL }, /* Hardware request structure */
  { 0, 0, NULL }, /* request list */
  1,
  slave_qns_apps_io_bws, /* bw nodes */
  { NULL, 0 }, /* notification list */
  { 0, 0, NULL }, /* query list */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* query state */
};

/**** Slave: qns_cnoc ****/
static icb_hw_node_type *slave_qns_cnoc_bws[] =
{
  &hw_node_sn3,
};

static icb_slave_def_type slave_qns_cnoc =
{
  "qns_cnoc",
  ICBID_SLAVE_SNOC_CNOC, /* id */
  &bus_system_noc, /* bus */
  8, /* width in bytes */
  1, /* number of aggregation ports */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* node state */
  { NULL, ICB_SLAVE_BW_REQUEST, NULL, false }, /* Bandwidth request structure */
  { ICB_SLAVE_HW_REQUEST, NULL }, /* Hardware request structure */
  { 0, 0, NULL }, /* request list */
  1,
  slave_qns_cnoc_bws, /* bw nodes */
  { NULL, 0 }, /* notification list */
  { 0, 0, NULL }, /* query list */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* query state */
};

/**** Slave: qns_llcc ****/
static icb_hw_node_type *slave_qns_llcc_bws[] =
{
  &hw_node_sh0,
};

static icb_slave_def_type slave_qns_llcc =
{
  "qns_llcc",
  ICBID_SLAVE_LLCC, /* id */
  &bus_mem_noc, /* bus */
  16, /* width in bytes */
  4, /* number of aggregation ports */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* node state */
  { NULL, ICB_SLAVE_BW_REQUEST, NULL, false }, /* Bandwidth request structure */
  { ICB_SLAVE_HW_REQUEST, NULL }, /* Hardware request structure */
  { 0, 0, NULL }, /* request list */
  1,
  slave_qns_llcc_bws, /* bw nodes */
  { NULL, 0 }, /* notification list */
  { 0, 0, NULL }, /* query list */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* query state */
};

/**** Slave: qns_memnoc_snoc ****/
static icb_hw_node_type *slave_qns_memnoc_snoc_bws[] =
{
  &hw_node_sh2,
};

static icb_slave_def_type slave_qns_memnoc_snoc =
{
  "qns_memnoc_snoc",
  ICBID_SLAVE_MEM_NOC_SNOC, /* id */
  &bus_mem_noc, /* bus */
  8, /* width in bytes */
  1, /* number of aggregation ports */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* node state */
  { NULL, ICB_SLAVE_BW_REQUEST, NULL, false }, /* Bandwidth request structure */
  { ICB_SLAVE_HW_REQUEST, NULL }, /* Hardware request structure */
  { 0, 0, NULL }, /* request list */
  1,
  slave_qns_memnoc_snoc_bws, /* bw nodes */
  { NULL, 0 }, /* notification list */
  { 0, 0, NULL }, /* query list */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* query state */
};

/**** Slave: qns_sys ****/
static icb_slave_def_type slave_qns_sys =
{
  "qns_sys",
  ICBID_SLAVE_CDSP_MEM_NOC, /* id */
  &bus_cdsp_noc, /* bus */
  32, /* width in bytes */
  1, /* number of aggregation ports */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* node state */
  { NULL, ICB_SLAVE_BW_REQUEST, NULL, false }, /* Bandwidth request structure */
  { ICB_SLAVE_HW_REQUEST, NULL }, /* Hardware request structure */
  { 0, 0, NULL }, /* request list */
  0,
  NULL, /* no bw nodes */
  { NULL, 0 }, /* notification list */
  { 0, 0, NULL }, /* query list */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* query state */
};

/**** Slave: qxs_imem ****/
static icb_hw_node_type *slave_qxs_imem_bws[] =
{
  &hw_node_sn1,
};

static icb_slave_def_type slave_qxs_imem =
{
  "qxs_imem",
  ICBID_SLAVE_IMEM, /* id */
  &bus_system_noc, /* bus */
  8, /* width in bytes */
  1, /* number of aggregation ports */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* node state */
  { NULL, ICB_SLAVE_BW_REQUEST, NULL, false }, /* Bandwidth request structure */
  { ICB_SLAVE_HW_REQUEST, NULL }, /* Hardware request structure */
  { 0, 0, NULL }, /* request list */
  1,
  slave_qxs_imem_bws, /* bw nodes */
  { NULL, 0 }, /* notification list */
  { 0, 0, NULL }, /* query list */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* query state */
};

/**** Slave: qxs_q6 ****/
static icb_slave_def_type slave_qxs_q6 =
{
  "qxs_q6",
  ICBID_SLAVE_CDSP_TCM, /* id */
  &bus_vapss_noc, /* bus */
  16, /* width in bytes */
  1, /* number of aggregation ports */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* node state */
  { NULL, ICB_SLAVE_BW_REQUEST, NULL, false }, /* Bandwidth request structure */
  { ICB_SLAVE_HW_REQUEST, NULL }, /* Hardware request structure */
  { 0, 0, NULL }, /* request list */
  0,
  NULL, /* no bw nodes */
  { NULL, 0 }, /* notification list */
  { 0, 0, NULL }, /* query list */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* query state */
};

/**** Slave: qxs_sys_0 ****/
static icb_slave_def_type slave_qxs_sys_0 =
{
  "qxs_sys_0",
  ICBID_SLAVE_CDSP_HCP_VAPSS, /* id */
  &bus_vapss_noc, /* bus */
  16, /* width in bytes */
  1, /* number of aggregation ports */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* node state */
  { NULL, ICB_SLAVE_BW_REQUEST, NULL, false }, /* Bandwidth request structure */
  { ICB_SLAVE_HW_REQUEST, NULL }, /* Hardware request structure */
  { 0, 0, NULL }, /* request list */
  0,
  NULL, /* no bw nodes */
  { NULL, 0 }, /* notification list */
  { 0, 0, NULL }, /* query list */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* query state */
};

/**** Slave: qxs_sys_1 ****/
static icb_slave_def_type slave_qxs_sys_1 =
{
  "qxs_sys_1",
  ICBID_SLAVE_CDSP_DMA_VAPSS, /* id */
  &bus_vapss_noc, /* bus */
  16, /* width in bytes */
  1, /* number of aggregation ports */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* node state */
  { NULL, ICB_SLAVE_BW_REQUEST, NULL, false }, /* Bandwidth request structure */
  { ICB_SLAVE_HW_REQUEST, NULL }, /* Hardware request structure */
  { 0, 0, NULL }, /* request list */
  0,
  NULL, /* no bw nodes */
  { NULL, 0 }, /* notification list */
  { 0, 0, NULL }, /* query list */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* query state */
};

/**** Slave: srvc_cdsp_noc ****/
static icb_slave_def_type slave_srvc_cdsp_noc =
{
  "srvc_cdsp_noc",
  ICBID_SLAVE_SERVICE_CDSP_NOC, /* id */
  &bus_cdsp_noc, /* bus */
  4, /* width in bytes */
  1, /* number of aggregation ports */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* node state */
  { NULL, ICB_SLAVE_BW_REQUEST, NULL, false }, /* Bandwidth request structure */
  { ICB_SLAVE_HW_REQUEST, NULL }, /* Hardware request structure */
  { 0, 0, NULL }, /* request list */
  0,
  NULL, /* no bw nodes */
  { NULL, 0 }, /* notification list */
  { 0, 0, NULL }, /* query list */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* query state */
};

/**** Slave: srvc_memnoc ****/
static icb_slave_def_type slave_srvc_memnoc =
{
  "srvc_memnoc",
  ICBID_SLAVE_SERVICE_MEM_NOC, /* id */
  &bus_mem_noc, /* bus */
  4, /* width in bytes */
  1, /* number of aggregation ports */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* node state */
  { NULL, ICB_SLAVE_BW_REQUEST, NULL, false }, /* Bandwidth request structure */
  { ICB_SLAVE_HW_REQUEST, NULL }, /* Hardware request structure */
  { 0, 0, NULL }, /* request list */
  0,
  NULL, /* no bw nodes */
  { NULL, 0 }, /* notification list */
  { 0, 0, NULL }, /* query list */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* query state */
};

/**** Slave: srvc_vapss_noc ****/
static icb_slave_def_type slave_srvc_vapss_noc =
{
  "srvc_vapss_noc",
  ICBID_SLAVE_SERVICE_VAPSS_NOC, /* id */
  &bus_vapss_noc, /* bus */
  4, /* width in bytes */
  1, /* number of aggregation ports */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* node state */
  { NULL, ICB_SLAVE_BW_REQUEST, NULL, false }, /* Bandwidth request structure */
  { ICB_SLAVE_HW_REQUEST, NULL }, /* Hardware request structure */
  { 0, 0, NULL }, /* request list */
  0,
  NULL, /* no bw nodes */
  { NULL, 0 }, /* notification list */
  { 0, 0, NULL }, /* query list */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* query state */
};

/**** Slave: xs_qdss_stm ****/
static icb_hw_node_type *slave_xs_qdss_stm_bws[] =
{
  &hw_node_sn5,
};

static icb_slave_def_type slave_xs_qdss_stm =
{
  "xs_qdss_stm",
  ICBID_SLAVE_QDSS_STM, /* id */
  &bus_system_noc, /* bus */
  4, /* width in bytes */
  1, /* number of aggregation ports */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* node state */
  { NULL, ICB_SLAVE_BW_REQUEST, NULL, false }, /* Bandwidth request structure */
  { ICB_SLAVE_HW_REQUEST, NULL }, /* Hardware request structure */
  { 0, 0, NULL }, /* request list */
  1,
  slave_xs_qdss_stm_bws, /* bw nodes */
  { NULL, 0 }, /* notification list */
  { 0, 0, NULL }, /* query list */
  { 0ULL, 0ULL, 0ULL, 0ULL, 0ULL, 0, 0 }, /* query state */
};

/*============================================================================
                        TOPOLOGY ROUTE DECLARATIONS
============================================================================*/
/* Define the valid routes  */
static icb_pair_type route_llcc_mc_ebi_list_array[1] =
{
  {
    &master_llcc_mc,
    &slave_ebi
  },
};
static icb_route_list_type route_llcc_mc_ebi_list =
{
  1,
  route_llcc_mc_ebi_list_array
};
static icb_pair_type route_q6_client_0_qxs_q6_list_array[1] =
{
  {
    &master_q6_client_0,
    &slave_qxs_q6
  },
};
static icb_route_list_type route_q6_client_0_qxs_q6_list =
{
  1,
  route_q6_client_0_qxs_q6_list_array
};
static icb_pair_type route_q6_client_1_qxs_q6_list_array[1] =
{
  {
    &master_q6_client_1,
    &slave_qxs_q6
  },
};
static icb_route_list_type route_q6_client_1_qxs_q6_list =
{
  1,
  route_q6_client_1_qxs_q6_list_array
};
static icb_pair_type route_qhm_cdsp_noc_cfg_srvc_cdsp_noc_list_array[1] =
{
  {
    &master_qhm_cdsp_noc_cfg,
    &slave_srvc_cdsp_noc
  },
};
static icb_route_list_type route_qhm_cdsp_noc_cfg_srvc_cdsp_noc_list =
{
  1,
  route_qhm_cdsp_noc_cfg_srvc_cdsp_noc_list_array
};
static icb_pair_type route_qhm_vapss_noc_cfg_srvc_vapss_noc_list_array[1] =
{
  {
    &master_qhm_vapss_noc_cfg,
    &slave_srvc_vapss_noc
  },
};
static icb_route_list_type route_qhm_vapss_noc_cfg_srvc_vapss_noc_list =
{
  1,
  route_qhm_vapss_noc_cfg_srvc_vapss_noc_list_array
};
static icb_pair_type route_qxm_q6_ebi_list_array[3] =
{
  {
    &master_qxm_q6,
    &slave_qns_sys
  },
  {
    &master_qnm_cdsp,
    &slave_qns_llcc
  },
  {
    &master_llcc_mc,
    &slave_ebi
  },
};
static icb_route_list_type route_qxm_q6_ebi_list =
{
  3,
  route_qxm_q6_ebi_list_array
};
static icb_pair_type route_qxm_q6_qhs_aop_list_array[4] =
{
  {
    &master_qxm_q6,
    &slave_qns_sys
  },
  {
    &master_qnm_cdsp,
    &slave_qns_memnoc_snoc
  },
  {
    &master_qnm_memnoc,
    &slave_qns_cnoc
  },
  {
    &master_qnm_snoc,
    &slave_qhs_aop
  },
};
static icb_route_list_type route_qxm_q6_qhs_aop_list =
{
  4,
  route_qxm_q6_qhs_aop_list_array
};
static icb_pair_type route_qxm_q6_qhs_aoss_list_array[4] =
{
  {
    &master_qxm_q6,
    &slave_qns_sys
  },
  {
    &master_qnm_cdsp,
    &slave_qns_memnoc_snoc
  },
  {
    &master_qnm_memnoc,
    &slave_qns_cnoc
  },
  {
    &master_qnm_snoc,
    &slave_qhs_aoss
  },
};
static icb_route_list_type route_qxm_q6_qhs_aoss_list =
{
  4,
  route_qxm_q6_qhs_aoss_list_array
};
static icb_pair_type route_qxm_q6_qhs_clk_ctl_list_array[4] =
{
  {
    &master_qxm_q6,
    &slave_qns_sys
  },
  {
    &master_qnm_cdsp,
    &slave_qns_memnoc_snoc
  },
  {
    &master_qnm_memnoc,
    &slave_qns_cnoc
  },
  {
    &master_qnm_snoc,
    &slave_qhs_clk_ctl
  },
};
static icb_route_list_type route_qxm_q6_qhs_clk_ctl_list =
{
  4,
  route_qxm_q6_qhs_clk_ctl_list_array
};
static icb_pair_type route_qxm_q6_qhs_llcc_list_array[5] =
{
  {
    &master_qxm_q6,
    &slave_qns_sys
  },
  {
    &master_qnm_cdsp,
    &slave_qns_memnoc_snoc
  },
  {
    &master_qnm_memnoc,
    &slave_qns_cnoc
  },
  {
    &master_qnm_snoc,
    &slave_qhs_dcc_cfg
  },
  {
    &master_qhm_cnoc,
    &slave_qhs_llcc
  },
};
static icb_route_list_type route_qxm_q6_qhs_llcc_list =
{
  5,
  route_qxm_q6_qhs_llcc_list_array
};
static icb_pair_type route_qxm_q6_qhs_mdsp_ms_mpu_cfg_list_array[6] =
{
  {
    &master_qxm_q6,
    &slave_qns_sys
  },
  {
    &master_qnm_cdsp,
    &slave_qns_memnoc_snoc
  },
  {
    &master_qnm_memnoc,
    &slave_qns_cnoc
  },
  {
    &master_qnm_snoc,
    &slave_qhs_dcc_cfg
  },
  {
    &master_qhm_cnoc,
    &slave_qhs_memnoc
  },
  {
    &master_qhm_memnoc_cfg,
    &slave_qhs_mdsp_ms_mpu_cfg
  },
};
static icb_route_list_type route_qxm_q6_qhs_mdsp_ms_mpu_cfg_list =
{
  6,
  route_qxm_q6_qhs_mdsp_ms_mpu_cfg_list_array
};
static icb_pair_type route_qxm_q6_qhs_prng_list_array[4] =
{
  {
    &master_qxm_q6,
    &slave_qns_sys
  },
  {
    &master_qnm_cdsp,
    &slave_qns_memnoc_snoc
  },
  {
    &master_qnm_memnoc,
    &slave_qns_cnoc
  },
  {
    &master_qnm_snoc,
    &slave_qhs_prng
  },
};
static icb_route_list_type route_qxm_q6_qhs_prng_list =
{
  4,
  route_qxm_q6_qhs_prng_list_array
};
static icb_pair_type route_qxm_q6_qhs_tcsr_list_array[4] =
{
  {
    &master_qxm_q6,
    &slave_qns_sys
  },
  {
    &master_qnm_cdsp,
    &slave_qns_memnoc_snoc
  },
  {
    &master_qnm_memnoc,
    &slave_qns_cnoc
  },
  {
    &master_qnm_snoc,
    &slave_qhs_tcsr
  },
};
static icb_route_list_type route_qxm_q6_qhs_tcsr_list =
{
  4,
  route_qxm_q6_qhs_tcsr_list_array
};
static icb_pair_type route_qxm_q6_qhs_tlmm_north_list_array[4] =
{
  {
    &master_qxm_q6,
    &slave_qns_sys
  },
  {
    &master_qnm_cdsp,
    &slave_qns_memnoc_snoc
  },
  {
    &master_qnm_memnoc,
    &slave_qns_cnoc
  },
  {
    &master_qnm_snoc,
    &slave_qhs_tlmm_north
  },
};
static icb_route_list_type route_qxm_q6_qhs_tlmm_north_list =
{
  4,
  route_qxm_q6_qhs_tlmm_north_list_array
};
static icb_pair_type route_qxm_q6_qhs_tlmm_south_list_array[4] =
{
  {
    &master_qxm_q6,
    &slave_qns_sys
  },
  {
    &master_qnm_cdsp,
    &slave_qns_memnoc_snoc
  },
  {
    &master_qnm_memnoc,
    &slave_qns_cnoc
  },
  {
    &master_qnm_snoc,
    &slave_qhs_tlmm_south
  },
};
static icb_route_list_type route_qxm_q6_qhs_tlmm_south_list =
{
  4,
  route_qxm_q6_qhs_tlmm_south_list_array
};
static icb_pair_type route_qxm_q6_qns_apps_io_list_array[2] =
{
  {
    &master_qxm_q6,
    &slave_qns_sys
  },
  {
    &master_qnm_cdsp,
    &slave_qns_apps_io
  },
};
static icb_route_list_type route_qxm_q6_qns_apps_io_list =
{
  2,
  route_qxm_q6_qns_apps_io_list_array
};
static icb_pair_type route_qxm_q6_qns_llcc_list_array[2] =
{
  {
    &master_qxm_q6,
    &slave_qns_sys
  },
  {
    &master_qnm_cdsp,
    &slave_qns_llcc
  },
};
static icb_route_list_type route_qxm_q6_qns_llcc_list =
{
  2,
  route_qxm_q6_qns_llcc_list_array
};
static icb_pair_type route_qxm_q6_qxs_imem_list_array[3] =
{
  {
    &master_qxm_q6,
    &slave_qns_sys
  },
  {
    &master_qnm_cdsp,
    &slave_qns_memnoc_snoc
  },
  {
    &master_qnm_memnoc,
    &slave_qxs_imem
  },
};
static icb_route_list_type route_qxm_q6_qxs_imem_list =
{
  3,
  route_qxm_q6_qxs_imem_list_array
};
static icb_pair_type route_qxm_q6_srvc_memnoc_list_array[6] =
{
  {
    &master_qxm_q6,
    &slave_qns_sys
  },
  {
    &master_qnm_cdsp,
    &slave_qns_memnoc_snoc
  },
  {
    &master_qnm_memnoc,
    &slave_qns_cnoc
  },
  {
    &master_qnm_snoc,
    &slave_qhs_dcc_cfg
  },
  {
    &master_qhm_cnoc,
    &slave_qhs_memnoc
  },
  {
    &master_qhm_memnoc_cfg,
    &slave_srvc_memnoc
  },
};
static icb_route_list_type route_qxm_q6_srvc_memnoc_list =
{
  6,
  route_qxm_q6_srvc_memnoc_list_array
};
static icb_pair_type route_qxm_q6_xs_qdss_stm_list_array[3] =
{
  {
    &master_qxm_q6,
    &slave_qns_sys
  },
  {
    &master_qnm_cdsp,
    &slave_qns_memnoc_snoc
  },
  {
    &master_qnm_memnoc,
    &slave_xs_qdss_stm
  },
};
static icb_route_list_type route_qxm_q6_xs_qdss_stm_list =
{
  3,
  route_qxm_q6_xs_qdss_stm_list_array
};
static icb_pair_type route_sys_client_0_ebi_list_array[4] =
{
  {
    &master_sys_client_0,
    &slave_qxs_sys_0
  },
  {
    &master_qxm_vapss_0,
    &slave_qns_sys
  },
  {
    &master_qnm_cdsp,
    &slave_qns_llcc
  },
  {
    &master_llcc_mc,
    &slave_ebi
  },
};
static icb_route_list_type route_sys_client_0_ebi_list =
{
  4,
  route_sys_client_0_ebi_list_array
};
static icb_pair_type route_sys_client_0_qhs_aop_list_array[5] =
{
  {
    &master_sys_client_0,
    &slave_qxs_sys_0
  },
  {
    &master_qxm_vapss_0,
    &slave_qns_sys
  },
  {
    &master_qnm_cdsp,
    &slave_qns_memnoc_snoc
  },
  {
    &master_qnm_memnoc,
    &slave_qns_cnoc
  },
  {
    &master_qnm_snoc,
    &slave_qhs_aop
  },
};
static icb_route_list_type route_sys_client_0_qhs_aop_list =
{
  5,
  route_sys_client_0_qhs_aop_list_array
};
static icb_pair_type route_sys_client_0_qhs_aoss_list_array[5] =
{
  {
    &master_sys_client_0,
    &slave_qxs_sys_0
  },
  {
    &master_qxm_vapss_0,
    &slave_qns_sys
  },
  {
    &master_qnm_cdsp,
    &slave_qns_memnoc_snoc
  },
  {
    &master_qnm_memnoc,
    &slave_qns_cnoc
  },
  {
    &master_qnm_snoc,
    &slave_qhs_aoss
  },
};
static icb_route_list_type route_sys_client_0_qhs_aoss_list =
{
  5,
  route_sys_client_0_qhs_aoss_list_array
};
static icb_pair_type route_sys_client_0_qhs_clk_ctl_list_array[5] =
{
  {
    &master_sys_client_0,
    &slave_qxs_sys_0
  },
  {
    &master_qxm_vapss_0,
    &slave_qns_sys
  },
  {
    &master_qnm_cdsp,
    &slave_qns_memnoc_snoc
  },
  {
    &master_qnm_memnoc,
    &slave_qns_cnoc
  },
  {
    &master_qnm_snoc,
    &slave_qhs_clk_ctl
  },
};
static icb_route_list_type route_sys_client_0_qhs_clk_ctl_list =
{
  5,
  route_sys_client_0_qhs_clk_ctl_list_array
};
static icb_pair_type route_sys_client_0_qhs_llcc_list_array[6] =
{
  {
    &master_sys_client_0,
    &slave_qxs_sys_0
  },
  {
    &master_qxm_vapss_0,
    &slave_qns_sys
  },
  {
    &master_qnm_cdsp,
    &slave_qns_memnoc_snoc
  },
  {
    &master_qnm_memnoc,
    &slave_qns_cnoc
  },
  {
    &master_qnm_snoc,
    &slave_qhs_dcc_cfg
  },
  {
    &master_qhm_cnoc,
    &slave_qhs_llcc
  },
};
static icb_route_list_type route_sys_client_0_qhs_llcc_list =
{
  6,
  route_sys_client_0_qhs_llcc_list_array
};
static icb_pair_type route_sys_client_0_qhs_mdsp_ms_mpu_cfg_list_array[7] =
{
  {
    &master_sys_client_0,
    &slave_qxs_sys_0
  },
  {
    &master_qxm_vapss_0,
    &slave_qns_sys
  },
  {
    &master_qnm_cdsp,
    &slave_qns_memnoc_snoc
  },
  {
    &master_qnm_memnoc,
    &slave_qns_cnoc
  },
  {
    &master_qnm_snoc,
    &slave_qhs_dcc_cfg
  },
  {
    &master_qhm_cnoc,
    &slave_qhs_memnoc
  },
  {
    &master_qhm_memnoc_cfg,
    &slave_qhs_mdsp_ms_mpu_cfg
  },
};
static icb_route_list_type route_sys_client_0_qhs_mdsp_ms_mpu_cfg_list =
{
  7,
  route_sys_client_0_qhs_mdsp_ms_mpu_cfg_list_array
};
static icb_pair_type route_sys_client_0_qhs_prng_list_array[5] =
{
  {
    &master_sys_client_0,
    &slave_qxs_sys_0
  },
  {
    &master_qxm_vapss_0,
    &slave_qns_sys
  },
  {
    &master_qnm_cdsp,
    &slave_qns_memnoc_snoc
  },
  {
    &master_qnm_memnoc,
    &slave_qns_cnoc
  },
  {
    &master_qnm_snoc,
    &slave_qhs_prng
  },
};
static icb_route_list_type route_sys_client_0_qhs_prng_list =
{
  5,
  route_sys_client_0_qhs_prng_list_array
};
static icb_pair_type route_sys_client_0_qhs_tcsr_list_array[5] =
{
  {
    &master_sys_client_0,
    &slave_qxs_sys_0
  },
  {
    &master_qxm_vapss_0,
    &slave_qns_sys
  },
  {
    &master_qnm_cdsp,
    &slave_qns_memnoc_snoc
  },
  {
    &master_qnm_memnoc,
    &slave_qns_cnoc
  },
  {
    &master_qnm_snoc,
    &slave_qhs_tcsr
  },
};
static icb_route_list_type route_sys_client_0_qhs_tcsr_list =
{
  5,
  route_sys_client_0_qhs_tcsr_list_array
};
static icb_pair_type route_sys_client_0_qhs_tlmm_north_list_array[5] =
{
  {
    &master_sys_client_0,
    &slave_qxs_sys_0
  },
  {
    &master_qxm_vapss_0,
    &slave_qns_sys
  },
  {
    &master_qnm_cdsp,
    &slave_qns_memnoc_snoc
  },
  {
    &master_qnm_memnoc,
    &slave_qns_cnoc
  },
  {
    &master_qnm_snoc,
    &slave_qhs_tlmm_north
  },
};
static icb_route_list_type route_sys_client_0_qhs_tlmm_north_list =
{
  5,
  route_sys_client_0_qhs_tlmm_north_list_array
};
static icb_pair_type route_sys_client_0_qhs_tlmm_south_list_array[5] =
{
  {
    &master_sys_client_0,
    &slave_qxs_sys_0
  },
  {
    &master_qxm_vapss_0,
    &slave_qns_sys
  },
  {
    &master_qnm_cdsp,
    &slave_qns_memnoc_snoc
  },
  {
    &master_qnm_memnoc,
    &slave_qns_cnoc
  },
  {
    &master_qnm_snoc,
    &slave_qhs_tlmm_south
  },
};
static icb_route_list_type route_sys_client_0_qhs_tlmm_south_list =
{
  5,
  route_sys_client_0_qhs_tlmm_south_list_array
};
static icb_pair_type route_sys_client_0_qns_apps_io_list_array[3] =
{
  {
    &master_sys_client_0,
    &slave_qxs_sys_0
  },
  {
    &master_qxm_vapss_0,
    &slave_qns_sys
  },
  {
    &master_qnm_cdsp,
    &slave_qns_apps_io
  },
};
static icb_route_list_type route_sys_client_0_qns_apps_io_list =
{
  3,
  route_sys_client_0_qns_apps_io_list_array
};
static icb_pair_type route_sys_client_0_qns_llcc_list_array[3] =
{
  {
    &master_sys_client_0,
    &slave_qxs_sys_0
  },
  {
    &master_qxm_vapss_0,
    &slave_qns_sys
  },
  {
    &master_qnm_cdsp,
    &slave_qns_llcc
  },
};
static icb_route_list_type route_sys_client_0_qns_llcc_list =
{
  3,
  route_sys_client_0_qns_llcc_list_array
};
static icb_pair_type route_sys_client_0_qxs_imem_list_array[4] =
{
  {
    &master_sys_client_0,
    &slave_qxs_sys_0
  },
  {
    &master_qxm_vapss_0,
    &slave_qns_sys
  },
  {
    &master_qnm_cdsp,
    &slave_qns_memnoc_snoc
  },
  {
    &master_qnm_memnoc,
    &slave_qxs_imem
  },
};
static icb_route_list_type route_sys_client_0_qxs_imem_list =
{
  4,
  route_sys_client_0_qxs_imem_list_array
};
static icb_pair_type route_sys_client_0_srvc_memnoc_list_array[7] =
{
  {
    &master_sys_client_0,
    &slave_qxs_sys_0
  },
  {
    &master_qxm_vapss_0,
    &slave_qns_sys
  },
  {
    &master_qnm_cdsp,
    &slave_qns_memnoc_snoc
  },
  {
    &master_qnm_memnoc,
    &slave_qns_cnoc
  },
  {
    &master_qnm_snoc,
    &slave_qhs_dcc_cfg
  },
  {
    &master_qhm_cnoc,
    &slave_qhs_memnoc
  },
  {
    &master_qhm_memnoc_cfg,
    &slave_srvc_memnoc
  },
};
static icb_route_list_type route_sys_client_0_srvc_memnoc_list =
{
  7,
  route_sys_client_0_srvc_memnoc_list_array
};
static icb_pair_type route_sys_client_0_xs_qdss_stm_list_array[4] =
{
  {
    &master_sys_client_0,
    &slave_qxs_sys_0
  },
  {
    &master_qxm_vapss_0,
    &slave_qns_sys
  },
  {
    &master_qnm_cdsp,
    &slave_qns_memnoc_snoc
  },
  {
    &master_qnm_memnoc,
    &slave_xs_qdss_stm
  },
};
static icb_route_list_type route_sys_client_0_xs_qdss_stm_list =
{
  4,
  route_sys_client_0_xs_qdss_stm_list_array
};
static icb_pair_type route_sys_client_1_ebi_list_array[4] =
{
  {
    &master_sys_client_1,
    &slave_qxs_sys_1
  },
  {
    &master_qxm_vapss_1,
    &slave_qns_sys
  },
  {
    &master_qnm_cdsp,
    &slave_qns_llcc
  },
  {
    &master_llcc_mc,
    &slave_ebi
  },
};
static icb_route_list_type route_sys_client_1_ebi_list =
{
  4,
  route_sys_client_1_ebi_list_array
};
static icb_pair_type route_sys_client_1_qhs_aop_list_array[5] =
{
  {
    &master_sys_client_1,
    &slave_qxs_sys_1
  },
  {
    &master_qxm_vapss_1,
    &slave_qns_sys
  },
  {
    &master_qnm_cdsp,
    &slave_qns_memnoc_snoc
  },
  {
    &master_qnm_memnoc,
    &slave_qns_cnoc
  },
  {
    &master_qnm_snoc,
    &slave_qhs_aop
  },
};
static icb_route_list_type route_sys_client_1_qhs_aop_list =
{
  5,
  route_sys_client_1_qhs_aop_list_array
};
static icb_pair_type route_sys_client_1_qhs_aoss_list_array[5] =
{
  {
    &master_sys_client_1,
    &slave_qxs_sys_1
  },
  {
    &master_qxm_vapss_1,
    &slave_qns_sys
  },
  {
    &master_qnm_cdsp,
    &slave_qns_memnoc_snoc
  },
  {
    &master_qnm_memnoc,
    &slave_qns_cnoc
  },
  {
    &master_qnm_snoc,
    &slave_qhs_aoss
  },
};
static icb_route_list_type route_sys_client_1_qhs_aoss_list =
{
  5,
  route_sys_client_1_qhs_aoss_list_array
};
static icb_pair_type route_sys_client_1_qhs_clk_ctl_list_array[5] =
{
  {
    &master_sys_client_1,
    &slave_qxs_sys_1
  },
  {
    &master_qxm_vapss_1,
    &slave_qns_sys
  },
  {
    &master_qnm_cdsp,
    &slave_qns_memnoc_snoc
  },
  {
    &master_qnm_memnoc,
    &slave_qns_cnoc
  },
  {
    &master_qnm_snoc,
    &slave_qhs_clk_ctl
  },
};
static icb_route_list_type route_sys_client_1_qhs_clk_ctl_list =
{
  5,
  route_sys_client_1_qhs_clk_ctl_list_array
};
static icb_pair_type route_sys_client_1_qhs_llcc_list_array[6] =
{
  {
    &master_sys_client_1,
    &slave_qxs_sys_1
  },
  {
    &master_qxm_vapss_1,
    &slave_qns_sys
  },
  {
    &master_qnm_cdsp,
    &slave_qns_memnoc_snoc
  },
  {
    &master_qnm_memnoc,
    &slave_qns_cnoc
  },
  {
    &master_qnm_snoc,
    &slave_qhs_dcc_cfg
  },
  {
    &master_qhm_cnoc,
    &slave_qhs_llcc
  },
};
static icb_route_list_type route_sys_client_1_qhs_llcc_list =
{
  6,
  route_sys_client_1_qhs_llcc_list_array
};
static icb_pair_type route_sys_client_1_qhs_mdsp_ms_mpu_cfg_list_array[7] =
{
  {
    &master_sys_client_1,
    &slave_qxs_sys_1
  },
  {
    &master_qxm_vapss_1,
    &slave_qns_sys
  },
  {
    &master_qnm_cdsp,
    &slave_qns_memnoc_snoc
  },
  {
    &master_qnm_memnoc,
    &slave_qns_cnoc
  },
  {
    &master_qnm_snoc,
    &slave_qhs_dcc_cfg
  },
  {
    &master_qhm_cnoc,
    &slave_qhs_memnoc
  },
  {
    &master_qhm_memnoc_cfg,
    &slave_qhs_mdsp_ms_mpu_cfg
  },
};
static icb_route_list_type route_sys_client_1_qhs_mdsp_ms_mpu_cfg_list =
{
  7,
  route_sys_client_1_qhs_mdsp_ms_mpu_cfg_list_array
};
static icb_pair_type route_sys_client_1_qhs_prng_list_array[5] =
{
  {
    &master_sys_client_1,
    &slave_qxs_sys_1
  },
  {
    &master_qxm_vapss_1,
    &slave_qns_sys
  },
  {
    &master_qnm_cdsp,
    &slave_qns_memnoc_snoc
  },
  {
    &master_qnm_memnoc,
    &slave_qns_cnoc
  },
  {
    &master_qnm_snoc,
    &slave_qhs_prng
  },
};
static icb_route_list_type route_sys_client_1_qhs_prng_list =
{
  5,
  route_sys_client_1_qhs_prng_list_array
};
static icb_pair_type route_sys_client_1_qhs_tcsr_list_array[5] =
{
  {
    &master_sys_client_1,
    &slave_qxs_sys_1
  },
  {
    &master_qxm_vapss_1,
    &slave_qns_sys
  },
  {
    &master_qnm_cdsp,
    &slave_qns_memnoc_snoc
  },
  {
    &master_qnm_memnoc,
    &slave_qns_cnoc
  },
  {
    &master_qnm_snoc,
    &slave_qhs_tcsr
  },
};
static icb_route_list_type route_sys_client_1_qhs_tcsr_list =
{
  5,
  route_sys_client_1_qhs_tcsr_list_array
};
static icb_pair_type route_sys_client_1_qhs_tlmm_north_list_array[5] =
{
  {
    &master_sys_client_1,
    &slave_qxs_sys_1
  },
  {
    &master_qxm_vapss_1,
    &slave_qns_sys
  },
  {
    &master_qnm_cdsp,
    &slave_qns_memnoc_snoc
  },
  {
    &master_qnm_memnoc,
    &slave_qns_cnoc
  },
  {
    &master_qnm_snoc,
    &slave_qhs_tlmm_north
  },
};
static icb_route_list_type route_sys_client_1_qhs_tlmm_north_list =
{
  5,
  route_sys_client_1_qhs_tlmm_north_list_array
};
static icb_pair_type route_sys_client_1_qhs_tlmm_south_list_array[5] =
{
  {
    &master_sys_client_1,
    &slave_qxs_sys_1
  },
  {
    &master_qxm_vapss_1,
    &slave_qns_sys
  },
  {
    &master_qnm_cdsp,
    &slave_qns_memnoc_snoc
  },
  {
    &master_qnm_memnoc,
    &slave_qns_cnoc
  },
  {
    &master_qnm_snoc,
    &slave_qhs_tlmm_south
  },
};
static icb_route_list_type route_sys_client_1_qhs_tlmm_south_list =
{
  5,
  route_sys_client_1_qhs_tlmm_south_list_array
};
static icb_pair_type route_sys_client_1_qns_apps_io_list_array[3] =
{
  {
    &master_sys_client_1,
    &slave_qxs_sys_1
  },
  {
    &master_qxm_vapss_1,
    &slave_qns_sys
  },
  {
    &master_qnm_cdsp,
    &slave_qns_apps_io
  },
};
static icb_route_list_type route_sys_client_1_qns_apps_io_list =
{
  3,
  route_sys_client_1_qns_apps_io_list_array
};
static icb_pair_type route_sys_client_1_qns_llcc_list_array[3] =
{
  {
    &master_sys_client_1,
    &slave_qxs_sys_1
  },
  {
    &master_qxm_vapss_1,
    &slave_qns_sys
  },
  {
    &master_qnm_cdsp,
    &slave_qns_llcc
  },
};
static icb_route_list_type route_sys_client_1_qns_llcc_list =
{
  3,
  route_sys_client_1_qns_llcc_list_array
};
static icb_pair_type route_sys_client_1_qxs_imem_list_array[4] =
{
  {
    &master_sys_client_1,
    &slave_qxs_sys_1
  },
  {
    &master_qxm_vapss_1,
    &slave_qns_sys
  },
  {
    &master_qnm_cdsp,
    &slave_qns_memnoc_snoc
  },
  {
    &master_qnm_memnoc,
    &slave_qxs_imem
  },
};
static icb_route_list_type route_sys_client_1_qxs_imem_list =
{
  4,
  route_sys_client_1_qxs_imem_list_array
};
static icb_pair_type route_sys_client_1_srvc_memnoc_list_array[7] =
{
  {
    &master_sys_client_1,
    &slave_qxs_sys_1
  },
  {
    &master_qxm_vapss_1,
    &slave_qns_sys
  },
  {
    &master_qnm_cdsp,
    &slave_qns_memnoc_snoc
  },
  {
    &master_qnm_memnoc,
    &slave_qns_cnoc
  },
  {
    &master_qnm_snoc,
    &slave_qhs_dcc_cfg
  },
  {
    &master_qhm_cnoc,
    &slave_qhs_memnoc
  },
  {
    &master_qhm_memnoc_cfg,
    &slave_srvc_memnoc
  },
};
static icb_route_list_type route_sys_client_1_srvc_memnoc_list =
{
  7,
  route_sys_client_1_srvc_memnoc_list_array
};
static icb_pair_type route_sys_client_1_xs_qdss_stm_list_array[4] =
{
  {
    &master_sys_client_1,
    &slave_qxs_sys_1
  },
  {
    &master_qxm_vapss_1,
    &slave_qns_sys
  },
  {
    &master_qnm_cdsp,
    &slave_qns_memnoc_snoc
  },
  {
    &master_qnm_memnoc,
    &slave_xs_qdss_stm
  },
};
static icb_route_list_type route_sys_client_1_xs_qdss_stm_list =
{
  4,
  route_sys_client_1_xs_qdss_stm_list_array
};

/*============================================================================
                         ROUTE TREE - 50 routes
============================================================================*/
/* Forward declarations */
static ul_treeNodeType route_0x99000000f9L_q6_client_0_qxs_q6_node;
static ul_treeNodeType route_0x9a00000000L_sys_client_0_ebi_node;
static ul_treeNodeType route_0x9a0000001aL_sys_client_0_qxs_imem_node;
static ul_treeNodeType route_0x9a0000001eL_sys_client_0_xs_qdss_stm_node;
static ul_treeNodeType route_0x9a0000002cL_sys_client_0_qhs_prng_node;
static ul_treeNodeType route_0x9a0000002fL_sys_client_0_qhs_clk_ctl_node;
static ul_treeNodeType route_0x9a00000032L_sys_client_0_qhs_tcsr_node;
static ul_treeNodeType route_0x9a000000c3L_sys_client_0_qhs_mdsp_ms_mpu_cfg_node;
static ul_treeNodeType route_0x9a000000d6L_sys_client_0_qhs_tlmm_north_node;
static ul_treeNodeType route_0x9a000000d8L_sys_client_0_qhs_tlmm_south_node;
static ul_treeNodeType route_0x9a000000daL_sys_client_0_qhs_aop_node;
static ul_treeNodeType route_0x9a000000dbL_sys_client_0_qhs_aoss_node;
static ul_treeNodeType route_0x9a000000e0L_sys_client_0_qhs_llcc_node;
static ul_treeNodeType route_0x9a000000efL_sys_client_0_qns_apps_io_node;
static ul_treeNodeType route_0x9a000000f3L_sys_client_0_qns_llcc_node;
static ul_treeNodeType route_0x9a00000102L_sys_client_0_srvc_memnoc_node;
static ul_treeNodeType route_0x9b000000f9L_q6_client_1_qxs_q6_node;
static ul_treeNodeType route_0x9c00000000L_sys_client_1_ebi_node;
static ul_treeNodeType route_0x9c0000001aL_sys_client_1_qxs_imem_node;
static ul_treeNodeType route_0x9c0000001eL_sys_client_1_xs_qdss_stm_node;
static ul_treeNodeType route_0x9c0000002cL_sys_client_1_qhs_prng_node;
static ul_treeNodeType route_0x9c0000002fL_sys_client_1_qhs_clk_ctl_node;
static ul_treeNodeType route_0x9c00000032L_sys_client_1_qhs_tcsr_node;
static ul_treeNodeType route_0x9c000000c3L_sys_client_1_qhs_mdsp_ms_mpu_cfg_node;
static ul_treeNodeType route_0x9c000000d6L_sys_client_1_qhs_tlmm_north_node;
static ul_treeNodeType route_0x9c000000d8L_sys_client_1_qhs_tlmm_south_node;
static ul_treeNodeType route_0x9c000000daL_sys_client_1_qhs_aop_node;
static ul_treeNodeType route_0x9c000000dbL_sys_client_1_qhs_aoss_node;
static ul_treeNodeType route_0x9c000000e0L_sys_client_1_qhs_llcc_node;
static ul_treeNodeType route_0x9c000000efL_sys_client_1_qns_apps_io_node;
static ul_treeNodeType route_0x9c000000f3L_sys_client_1_qns_llcc_node;
static ul_treeNodeType route_0x9c00000102L_sys_client_1_srvc_memnoc_node;
static ul_treeNodeType route_0x9e000000feL_qhm_cdsp_noc_cfg_srvc_cdsp_noc_node;
static ul_treeNodeType route_0xa0000000ffL_qhm_vapss_noc_cfg_srvc_vapss_noc_node;
static ul_treeNodeType route_0xad00000000L_qxm_q6_ebi_node;
static ul_treeNodeType route_0xad0000001aL_qxm_q6_qxs_imem_node;
static ul_treeNodeType route_0xad0000001eL_qxm_q6_xs_qdss_stm_node;
static ul_treeNodeType route_0xad0000002cL_qxm_q6_qhs_prng_node;
static ul_treeNodeType route_0xad0000002fL_qxm_q6_qhs_clk_ctl_node;
static ul_treeNodeType route_0xad00000032L_qxm_q6_qhs_tcsr_node;
static ul_treeNodeType route_0xad000000c3L_qxm_q6_qhs_mdsp_ms_mpu_cfg_node;
static ul_treeNodeType route_0xad000000d6L_qxm_q6_qhs_tlmm_north_node;
static ul_treeNodeType route_0xad000000d8L_qxm_q6_qhs_tlmm_south_node;
static ul_treeNodeType route_0xad000000daL_qxm_q6_qhs_aop_node;
static ul_treeNodeType route_0xad000000dbL_qxm_q6_qhs_aoss_node;
static ul_treeNodeType route_0xad000000e0L_qxm_q6_qhs_llcc_node;
static ul_treeNodeType route_0xad000000efL_qxm_q6_qns_apps_io_node;
static ul_treeNodeType route_0xad000000f3L_qxm_q6_qns_llcc_node;
static ul_treeNodeType route_0xad00000102L_qxm_q6_srvc_memnoc_node;
static ul_treeNodeType route_0xb400000000L_llcc_mc_ebi_node;

/* Create the tree */
static ul_treeNodeType route_0x99000000f9L_q6_client_0_qxs_q6_node =
{
  0x99000000f9ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_q6_client_0_qxs_q6_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x9a00000000L_sys_client_0_ebi_node =
{
  0x9a00000000ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_sys_client_0_ebi_list,
  &route_0x99000000f9L_q6_client_0_qxs_q6_node,
  &route_0x9a0000001aL_sys_client_0_qxs_imem_node
};
static ul_treeNodeType route_0x9a0000001aL_sys_client_0_qxs_imem_node =
{
  0x9a0000001aULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_sys_client_0_qxs_imem_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x9a0000001eL_sys_client_0_xs_qdss_stm_node =
{
  0x9a0000001eULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_sys_client_0_xs_qdss_stm_list,
  &route_0x9a00000000L_sys_client_0_ebi_node,
  &route_0x9a0000002fL_sys_client_0_qhs_clk_ctl_node
};
static ul_treeNodeType route_0x9a0000002cL_sys_client_0_qhs_prng_node =
{
  0x9a0000002cULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_sys_client_0_qhs_prng_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x9a0000002fL_sys_client_0_qhs_clk_ctl_node =
{
  0x9a0000002fULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_sys_client_0_qhs_clk_ctl_list,
  &route_0x9a0000002cL_sys_client_0_qhs_prng_node,
  &route_0x9a00000032L_sys_client_0_qhs_tcsr_node
};
static ul_treeNodeType route_0x9a00000032L_sys_client_0_qhs_tcsr_node =
{
  0x9a00000032ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_sys_client_0_qhs_tcsr_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x9a000000c3L_sys_client_0_qhs_mdsp_ms_mpu_cfg_node =
{
  0x9a000000c3ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_sys_client_0_qhs_mdsp_ms_mpu_cfg_list,
  &route_0x9a0000001eL_sys_client_0_xs_qdss_stm_node,
  &route_0x9a000000d8L_sys_client_0_qhs_tlmm_south_node
};
static ul_treeNodeType route_0x9a000000d6L_sys_client_0_qhs_tlmm_north_node =
{
  0x9a000000d6ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_sys_client_0_qhs_tlmm_north_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x9a000000d8L_sys_client_0_qhs_tlmm_south_node =
{
  0x9a000000d8ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_sys_client_0_qhs_tlmm_south_list,
  &route_0x9a000000d6L_sys_client_0_qhs_tlmm_north_node,
  &route_0x9a000000dbL_sys_client_0_qhs_aoss_node
};
static ul_treeNodeType route_0x9a000000daL_sys_client_0_qhs_aop_node =
{
  0x9a000000daULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_sys_client_0_qhs_aop_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x9a000000dbL_sys_client_0_qhs_aoss_node =
{
  0x9a000000dbULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_sys_client_0_qhs_aoss_list,
  &route_0x9a000000daL_sys_client_0_qhs_aop_node,
  &route_0x9a000000e0L_sys_client_0_qhs_llcc_node
};
static ul_treeNodeType route_0x9a000000e0L_sys_client_0_qhs_llcc_node =
{
  0x9a000000e0ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_sys_client_0_qhs_llcc_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x9a000000efL_sys_client_0_qns_apps_io_node =
{
  0x9a000000efULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_sys_client_0_qns_apps_io_list,
  &route_0x9a000000c3L_sys_client_0_qhs_mdsp_ms_mpu_cfg_node,
  &route_0x9c0000001eL_sys_client_1_xs_qdss_stm_node
};
static ul_treeNodeType route_0x9a000000f3L_sys_client_0_qns_llcc_node =
{
  0x9a000000f3ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_sys_client_0_qns_llcc_list,
  NULL,
  &route_0x9a00000102L_sys_client_0_srvc_memnoc_node
};
static ul_treeNodeType route_0x9a00000102L_sys_client_0_srvc_memnoc_node =
{
  0x9a00000102ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_sys_client_0_srvc_memnoc_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x9b000000f9L_q6_client_1_qxs_q6_node =
{
  0x9b000000f9ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_q6_client_1_qxs_q6_list,
  &route_0x9a000000f3L_sys_client_0_qns_llcc_node,
  &route_0x9c0000001aL_sys_client_1_qxs_imem_node
};
static ul_treeNodeType route_0x9c00000000L_sys_client_1_ebi_node =
{
  0x9c00000000ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_sys_client_1_ebi_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x9c0000001aL_sys_client_1_qxs_imem_node =
{
  0x9c0000001aULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_sys_client_1_qxs_imem_list,
  &route_0x9c00000000L_sys_client_1_ebi_node,
  NULL
};
static ul_treeNodeType route_0x9c0000001eL_sys_client_1_xs_qdss_stm_node =
{
  0x9c0000001eULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_sys_client_1_xs_qdss_stm_list,
  &route_0x9b000000f9L_q6_client_1_qxs_q6_node,
  &route_0x9c000000c3L_sys_client_1_qhs_mdsp_ms_mpu_cfg_node
};
static ul_treeNodeType route_0x9c0000002cL_sys_client_1_qhs_prng_node =
{
  0x9c0000002cULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_sys_client_1_qhs_prng_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x9c0000002fL_sys_client_1_qhs_clk_ctl_node =
{
  0x9c0000002fULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_sys_client_1_qhs_clk_ctl_list,
  &route_0x9c0000002cL_sys_client_1_qhs_prng_node,
  &route_0x9c00000032L_sys_client_1_qhs_tcsr_node
};
static ul_treeNodeType route_0x9c00000032L_sys_client_1_qhs_tcsr_node =
{
  0x9c00000032ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_sys_client_1_qhs_tcsr_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x9c000000c3L_sys_client_1_qhs_mdsp_ms_mpu_cfg_node =
{
  0x9c000000c3ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_sys_client_1_qhs_mdsp_ms_mpu_cfg_list,
  &route_0x9c0000002fL_sys_client_1_qhs_clk_ctl_node,
  &route_0x9c000000d8L_sys_client_1_qhs_tlmm_south_node
};
static ul_treeNodeType route_0x9c000000d6L_sys_client_1_qhs_tlmm_north_node =
{
  0x9c000000d6ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_sys_client_1_qhs_tlmm_north_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x9c000000d8L_sys_client_1_qhs_tlmm_south_node =
{
  0x9c000000d8ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_sys_client_1_qhs_tlmm_south_list,
  &route_0x9c000000d6L_sys_client_1_qhs_tlmm_north_node,
  &route_0x9c000000dbL_sys_client_1_qhs_aoss_node
};
static ul_treeNodeType route_0x9c000000daL_sys_client_1_qhs_aop_node =
{
  0x9c000000daULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_sys_client_1_qhs_aop_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x9c000000dbL_sys_client_1_qhs_aoss_node =
{
  0x9c000000dbULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_sys_client_1_qhs_aoss_list,
  &route_0x9c000000daL_sys_client_1_qhs_aop_node,
  &route_0x9c000000e0L_sys_client_1_qhs_llcc_node
};
static ul_treeNodeType route_0x9c000000e0L_sys_client_1_qhs_llcc_node =
{
  0x9c000000e0ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_sys_client_1_qhs_llcc_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x9c000000efL_sys_client_1_qns_apps_io_node =
{
  0x9c000000efULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_sys_client_1_qns_apps_io_list,
  &route_0x9a000000efL_sys_client_0_qns_apps_io_node,
  &route_0xad000000d8L_qxm_q6_qhs_tlmm_south_node
};
static ul_treeNodeType route_0x9c000000f3L_sys_client_1_qns_llcc_node =
{
  0x9c000000f3ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_sys_client_1_qns_llcc_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x9c00000102L_sys_client_1_srvc_memnoc_node =
{
  0x9c00000102ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_sys_client_1_srvc_memnoc_list,
  &route_0x9c000000f3L_sys_client_1_qns_llcc_node,
  &route_0x9e000000feL_qhm_cdsp_noc_cfg_srvc_cdsp_noc_node
};
static ul_treeNodeType route_0x9e000000feL_qhm_cdsp_noc_cfg_srvc_cdsp_noc_node =
{
  0x9e000000feULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_qhm_cdsp_noc_cfg_srvc_cdsp_noc_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0xa0000000ffL_qhm_vapss_noc_cfg_srvc_vapss_noc_node =
{
  0xa0000000ffULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_qhm_vapss_noc_cfg_srvc_vapss_noc_list,
  &route_0x9c00000102L_sys_client_1_srvc_memnoc_node,
  &route_0xad0000001aL_qxm_q6_qxs_imem_node
};
static ul_treeNodeType route_0xad00000000L_qxm_q6_ebi_node =
{
  0xad00000000ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_qxm_q6_ebi_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0xad0000001aL_qxm_q6_qxs_imem_node =
{
  0xad0000001aULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_qxm_q6_qxs_imem_list,
  &route_0xad00000000L_qxm_q6_ebi_node,
  &route_0xad0000001eL_qxm_q6_xs_qdss_stm_node
};
static ul_treeNodeType route_0xad0000001eL_qxm_q6_xs_qdss_stm_node =
{
  0xad0000001eULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_qxm_q6_xs_qdss_stm_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0xad0000002cL_qxm_q6_qhs_prng_node =
{
  0xad0000002cULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_qxm_q6_qhs_prng_list,
  &route_0xa0000000ffL_qhm_vapss_noc_cfg_srvc_vapss_noc_node,
  &route_0xad00000032L_qxm_q6_qhs_tcsr_node
};
static ul_treeNodeType route_0xad0000002fL_qxm_q6_qhs_clk_ctl_node =
{
  0xad0000002fULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_qxm_q6_qhs_clk_ctl_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0xad00000032L_qxm_q6_qhs_tcsr_node =
{
  0xad00000032ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_qxm_q6_qhs_tcsr_list,
  &route_0xad0000002fL_qxm_q6_qhs_clk_ctl_node,
  &route_0xad000000d6L_qxm_q6_qhs_tlmm_north_node
};
static ul_treeNodeType route_0xad000000c3L_qxm_q6_qhs_mdsp_ms_mpu_cfg_node =
{
  0xad000000c3ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_qxm_q6_qhs_mdsp_ms_mpu_cfg_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0xad000000d6L_qxm_q6_qhs_tlmm_north_node =
{
  0xad000000d6ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_qxm_q6_qhs_tlmm_north_list,
  &route_0xad000000c3L_qxm_q6_qhs_mdsp_ms_mpu_cfg_node,
  NULL
};
static ul_treeNodeType route_0xad000000d8L_qxm_q6_qhs_tlmm_south_node =
{
  0xad000000d8ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_qxm_q6_qhs_tlmm_south_list,
  &route_0xad0000002cL_qxm_q6_qhs_prng_node,
  &route_0xad000000efL_qxm_q6_qns_apps_io_node
};
static ul_treeNodeType route_0xad000000daL_qxm_q6_qhs_aop_node =
{
  0xad000000daULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_qxm_q6_qhs_aop_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0xad000000dbL_qxm_q6_qhs_aoss_node =
{
  0xad000000dbULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_qxm_q6_qhs_aoss_list,
  &route_0xad000000daL_qxm_q6_qhs_aop_node,
  &route_0xad000000e0L_qxm_q6_qhs_llcc_node
};
static ul_treeNodeType route_0xad000000e0L_qxm_q6_qhs_llcc_node =
{
  0xad000000e0ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_qxm_q6_qhs_llcc_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0xad000000efL_qxm_q6_qns_apps_io_node =
{
  0xad000000efULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_qxm_q6_qns_apps_io_list,
  &route_0xad000000dbL_qxm_q6_qhs_aoss_node,
  &route_0xad00000102L_qxm_q6_srvc_memnoc_node
};
static ul_treeNodeType route_0xad000000f3L_qxm_q6_qns_llcc_node =
{
  0xad000000f3ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_qxm_q6_qns_llcc_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0xad00000102L_qxm_q6_srvc_memnoc_node =
{
  0xad00000102ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_qxm_q6_srvc_memnoc_list,
  &route_0xad000000f3L_qxm_q6_qns_llcc_node,
  &route_0xb400000000L_llcc_mc_ebi_node
};
static ul_treeNodeType route_0xb400000000L_llcc_mc_ebi_node =
{
  0xb400000000ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_llcc_mc_ebi_list,
  NULL,
  NULL
};

/****************************************************************************/
/*                              LISTS                                       */
/****************************************************************************/
/* List of buses */
static icb_bus_def_type *bus_list[] = 
{
  &bus_cdsp_noc,
  &bus_config_noc,
  &bus_dc_noc,
  &bus_mc_virt,
  &bus_mem_noc,
  &bus_system_noc,
  &bus_vapss_noc,
};

/* List of masters */
static icb_master_def_type *master_list[] = 
{
  &master_llcc_mc,
  &master_q6_client_0,
  &master_q6_client_1,
  &master_qhm_cdsp_noc_cfg,
  &master_qhm_cnoc,
  &master_qhm_memnoc_cfg,
  &master_qhm_vapss_noc_cfg,
  &master_qnm_cdsp,
  &master_qnm_memnoc,
  &master_qnm_snoc,
  &master_qxm_q6,
  &master_qxm_vapss_0,
  &master_qxm_vapss_1,
  &master_sys_client_0,
  &master_sys_client_1,
};

/* List of slaves */
static icb_slave_def_type *slave_list[] = 
{
  &slave_ebi,
  &slave_qhs_aop,
  &slave_qhs_aoss,
  &slave_qhs_clk_ctl,
  &slave_qhs_dcc_cfg,
  &slave_qhs_llcc,
  &slave_qhs_mdsp_ms_mpu_cfg,
  &slave_qhs_memnoc,
  &slave_qhs_prng,
  &slave_qhs_tcsr,
  &slave_qhs_tlmm_north,
  &slave_qhs_tlmm_south,
  &slave_qns_apps_io,
  &slave_qns_cnoc,
  &slave_qns_llcc,
  &slave_qns_memnoc_snoc,
  &slave_qns_sys,
  &slave_qxs_imem,
  &slave_qxs_q6,
  &slave_qxs_sys_0,
  &slave_qxs_sys_1,
  &slave_srvc_cdsp_noc,
  &slave_srvc_memnoc,
  &slave_srvc_vapss_noc,
  &slave_xs_qdss_stm,
};

/* List of hardware nodes */
static icb_hw_node_type *hw_node_list[] =
{
  &hw_node_acv,
  &hw_node_alc,
  &hw_node_mc0,
  &hw_node_sh0,
  &hw_node_cn0,
  &hw_node_sh1,
  &hw_node_sh2,
  &hw_node_sh4,
  &hw_node_sn1,
  &hw_node_sn3,
  &hw_node_sn5,
  &hw_node_sn15,
};

/*============================================================================
                               TOPOLOGY DEFINITIONS
============================================================================*/
static icb_topology_type topology =
{
  { RSC_DRV_COMPUTE_DSP, NULL }, /**< RPMh handle definition */
  &route_0x9c000000efL_sys_client_1_qns_apps_io_node,
  ICB_ARRAY(bus_list),
  ICB_ARRAY(master_list),
  ICB_ARRAY(slave_list),
  ICB_ARRAY(hw_node_list)
};

static icb_topology_type *topology_list[] =
{
  &topology,
};

/*============================================================================
                          ARBITER NODE DEFINITION
============================================================================*/
static npa_resource_definition icb_node_resources[] = 
{
  { /* compute_dsp RSC */
    "/icb/arbiter", 
    "Arbitration Request",
    NPA_MAX_STATE,  /* Max "value" of state vector -- max len for now */
    NULL, /* Resource plugin to be filled in at run time */
    ( NPA_RESOURCE_DRIVER_UNCONDITIONAL | NPA_RESOURCE_ALLOW_CLIENT_TYPE_CHANGE |
      NPA_RESOURCE_REMOTE_ACCESS_ALLOWED ),
    (npa_user_data)&topology,
    NULL,
    NULL,
  },
};

static npa_node_definition icb_node_defn = 
{ 
  "/icb/arbiter", 
  NULL,  /* Driver function to be filled in at run time. */
  NPA_NODE_DEFAULT,
  NULL,
  NPA_EMPTY_ARRAY,
  NPA_ARRAY( icb_node_resources )
};

/*============================================================================
                     ARBITER STANDALONE NODE DEFINITIONS
============================================================================*/
/**** Node: alc ****/
static icb_standalone_data_type icb_standalone_node_alc_data =
{
  ICB_STANDALONE_INTERFACE_FAL,
  { RSC_DRV_COMPUTE_DSP, NULL }, /**< RPMh handle definition */
  &hw_node_alc
};

static npa_resource_definition icb_standalone_node_alc_resources[] = 
{
  { 
    "/icb/alc", 
    "KHz",
    NPA_MAX_STATE,
    NULL,  /* Plugin to be filled in at run time. */
    NPA_RESOURCE_REMOTE_ACCESS_ALLOWED,
    (npa_user_data)&icb_standalone_node_alc_data,
    NULL,
    NULL,
  },
};

static icb_standalone_node_type icb_standalone_node_alc =
{
  { 
    "/node/icb/alc", 
    NULL,  /* Driver function to be filled in at run time. */
    NPA_NODE_DEFAULT,
    NULL,
    NPA_EMPTY_ARRAY,
    NPA_ARRAY( icb_standalone_node_alc_resources )
  },
};

static icb_standalone_node_type *icb_standalone_nodes[] =
{
  &icb_standalone_node_alc,
};

/*============================================================================
                   EXTERNAL DATA DECLARATIONS
============================================================================*/
icb_info_type icb_info =
{
  &icb_node_defn, 
  ICB_ARRAY(topology_list),
  ICB_ARRAY(icb_standalone_nodes),
  {
    "+RPMH_BCM_BCM_STATUS",
    0,
    0x1F00,
    0,
  },
};

