#pragma once
// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"
#include "IAppLegacyTest.h"

// Copyright (c) 2017 Qualcomm Technologies, Inc.  All Rights Reserved.

// Qualcomm Technologies Proprietary and Confidential.

/**
 * IAppLegacyTest is an interface that an app can implement to expose the legacy
 * tz_app_cmd_handler interface via SMC Invoke objects
 */

#define IAppLegacyTest_DEFINE_INVOKE(func, prefix, type) \
  int32_t func(ObjectCxt h, ObjectOp op, ObjectArg *a, ObjectCounts k) \
  { \
    type me = (type) h; \
    switch (ObjectOp_methodID(op)) { \
      case Object_OP_release: { \
        return prefix##release(me); \
      } \
      case Object_OP_retain: { \
        return prefix##retain(me); \
      } \
      case IAppLegacyTest_OP_handleRequest: { \
        if (k != ObjectCounts_pack(1, 1, 0, 0)) { \
          break; \
        } \
        const void *request_ptr = (const void*) a[0].b.ptr; \
        size_t request_len = a[0].b.size / 1; \
        void *response_ptr = (void*) a[1].b.ptr; \
        size_t response_len = a[1].b.size / 1; \
        int32_t r = prefix##handleRequest(me, request_ptr, request_len, response_ptr, response_len, &response_len); \
        a[1].b.size = response_len * 1; \
        return r; \
      } \
    } \
    return Object_ERROR_INVALID; \
  }


