// Copyright (c) 2017 Qualcomm Technologies, Inc.  All Rights Reserved.
// Qualcomm Technologies Proprietary and Confidential.

/**
 * IAppLegacyTest is an interface that an app can implement to expose the legacy
 * tz_app_cmd_handler interface via SMC Invoke objects
 */
interface IAppLegacyTest {

  /**
   * @brief The object implementing this interface is supposed to redirect the
   * request to the tz_app_cmd_handler in its own application.
   */
  method handleRequest(in buffer request, out buffer response);
};
