// Copyright (c) 2018 - 2020 Qualcomm Technologies, Inc.  All Rights Reserved.
// Qualcomm Technologies Proprietary and Confidential.

/**
* @addtogroup CAccessControl
* @{
  Class CAccessControl implements \link IAccessControl \endlink interface.
		
  The class ID `AccessControl` is not included in the default privilege set. It needs to be added to the 
  privileges section in the metadata to allow the TA to use the CAccessControl class.
*/

const uint32 CAccessControl_UID = 138;

/** @} */
