// Copyright (c) 2017 Qualcomm Technologies, Inc.  All Rights Reserved.
// Qualcomm Technologies Proprietary and Confidential.

// This class provides an interface to load Secure Applications in QSEE
//

const uint32 CAppLoader_UID = 3;
