// Copyright (c) 2016 Qualcomm Technologies, Inc.  All Rights Reserved.
// Qualcomm Technologies Proprietary and Confidential.

// This class implements the `IProperty` interface.

const uint32 CCelerityProperty_UID = 75;
