// Copyright (c) 2015 Qualcomm Technologies, Inc.  All Rights Reserved.
// Qualcomm Technologies Proprietary and Confidential.

// This class determines if the provided certificate is valid or not using a set of custom checks
// `IValidate` interface.
//

const uint32 CCertValidate_UID = 50;
