// Copyright (c) 2015 Qualcomm Technologies, Inc.  All Rights Reserved.
// Qualcomm Technologies Proprietary and Confidential.

const uint32 CCipherAES128_UID = 35;
const uint32 CCipherAES256_UID = 36;
const uint32 CCipherTripleDES_UID = 37;
