// Copyright (c) 2018 Qualcomm Technologies, Inc.  All Rights Reserved.
// Qualcomm Technologies Proprietary and Confidential.

// This UID grants access to AC_VM_CP_CDSP.

const uint32 CComputeDSPSecureMemAccess_UID = 83;
