// Copyright (c) 2015 Qualcomm Technologies, Inc.  All Rights Reserved.
// Qualcomm Technologies Proprietary and Confidential.

// This class implements the ICrypo interface.

const uint32 CCrypto_UID = 11;
