// Copyright (c) 2019 Qualcomm Technologies, Inc.  All Rights Reserved.
// Qualcomm Technologies Proprietary and Confidential.

// This class implements the IDiagnostics interface.

const uint32 CDiagnostics_UID = 143;
