// Copyright (c) 2018 Qualcomm Technologies, Inc.  All Rights Reserved.
// Qualcomm Technologies Proprietary and Confidential.

// This UID may be used to obtain an IMemRegion object representing shared
// memory between TZ and the DSP.

const uint32 CDSPSharedChannel_UID = 84;
