// Copyright (c) 2015 Qualcomm Technologies, Inc.  All Rights Reserved.
// Qualcomm Technologies Proprietary and Confidential.

// This class implements the IESEService interface.

const uint32 CESEService_UID = 255;
