// Copyright (c) 2015-2017 Qualcomm Technologies, Inc.  All Rights Reserved.
// Qualcomm Technologies Proprietary and Confidential.

const uint32 CHashNone_UID = 38;
const uint32 CHashSHA1_UID = 39;
const uint32 CHashSHA256_UID = 40;
const uint32 CHashSHA384_UID = 46;
