// Copyright (c) 2018 Qualcomm Technologies, Inc.  All Rights Reserved.
// Qualcomm Technologies Proprietary and Confidential.

/**
 * This class can be implemented by a TA to Generate Keys.
 * This class implements `IKeyGen`.
 */
const uint32 CKeyGen_UID = 1027;
