// Copyright (c) 2019 Qualcomm Technologies, Inc.  All Rights Reserved.
// Qualcomm Technologies Proprietary and Confidential.

// This class implements the `ILicenseManager` interface.

const uint32 CLicenseManager_UID = 80;
