// Copyright (c) 2015 Qualcomm Technologies, Inc.  All Rights Reserved.
// Qualcomm Technologies Proprietary and Confidential.

// This class provides the configuration blob for the fidocrypto application.
// It implements the `ISource` interface.
//

const uint32 COEMFidoConfig_UID = 1025;
