// Copyright (c) 2017 Qualcomm Technologies, Inc.  All Rights Reserved.
// Qualcomm Technologies Proprietary and Confidential.

include "IAppController.idl"

interface IAppLoader {

  /**
   * Error codes
   */
  error ERROR_INVALID_BUFFER;          /**< Buffer is invalid */
  error ERROR_PIL_ROLLBACK_FAILURE;    /**< TA loading failed due to rollback protection */
  error ERROR_ELF_SIGNATURE_ERROR;     /**< Error in ELF or signature validation */
  error ERROR_METADATA_INVALID;        /**< Invalid metadata */
  error ERROR_MAX_NUM_APPS;            /**< Max number of supported apps reached */
  error ERROR_NO_NAME_IN_METADATA;     /**< Missing name in app metadata */
  error ERROR_ALREADY_LOADED;          /**< Already loaded by another client */

  /**
   * @brief Load a secure application .
   * The application ELF binary is passed as a buffer.
   *
   * @param[in]  appElf         Buffer containing the ELF image.
   * @param[out] appController  IAppController to access the secure application.
   *
   * @return  Object_OK if successful.
   */
  method loadFromBuffer(in buffer appElf,
                        out IAppController appController);

  /**
   * @brief Load a secure application .
   * The application ELF binary is passed as an IMemRegion object.
   *
   * @param[in]  appElf         Region containing the ELF image.
   * @param[out] appController  IAppController to access the secure application.
   *
   * @return  Object_OK if successful.
   */
  method loadFromRegion(in interface appElf,
                        out IAppController appController);

};
