// Copyright (c) 2016-2017 Qualcomm Technologies, Inc.  All Rights Reserved.
// Qualcomm Technologies Proprietary and Confidential.

/**
 * Interface used by HLOS clients to obtain objects from QSEE via
 * SMC Invoke.
 */
interface IClientEnv {

  /**
   * @brief Obtain an object from the Client Environment.
   */
  method open (in uint32 classid,
               out interface obj);

  /**
   * @brief Register a client with the specified credentials.
   */
  method register (in buffer credential,
                   out interface iclientenv_obj);

};

