// Copyright (c) 2015 Qualcomm Technologies, Inc.  All Rights Reserved.
// Qualcomm Technologies Proprietary and Confidential.

interface ICredentials {

  /** No property was found with the requested index or name */
  error ERROR_NOT_FOUND;

  /** The buffer provided to receive the name was too small */
  error ERROR_NAME_SIZE;

  /** The buffer provided to receive the value was too small */
  error ERROR_VALUE_SIZE;

  /**
   * Get the name of a property, given its position in the sequence of
   * properties.
   *
   * Errors:
   *    Object_ERROR_SIZE_OUT : the supplid buffer was not large enough to
   *                            contain the name.
   *    ICredentials_ERROR_INDEX_OUT_OF_RANGE : there are no properties at
   *        that index.
   */
  method getPropertyByIndex(
                            /** A (zero-based) index into the set of properties */
                            in uint32 index,

                            /** Property name, including a terminating zero byte. */
                            out buffer name,

                            /** Property value, including a terminating zero byte. */
                            out buffer value);

  /**
   * Return a property value, given a name.
   *
   * Note that `name` and `value` typed as buffers, not strings.  The `name`
   * buffer does not contain any null terminating character.  For example,
   * `strlen(szname)` should be passed as the `size` of the buffer if
   * `szname` is a zero-terminated string.
   *
   * On the other hand, the `value` buffer *will* be populated with a
   * terminating null byte, and the resulting length (*lenout) will be set
   * to the size including the terminating null.
   */
  method getValueByName(in buffer name,
                        out buffer value);
};
