// Copyright (c) 2015 Qualcomm Technologies, Inc.  All Rights Reserved.
// Qualcomm Technologies Proprietary and Confidential.

/**
 * @file IElfFile.idl
 *
 * IElfFile describes the first object executed in an ELF file after it is
 * loaded and its containing process is initialized.
 *
 * The entry point of the ELF file serves as the `invoke` function for the
 * object implementing this interface, and NULL is passed as the object's
 * `context` value.
 */

include "IModule.idl"
include "IEnv.idl"
include "IMemSpace.idl"

interface IElfFile {

  /**
   * @brief   Initialize a process constructed around an ELF file.
   *
   */
  method init(
              /** The environment for the application to use. */
              in IEnv env,
              
              /**KSpace Object created for the application*/
              in IMemSpace space,

              /** The module provided by the application to the system. This
                  will be used to obtain further functionality from the module. */
              out IModule module);
};
