/** @file  IGuestVM.idl */

// Copyright (c) 2015, 2017 Qualcomm Technologies, Inc.  All Rights Reserved.
// Qualcomm Technologies Proprietary and Confidential.



interface IGuestVM {
/**
 * @addtogroup interrupts
 * @{
 */
  /** Handles a message provided by the REE.
      
      @param[in]  req  Request buffer from the REE.
      @param[out] resp Response buffer for the REE.
      
      @return
      Object_OK if successful.
   */
  method handleCommand(in buffer req, out buffer resp);

  /** Receives notification of one or more requested event(s).
    
      @param[in] registeredMask Bit mask identifying one or more executed interrupt(s). 
      
      @return
      Object_OK if successful.
   */
  method handleInterrupt(in uint32 registeredMask);
/** @} */ /* end_addtogroup interrupts */
};
