// Copyright (c) 2017 Qualcomm Technologies, Inc.  All Rights Reserved.
// Qualcomm Technologies Proprietary and Confidential.

/**
 * @brief
 * Interface to update Output Protection Service with the revoked receiver IDs
 * list retrieved from a signed SRM file
 */
 
interface IHdcpSrm {
  /**
   * Update receiver Ids parsed from HDCP System Renewability Message
   * @param [in] version - SRM version number
   * @param [in] receiverIdList - Receiver IDs to be revoked
   */
   method updateRevokedIds(in uint16 version, in uint8[] receiverIdList);
};

