// Copyright (c) 2016 Qualcomm Technologies, Inc.  All Rights Reserved.
// Qualcomm Technologies Proprietary and Confidential.

/**
 * @brief
 * Hdcp Encryption interface controls hardware blocks that implement HDCP
 * ecnryption (HDMI, DP, ...) and keeps track of the minimum encryption level
 * given by the DRM policy.
 *
 */
  
interface IHdcpEncryption
{
   /**
   * Corresponds to enum qsee_hdcp_version_t
   * These constants define the HDCP version
   */
   const uint32 HDCP_VERSION_14 = 0x2001;
   const uint32 HDCP_VERSION_22 = 0x2002;

   /**
   * Corresponds to enum qsee_hdcp_device_t
   * These constants define the device types.
   */
   const uint32 HDCP_TXMTR_HDMI = 0x8001;
   const uint32 HDCP_TXMTR_DP   = 0x8002;

   /**
   * Error Codes
   */
   error ERROR_GENERIC;
   error ERROR_HW_NOT_SUPPORTED;
   error ERROR_HW_NOT_AVAILABLE;
   error ERROR_HW_CLOCK_OFF;
   error ERROR_BAD_PARAMETER;
   error ERROR_VERSION_NOT_SUPPORTED;
   
   /**
   * Enable HDCP encryption
   *
   * @param[in] hdcpVersion HDCP Version
   * @param[in] deviceType The HDCP device type
   * @param[in] key The key to write to HW for encryption
   * @param[in] randomIV Random IV to set to HW for encryption
   * @return Object_OK if successful.
   */
   method enable(in uint32 hdcpVersion, in uint32 deviceType, in buffer key, in buffer randomIV);
   
   /**
   * Disable HDCP encryption
   *
   * @param[in] hdcpVersion HDCP Version
   * @param[in] deviceType The HDCP device type
   * @return Object_OK if successful.
   */
   method disable(in uint32 hdcpVersion, in uint32 deviceType);
};

