//  Copyright (c) 2017 Qualcomm Technologies, Inc.  All Rights Reserved.
//  Qualcomm Technologies Proprietary and Confidential.
include "IMemRegion.idl"

interface IHlosRegionFinder
{

  /**
   * @brief
   *    API for secure applications to create a memory region for accessing HLOS memory.
   *
   * @param[in]   start Physical address of HLOS memory
   * @param[in]   size  Size of physical memory region
   * @param[out]  memRegionOut On success, HLOS Memory Region object
   *
   * @return Object_OK          Indicates success
   *         Object_ERROR       Indicates failure
   */
  method getRegion(in uint64 physAddr, in uint64 size, out IMemRegion memRegionOut);
};
