// Copyright (c) 2015-2017 Qualcomm Technologies, Inc.  All Rights Reserved.
// Qualcomm Technologies Proprietary and Confidential.



interface IHmac { 
/** @cond */
  const int32 PARAM_KEY  = 1;
  const int32 PARAM_INVALID = -1;

  const int32 SIZE_SHA1 = 20;
  const int32 SIZE_SHA256 = 32;
  const int32 SIZE_INVALID = -1;

  const int32 DIGEST_SIZE_SHA1 = 20;
  const int32 DIGEST_SIZE_SHA256 = 32; /** @endcond */

/**
 * @addtogroup crypto
 * @{
*/
/** Updates the hash MAC per @xhyperref{FIPS198,FIPS PUB 198-1} using the
    configured hash algorithm.

    @param[in] msg Pointer to the message to be authenticated.

    @return
    Object_OK if successful.
 */
  method update(in buffer msg);

/** Final operation for hash MAC per @xhyperref{FIPS198,FIPS PUB 198-1} using
    the specified hash algorithm.

    @param[out] digest     Pointer to the message digest (memory provided by
                           the caller).

    @return
    Object_OK if successful.
*/
  method final(out buffer digest);

/** Modify the parameters for a given HMAC operation.

    @param[in] paramID Parameter to modify.

    @param[in] param   Parameter value to set.

    @return
    Object_OK if successful.
 */
  method setParamAsData(in int32 paramID, in buffer param);
/** @} */ /* end_addtogroup crypto */
};
 

