// Copyright (c) 2015 Qualcomm Technologies, Inc.  All Rights Reserved.
// Qualcomm Technologies Proprietary and Confidential.

interface IHwFuse {

  /**
   * @brief      QFPROM read row
   * @param[in]  rowAddress          Row address in the QFPROM region from which the row data is read
   * @param[in]  addrType            Raw or corrected address
   * @param[out] rowData1            Values read
   * @param[out] rowData2            Values read
   * @param[out] qfpromApiStatus     QFPROM API status
   * @return                         Object_OK on success
   */
  method fuseRead(in uint32 rowAddress, in int32 addrType, out uint32 rowData1, out uint32 rowData2, out uint32 qfpromApiStatus);

  /**
   * @brief      QFPROM write row
   * @param[in]  rawRowAddress       Raw row address in the QFPROM region from which the row data is written
   * @param[in]  rowData1            Values to be written
   * @param[in]  rowData2            Values to be written
   * @param[out] qfpromApiStatus     QFPROM API status
   * @return                         Object_OK on success
   */

  method fuseWrite(in uint32 rawRowAddress, in uint32 rowData1, in uint32 rowData2, out uint32 qfpromApiStatus);

};
