// Copyright (c) 2018 Qualcomm Technologies, Inc.  All Rights Reserved.
// Qualcomm Technologies Proprietary and Confidential.

interface IKeyGen {

  /**
   * Supported key types.
   */
  const int32 AES256=0;

  /**
   * Key lengths in byte.
   */
  const uint32 AES256_LEN=32;

  /**
   * Generates a key.
   *
   * @param [in] keyType - Requested key type.
   * @param [out] key - Return a key.
   *
   * @return Object_OK on success; Object_ERROR on failure.
   */
  method generateKey(in int32 keyType, out buffer key);
};
