// Copyright (c) 2015 Qualcomm Technologies, Inc.  All Rights Reserved.
// Qualcomm Technologies Proprietary and Confidential.

interface IListener {
   /**
    * @param[in] listenerId
    * @param[in] request
    * @param[out] response
    * @return Object_OK on success
    */
   method requestService(in int32 listenerId, in buffer request, out buffer response);
};
