

interface IMemRegion {

  /*
   * The memory cannot be mapped as specified because the provided memory
   * region object did not confer the required memory access permissions.
   */
  error ERROR_PERM;

  /*
   * Permissions are designated by a field of bits.
   *
   * When a region is constructed, its PERM_R and PERM_W permissions dictate
   * how the memory can be used.
   *
   * PERM_X is only meaningful when mapping memory.  PERM_X allows execution
   * of instructions directly from the memory.  PERM_X can be applied to a
   * mapping only when the region confers the PERM_R permission.
   */
  const uint32 PERM_X    =  1;
  const uint32 PERM_W    =  2;
  const uint32 PERM_R    =  4;

  const uint32 PERM_RW   =  6;  /* PERM_R | PERM_W */
  const uint32 PERM_RX   =  5;  /* PERM_R | PERM_X */

  /**
   * Read bytes present at `offset` within the region.
   */
  method getData(in uint64 offset, out buffer data);

  /**
   * Write bytes at `offset` within the region.
   */
  method setData(in uint64 offset, in buffer data);

  /**
   * Create a regin that identifies the same memory as this region but
   * confers a subset of the permissions.
   */
  method createRestrictedRegion(in uint32 perms, out interface region);
};
