// Copyright (c) 2015 Qualcomm Technologies, Inc.  All Rights Reserved.
// Qualcomm Technologies Proprietary and Confidential.

// IModule.idl
//
// This interface is used to request objects from modules.

interface IModule {

   error ERROR_NOT_FOUND;

   // Request an instance object.
   //
   // On entry:
   //
   //    id = the ID of a class
   //    credentials = an object describing the credentials being used to request the object.
   //
   // On success:
   //
   //    obj = an instance of the requested class
   //
   method open(in uint32 id, in interface credentials, out interface obj);

   // Shutdown an instance object.
   //
   // On entry = None
   //
   // On success:
   //
   //   instance is prepared for deletion
   //
   method shutdown();
};
