// Copyright (c) 2017 Qualcomm Technologies, Inc.  All Rights Reserved.
// Qualcomm Technologies Proprietary and Confidential.

/**
 * @brief
 * INotifyHdcp Interface provides APIs to report HDCP authentication
 * level changes from OutputProtectionService to HDCP TX TAs
 *
 */
interface INotifyHdcp {

  /**
   * Error Codes
   */
   error HDCP_ERROR_AUTH_TIMEOUT;

  /**
   * Notify HDCP Auth level errors
   *
   * @param [in] hdcpError HDCP Error
   */
  method HdcpNotifyError(in int32 hdcpError);

};
