// Copyright (c) 2017 Qualcomm Technologies, Inc.  All Rights
// Reserved.  Qualcomm Technologies Proprietary and Confidential.

interface INSSystemReg {
  /** Returned when an unsupported System Register type is passed to
      GetNSSystemReg() */
  error ERROR_UNSUPPORTED_SYS_REG_TYPE;

  /**
   * Supported System Registers
   */
  const uint32 VBAR_EL1  = 0x0;

  /**
   * Retrieve NS System Register
   *
   * @param[in] SysReg This describes the System Register 
   *            that should be retrieved.
   * @param[out] val The value of the system register.
   *
   * @note This API will return the value of the System register requested.
   *
   * @return Object_OK on success
   */
  method GetNSSystemReg(in  uint32 SysReg,
                        out uint64 val);
};
