/** @file  IOpener.idl */

// Copyright (c) 2015, 2017 Qualcomm Technologies, Inc.  All Rights Reserved.
// Qualcomm Technologies Proprietary and Confidential.

/**
   @addtogroup core
   @{
*/
/** 0 is not a valid service ID. */
const uint32 IOpener_INVALID_ID = 0;
/** @} */ /* end_addtogroup core */

// This interface is used to request services from the system.
interface IOpener {

 /** @cond */
   /* The open() method returns this error code when it cannot find a service
      matching the ID.   */
   error ERROR_NOT_FOUND;

   /* The open() method returns this error code when the required privileges 
       are not present.  */
   error ERROR_PRIVILEGE;
/** @endcond */

/**
   @addtogroup core
   @{
*/
   /** Gets a service object from the system.
     
       @param[in]   id Identifies a class of service object.
       @param[in]  obj Instance of the requested service.

       @return
       - Object_OK if successful.
       - ERROR_NOT_FOUND if a service matching the ID cannot be found.
       - ERROR_PRIVILEGE if required privileges are not present.
   */
   method open(in uint32 id, out interface obj);
/** @} */ /* end_addtogroup core */

};
 
 
