// Copyright (c) 2017 Qualcomm Technologies, Inc.  All Rights Reserved.
// Qualcomm Technologies Proprietary and Confidential.

/**
 * @brief
 * IOPSSource Interface provides APIs to enforce output protection for
 * DRM protected content.
 *
 */
interface IOPSSource {

  /** error codes */

  /** SRM Version check failure */
  error ERROR_SRM_VERSION_CHECK_FAILED;

  /** Output/Sink does not meet the required OPL */
  error ERROR_INSUFFICIENT_HDCP;

  /**
   * Sets the content's encryption level as required by the license
   * DRM TAs should invoke this API to enforce the required HDCP level
   *
   * @param [in] opl - OPL to be enforced by Source/DRM
   * @param [in] srmVersion - HDCP System Renewability Message version
   * @param [out] cpl - content protection level = max( all source OPLs )
   * @param [out] dpl - display protection level = min( all sink OPLs )
   * @param [out] epl - final protection level enforced by OPS
   */
  method applyOPL(in uint8 opl, in uint16 srmVersion,
                  out uint8 cpl, out uint8 dpl, out uint8 epl);
};
