// Copyright (c) 2017 Qualcomm Technologies, Inc.  All Rights Reserved.
// Qualcomm Technologies Proprietary and Confidential.

include "IHdcpTransmitter.idl"
include "INotifyHdcp.idl"
/**
 * @brief
 * IOPSSink provides a interface to create HdcpTransmitter object
 *
 */
interface IOPSSink {

  /**
   * Creates a object implementing IHdcpTransmitter interface for a specific
   * device type
   *
   * @param [in] deviceId - Device type can be HDMI/DP/WFD listed in IOPS.idl
   * @param [in] notify - Object implementing INotifyHdcp interface which can be
   *                      invoked by OPS to notify HDCP errors
   * @param [out] hdcpTx - HDCP Transmitter object
   */
  method getHdcpTransmitter(in uint32 deviceId,
                            in INotifyHdcp notify,
                            out IHdcpTransmitter hdcpTx);
};
