// Copyright (c) 2016 Qualcomm Technologies, Inc.  All Rights Reserved.
// Qualcomm Technologies Proprietary and Confidential.

interface IProperty {

/* IProperty Error Codes */
  error INVALID_PARAMETERS;
  error UNKNOWN_NAME;
  error UNSUPPORTED;
  error CONFIG_ERROR;
  error MAP_ERROR;

/*
 * @brief Get the value of the named property.
 *
 * @param[in]   name     name of the property
 * @param[out]  dest     dest buffer to write the value into
 *
 * @return 0 on success, non-zero on failure
 */
  method getProperty(in buffer name, out buffer dest);

/*
 * @brief Set the value of the named property.
 *
 * @param[in]   name     name of the property
 * @param[out]  src      src buffer to read the value from
 *
 * @return 0 on success, non-zero on failure
 */
  method setProperty(in buffer name, in buffer src);
};

