// Copyright (c) 2015 Qualcomm Technologies, Inc.  All Rights Reserved.
// Qualcomm Technologies Proprietary and Confidential.

/**
 * @brief
 * A reset timer maintains a coutdown timer that, on expiration, triggers a
 * reset of the device.
 *
 * @details
 *
 * In the expected usage, a TA will set the reset timer to ensure that it is
 * invoked again by the REE within a certain amount of time.  At that point,
 * the TA may reset the expiration time or stop the timer.  If the REE fails
 * to invoke the TA, then it will fail to reset the timer before expiration
 * and TrustZone software will trigger a warm boot of the device.
 */

interface IResetTimer {

  /**
   * @brief
   * Set a new expiration time for the reset timer.
   *
   * @param[in] delayInSeconds - The number of seconds (from the current
   * time) at which the reset timer will fire.  Any value less than or equal
   * to 0 will reset the device immediately.
   */

  method setDelay(in int32 seconds);

  /**
   * @brief
   * Stop the reset timer.
   */
  method stop();
};
