/* Copyright (c) 2017 Qualcomm Technologies, Inc.  All Rights Reserved.
   Qualcomm Technologies Proprietary and Confidential. */

interface ISecureCameraClientEvent
{
    /**
     * @brief This will be called by TZ kernel when camera PHYs are protected
     * The implementation need to be present in TA which uses secure camera functionality.
     *
     * @param[in] state     reserved for future use
     * @return  Object_Ok if successful.
     */
    method phyProtectEvent(in uint32[] state);

    /**
     * @brief This will be called by TZ kernel when secure camera PHYs are unprotected.
     * The implementation need to be present in TA which uses secure camera functionality.
     *
     * @param[in] state     reserved for future use
     *
     * @return  Object_Ok if successful.
     */
     method phyUnprotectEvent(in uint32[] state);
};
