/** @file ISecureDisplay.idl  */
/* 
  Copyright (c) 2015-2018 Qualcomm Technologies, Inc.  All Rights Reserved.
  Qualcomm Technologies Proprietary and Confidential. */



interface ISecureDisplay {

/**
 * @addtogroup core
 * @{
 */
  /**  Controls whether the REE can stop the secure display using the
     Android sd_ctrl syscall.
    
     @param[in] isAllowed TRUE to allow REE to stop the secure display; FALSE
                          otherwise.

     @return
     Object_OK if successful. 
   */
  method setStopAllowed(in int32 isAllowed);

  /**  Gets the current secure display session ID.
    
     @param[out] sessionID ID of the current secure display session;
                           0 if no session is active.
     
     @return
     Object_OK if successful.
   */
  method getSession(out uint32 sessionID);

  /**
     Gets the Layer Mixer Register count for CRC calculation .

     @param[out] lm_count count of Layer Mixer registers used by display
                          0 to disable the frame authentication based on MISR

     @return
     Object_OK if successful.
   */
  method getLMRegCount(out uint32 lm_count);

  /**
     Reads the Layer Mixer MISR registers.

     @param[out] lm_misr Pointer to the output array for MISR vaues.
                         The size of the array should be atleast equal to
                         2*lm_count

     @return
     Object_OK if successful.
   */
  method readMISR(out uint32[] lm_misr);
/** @} */ /* end_addtogroup core */
};

