//  Copyright (c) 2015, 2017 Qualcomm Technologies, Inc.  All Rights Reserved.
//  Qualcomm Technologies Proprietary and Confidential.

interface ISharedBuffer
{

  /**
   * @brief
   *    API for secure applications to register the shared buffer with QSEE.
   *
   * @param[in] start Buffer reference, must match registered buffer.
   * @param[in] size Size of buffer
   *
   * @return Object_OK          Indicates success
   *         Object_ERROR       Indicates failure
   */
  method registerSharedBuffer(in uint64 start, in uint64 size);

  /**
   * @brief
   *    API for secure applications to deregister the shared buffer that has been
   *    previously registered with QSEE.
   *
   * @param[in] start Buffer reference, must match registered buffer.
   * @param[in] size Size of buffer [deprecated]
   *
   * @return Object_OK          Indicates success
   *         Object_ERROR       Indicates failure
   */
  method deregisterSharedBuffer(in uint64 start, in uint64 size);

  /**
   * @brief Flushes cachelines for the shared memory buffer.
   *        This must be called prior to passing buffer contents to consumer.
   *
   * @param[in] start Buffer reference, must match registered buffer.
   *
   * @return Object_OK          Indicates success
   *         Object_ERROR       Indicates failure
   */
  method flushCache(in uint64 start);

  /**
   * @brief Invalidates cachelines for the shared memory buffer.
   *        This must be called prior to accessing memory region.
   *
   * @param[in] start Buffer reference, must match registered buffer.
   *
   * @return Object_OK          Indicates success
   *         Object_ERROR       Indicates failure
   */
  method invalidateCache(in uint64 start);
};
