// Copyright (c) 2015 Qualcomm Technologies, Inc.  All Rights Reserved.
// Qualcomm Technologies Proprietary and Confidential.

/**
 * @brief Provides synchronization functions.
 */

interface ISync
{
  /**
   * @brief Perform a busy wait (spin) for the input number of microseconds.
   *
   * @param[in] timeoutUs - Number of microseconds to spin.
   *
   * @return Always returns Object_OK
   */

  method spin(in uint32 timeoutUs);
};
