// Copyright (c) 2017 Qualcomm Technologies, Inc. All Rights Reserved.
// Qualcomm Technologies Proprietary and Confidential.

//-------------------------------------------------------------------
// Interface to send TPM commands to WinSecApp
//------------------------------------------------------------------

interface ITPM {

const int32 MAX_REQ_BUFF_SIZE = 0x1000;   //4KB
const int32 MAX_RSP_BUFF_SIZE = 0x1000;   //4KB

const uint8 FLUSH_PENDING_TRUE = 1;
const uint8 FLUSH_PENDING_FALSE = 0;

/**
* Sends TPM command to WinSecApp
*
* @param[in] locality - locality for the command (4 < locality < 32)
* @param[in] reqBuffer - request buffer containing the command
* @param[in] rspBuffer - response  buffer
*
* @return 0 on success, negative on failure
*/

method SendTPMCommand(in uint8 locality, in buffer reqBuffer, out buffer rspBuffer);

/**
* Returns status of NV Flush to storage
*
* @param[out] flushPending - 1 if NV flush is pending
*                          - 0 if NV has been flushed
*
* @return 0 on success, negative on failure
*/
method CheckNVFlushState(out uint8 flushPending);

};


