// Copyright (c) 2015 Qualcomm Technologies, Inc.  All Rights Reserved.
// Qualcomm Technologies Proprietary and Confidential.

interface IUnwrapKeys {

  /**
   * Unwraps keys in an OEM-specific manner.
   *
   * @param [in] wrapped - Wrapped key data.
   * @param [in] unwrapped - unwrapped key data.
   *
   * @return Object_OK on success; Object_ERROR on failure to unwrap the data.
   */
  method unwrap(in buffer wrapped, out buffer unwrapped);
};
