/** @file  IUptime.idl */

/* Copyright (c) 2015-2017 Qualcomm Technologies, Inc.  All Rights Reserved.
   Qualcomm Technologies Proprietary and Confidential. */


/*
 * @brief Gets the up time from bootup
 *
*/

interface IUptime
{  
/**
 * @addtogroup core
 * @{
*/
    
/** Gets the up time from bootup in milliseconds.
 
    @param[out] upTimeMS Time from bootup in milliseconds.
 
    @return
    Object_OK if successful.
*/
  method getUptime(out uint64 upTimeMS);
/** @} */ /* end_addtogroup core */

/** @cond */
/* Gets the up time from bootup in microseconds.

    @param[out] upTimeUS Time from bootup in microseconds.

    @return
    Object_OK if successful.
*/
  method getUptimeUS(out uint64 upTimeUS);
/** @endcond */
};


