// Copyright (c) 2018 Qualcomm Technologies, Inc.  All Rights Reserved.
// Qualcomm Technologies Proprietary and Confidential.

interface IWait {

  /**
   * Return codes
   */
  error ERROR_INTERRUPTED;        /**< Wait was interrupted */

  /**
   * Flags
   */
  const int32 FLAG_INTERRUPTIBLE = 1;

  /**
   * @brief Wait for the specified amount of milliseconds.
   *
   * @param[in]  msec                            How long to wait, in milliseconds.
   *
   * @return  Object_OK if successful, IWait_ERROR_INTERRUPTED if the waiting was
   *          interrupted.
   */
  method wait(in uint32 msec, in uint32 flags);

};
