// Copyright (c) 2015 Qualcomm Technologies, Inc.  All Rights Reserved.
// Qualcomm Technologies Proprietary and Confidential.

interface IWatchdog {

   /**
    * @return Object_OK on success
    */

   method stop();

   /**
    * @return Object_OK on success
    */

   method pet();
};
