#ifndef ADSP_PS_IDL
#define ADSP_PS_IDL

#include "AEEStdDef.idl"

struct process
{
    int32 asid;
    int32 hlos_pid;
    string name;
};

typedef sequence<process> process_list;

interface adsp_ps{
    uint32 getProcessList(rout process_list current_processes, rout uint32 num_processes);
    uint32 getProcessListSerialized(rout string process_list, rout uint32 num_processes);
};

#endif /*ADSP_PS_IDL*/
