/**
 * Copyright (c) 2013-2014 QUALCOMM Technologies Inc. All Rights Reserved.
 * Qualcomm Technologies Confidential and Proprietary
 *
 */
module adsp {

   interface current_process {
      long exit();
      long thread_exit();
      long set_logging_params(in unsigned short mask, in sequence<string> filesToLog);
      long getASID(rout unsigned long asid);
   };
};

