/**
 * Copyright (c) 2013-2014 QUALCOMM Technologies Inc. All Rights Reserved.
 * Qualcomm Technologies Confidential and Proprietary
 *
 */
#include "remote.idl"

const long _const_adsp_current_process1_handle = 4;

module adsp {
   interface current_process1 : remote_handle64 {
      long exit();
      long thread_exit();
      long set_logging_params(in unsigned short mask, in sequence<string> filesToLog);
      long getASID(rout unsigned long asid);
   };
};

