#ifndef ADSP_PROCESS_GROUP_IDL
#define ADSP_PROCESS_GROUP_IDL

#include "AEEStdDef.idl"

const long _const_adsp_process_group_handle = 1;
struct mmap_page32 {
   uint32 phy_addr;
   int32 page_size;
};

struct mmap_page {
   uint64 phy_addr;
   int64 page_size;
};

module adsp {
   interface process_group {
      long create(in long pgid);
      long destroy(in long pgid);
      long mmap(in long pgid,
                in uint32 flags,
                in uint32 vaddrin,
                in sequence<uint8> pages, 
                rout uint32 vaddrout);
      long munmap(in long pgid, in uint32 vaddrin, in long len);
      long mmap64(in long pgid, 
                  in uint32 flags, 
                  in uint64 vaddrin, 
                  in sequence<uint8> pages, //! these are always mmap_page
                  rout uint64 vaddrout);
      long munmap64(in long pgid, in uint64 vaddrin, in int64 len);
      long create_mpd(in long pgid, in string appspdname, in sequence<char> elffile, in sequence<mmap_page> pages);
      long create_mpd_attrs(in long pgid, in string appspdname, in sequence<char> elffile, in sequence<mmap_page> pages, in long attrs, in long siglen);
      long create_staticpd(in long pgid,in string staticpdname, in sequence<mmap_page> pages);
      long get_tz_secure_channel(in long pgid ,rout uint8 secret_key);
   };
};

#endif // ADSP_PROCESS_GROUP_IDL
