#===========================================================================
#  Copyright (c) 2018 QUALCOMM Technologies Incorporated.
#  All Rights Reserved.
#  Qualcomm Confidential and Proprietary
#===========================================================================
#
# App Core
#
# GENERAL DESCRIPTION
#    build script
#                      EDIT HISTORY FOR FILE
#
#  This section contains schedulerents describing changes made to the module.
#  Notice that changes are listed in reverse chronological order.
#
# when       who     what, where, why
# --------   ---     ---------------------------------------------------------

#===============================================================================
import os

Import('env')
env = env.Clone()
#-------------------------------------------------------------------------------
# Compiler, object, and linker definitions
#-------------------------------------------------------------------------------
includes = [
  "#../../core/api/kernel/libstd/stringl",
  "#../../ssg/securemsm/trustzone/qsapps/libs/applib/qsee/src",
]

#------------------------------------------------------------------------------
# We need to specify "neon" to generate SIMD instructions in 32-bit mode
#------------------------------------------------------------------------------
if env['PROC'] == 'scorpion':
  env.Append(CCFLAGS = " -mfpu=neon ")

#----------------------------------------------------------------------------
# App core Objects
#----------------------------------------------------------------------------
sources = [
  'app_main.c',
  'CKeyGen.c',
]

#-------------------------------------------------------------------------------
# Add metadata to image
#-------------------------------------------------------------------------------
md = {
   'appName':           'keygentest',
   'privileges':        ['default',],
   'services':          ['KeyGen'],
   'acceptBufSize':     16384,
   #'memoryType':       'Unprotected',
}

deploy_header_files = env.Glob('*.h')

app = env.SecureAppBuilder(
  sources = sources,
  includes = includes,
  metadata = md,
  image = md['appName'],
  deploy_sources = [sources, 'SConscript', deploy_header_files],
  deploy_variants = env.GetDefaultPublicVariants()
)

for image in env['IMAGE_ALIASES']:
  op = env.Alias(image, app)

