/*============================================================================
  Copyright (c) 2016 QUALCOMM Technologies, Inc.  All Rights Reserved.
  QUALCOMM Technologies, Inc Proprietary.  Export of this technology or software is regulated
  by the U.S. Government, Diversion contrary to U.S. law prohibited.
============================================================================*/

#ifndef __ACD_MODEL_ATTRIBUTE_IDS_H__
#define __ACD_MODEL_ATTRIBUTE_IDS_H__

enum {
	ID_GLOBAL_HEADER_START = 100,
	ID_GLOBAL_HEADER_PAYLOAD_BYTES = ID_GLOBAL_HEADER_START,
	ID_GLOBAL_HEADER_MODEL_VERSION,
	ID_GLOBAL_HEADER_END,
};

enum {
	ID_CONFIGURATION_NUMBER_SOUND_MODELS = 300,
	ID_CONFIGURATION_NUMBER_DETECTION_SENSITIVITY_LEVELS,
	ID_CONFIGURATION_NUMBER_TRACKING_SENSITIVITY_LEVELS,
	ID_CONFIGURATION_FRAME_SKIP_RATE,
	ID_CONFIGURATION_TRACKING_ENABLE_BIT_SET,
	ID_CONFIGURATION_FORGETTING_FACTOR,
	ID_CONFIGURATION_MAX_NUMBER_OF_PROCESSING_FRAME,
	ID_CONFIGURATION_MAX_NUMBER_OF_CROSSLIKELIHOOD_FRAME,
	ID_CONFIGURATION_REJECTION_WINDOW_SIZE,

	ID_DETECTION_PHYSICAL_STATE_NUM_GRAPHS = 400,
	ID_DETECTION_PHYSICAL_STATE_NUM_LAYERS,
	ID_DETECTION_PHYSICAL_STATE_NUM_OUTPUT_NODES,
	ID_DETECTION_PHYSICAL_STATE_LAYER,
	ID_DETECTION_PHYSICAL_STATE_WEIGHTS,
	ID_DETECTION_PHYSICAL_STATE_RECTIFIER_PARAMS,
	ID_DETECTION_PHYSICAL_STATE_WEIGHT_Q_FACTOR,
	
	ID_CHANGE_PHYSICAL_STATE_NUM_STATES = 500,
	ID_CHANGE_PHYSICAL_STATE_NUM_TOTAL_GAUSSIAN,
	ID_CHANGE_PHYSICAL_STATE_NUM_DIMENSION,
	ID_CHANGE_PHYSICAL_STATE_KERNEL_LENGTH,
	ID_CHANGE_PHYSICAL_STATE_WGCONST,
	ID_CHANGE_PHYSICAL_STATE_MEANS,
	ID_CHANGE_PHYSICAL_STATE_INVARS,

	ID_SOUND_MODEL_FEATURE_KIND = 600,
	ID_SOUND_MODEL_DETECTION_DECISION_LENGTH,
	ID_SOUND_MODEL_TRACKING_DECISION_LENGTH,
	ID_SOUND_MODEL_DETECTION_MAX_DECISION_LENGTH,
	ID_SOUND_MODEL_TRACKING_MAX_DECISION_LENGTH,
	ID_SOUND_MODEL_SOUND_SPELLS,
	ID_SOUND_MODEL_DETECTION_THRESHOLDS,
	ID_SOUND_MODEL_TRACKING_THRESHOLDS,
	ID_SOUND_MODEL_NUM_TARGET_STATES_PER_SOUND,
	ID_SOUND_MODEL_PHYSICAL_STATE_INDEX_FOR_TARGET,
	ID_SOUND_MODEL_NUM_FILLER_STATES_PER_SOUND,
	ID_SOUND_MODEL_PHYSICAL_STATE_INDEX_FOR_FILLER,
	ID_SOUND_MODEL_NUM_TRACKING_STATES_PER_SOUND,
	ID_SOUND_MODEL_PHYSICAL_STATE_INDEX_FOR_TRACKING,
	ID_SOUND_MODEL_TRACKING_ADAPTATION_LENGTH,
	ID_SOUND_MODEL_MODEL_ADAPT_RATIO,
	ID_SOUND_MODEL_ADAPT_SAMPLING_RATE,
	ID_SOUND_MODEL_NEXT_TURN_ON_TIMES,
	ID_SOUND_MODEL_REJECTIONS,
	ID_SOUND_MODEL_TRACKING_REJECTIONS,
	ID_SOUND_MODEL_QUICK_REJECTION_THRESHOLD,

	ID_MODEL_METAINFO_DESCRIPTION = 700,	
};

#endif // __ACD_MODEL_ATTRIBUTE_IDS_H__