#===============================================================================
#
# Secure Camera Library
#
# GENERAL DESCRIPTION
#    build script
#
# Copyright (c) 2016-2017 by Qualcomm Technologies, Inc. All Rights Reserved.
# Qualcomm Technologies Proprietary and Confidential.
#
#-------------------------------------------------------------------------------
#
#  $Header: //components/rel/apps.tz/2.0.2/securemsm/trustzone/qsapps/seccamlib/src/SConscript#1 $
#  $DateTime: 2018/02/06 03:27:17 $
#  $Author: pwbldsvc $
#  $Change: 15400261 $
#                      EDIT HISTORY FOR FILE
#
#  This section contains schedulerents describing changes made to the module.
#  Notice that changes are listed in reverse chronological order.
#
# when       who     what, where, why
# --------   ---     ---------------------------------------------------------
# 08/14/17    dr     Port to sdm845
# 01/01/17    dr     Created
#===============================================================================
Import('env')
env = env.Clone()


libname = 'seccam_lib'

includes = [
  "${BUILD_ROOT}/core/api/services",
  "${BUILD_ROOT}/ssg/api/securemsm/trustzone/qsee",
  "${BUILD_ROOT}/core/api/kernel/libstd/stringl",
  "${BUILD_ROOT}/ssg/securemsm/accesscontrol/api",
  "${BUILD_ROOT}/core/kernel/smmu/ACv3.0/common/inc",
  "${BUILD_ROOT}/ssg/securemsm/trustzone/qsee/include/",
  "${BUILD_ROOT}/ssg/securemsm/trustzone/qsee/mink/include/",
   "../inc",
]

sources = ['seccamlib.c',]

lib = env.SecureAppLibBuilder(
    includes = includes,
    sources = sources,
    libname = libname,
    deploy_sources = ['SConscript',
                       env.Glob('../inc/*.h'),
                     ],
    deploy_lib = True,
    deploy_variants = env.GetDefaultPublicVariants()
    )
Return('lib')
