#===============================================================================
#
# DSP Shared Channel Library
#
# GENERAL DESCRIPTION
#    build script
#
# Copyright (c) 2018 by Qualcomm Technologies, Inc. All Rights Reserved.
# Qualcomm Technologies Proprietary and Confidential.
#
#-------------------------------------------------------------------------------
#
#  $Header: //components/rel/apps.tz/2.0.2/securemsm/trustzone/qsapps/secdsplib/SConscript#3 $
#  $DateTime: 2018/08/30 08:33:33 $
#  $Author: pwbldsvc $
#  $Change: 17004987 $
#                      EDIT HISTORY FOR FILE
#
#  This section contains schedulerents describing changes made to the module.
#  Notice that changes are listed in reverse chronological order.
#
# when       who     what, where, why
# --------   ---     ---------------------------------------------------------
#===============================================================================
Import('env')
env = env.Clone()

if env['PROC'] == 'scorpion':
   libname = 'dsc_lib'
else:
   libname = 'dsc_lib64'

sources_header = Glob('*.h')

includes = [
    "${BUILD_ROOT}/core/api/services",
    "${BUILD_ROOT}/core/api/kernel/libstd/stringl",
    "${BUILD_ROOT}/core/kernel/smmu/ACv3.0/common/inc",
    "${BUILD_ROOT}/ssg/api/securemsm/trustzone/qsee",
    "${BUILD_ROOT}/ssg/securemsm/accesscontrol/api",
    "${BUILD_ROOT}/ssg/securemsm/trustzone/qsee/include",
    "${BUILD_ROOT}/ssg/securemsm/trustzone/qsee/mink/include",
]

sources = Glob('*.c')

lib = env.SecureAppLibBuilder(includes, sources, libname)
env.Deploy([lib, 'SConscript', sources_header])

Return('lib')
