//////////////////////////////////////////////////////////////////////////////
// LPASS_ADDRESS_FILE.h generated by: addrfile2all.pl
// QCSR addrfile2all.pl 4.4.3
//////////////////////////////////////////////////////////////////////////////
// **** W A R N I N G ****  THIS FILE IS AUTO GENERATED!! PLEASE DO NOT EDIT!!
//////////////////////////////////////////////////////////////////////////////
// QUALCOMM Proprietary
// Copyright Qualcomm Technologies Incorporated.  All rights reserved.
//
// All data and information contained in or disclosed by this document are
// confidential and proprietary information of Qualcomm Technologies Incorporated, and
// all rights therein are expressly reserved. By accepting this material,
// the recipient agrees that this material and the information contained
// therein are held in confidence and in trust and will not be used,
// copied, reproduced in whole or in part, nor its contents revealed in
// any manner to others without the express written permission of QUALCOMM
// Incorporated.
//
// This technology was exported from the United States in accordance with
// the Export Administration Regulations. Diversion contrary to U.S. law
// prohibited.
//////////////////////////////////////////////////////////////////////////////
// RCS File        : -USE CVS LOG-
// Revision        : -USE CVS LOG-
// Last Check In   : -USE CVS LOG-
//////////////////////////////////////////////////////////////////////////////
// Description     : Constants related to Hardware Registers
//
// Byte Addresses are used for all BASES and ADDRESSES
//////////////////////////////////////////////////////////////////////////////
#ifndef LPASS_ADDRESS_SPDIF_FILE_H

#define LPASS_ADDRESS_SPDIF_FILE_H


#define LPASS_SPDIFTX_RESET_BASE                                                          (0xFE0B7000)

#define LPASS_SPDIFTX_CTL                                                                (0xFE0B7000)
#define   SPDIFTX_CTL___RWC                                                                QCSR_REG_RW
#define   SPDIFTX_CTL___POR                                                                0x00000000
#define   SPDIFTX_CTL__SOFT_RESET___M                                                      0x80000000
#define   SPDIFTX_CTL__SOFT_RESET___S                                                      31
#define   SPDIFTX_CTL__SOFT_RESET__DISABLE                                                 0x0
#define   SPDIFTX_CTL__SOFT_RESET__ENABLE                                                  0x1
#define   SPDIFTX_CTL__FORCE_RESET___M                                                     0x40000000
#define   SPDIFTX_CTL__FORCE_RESET___S                                                     30
#define   SPDIFTX_CTL__FORCE_RESET__DISABLE                                                0x0
#define   SPDIFTX_CTL__FORCE_RESET__ENABLE                                                 0x1
#define   SPDIFTX_CTL___M                                                                  0xC0000000
#define   SPDIFTX_CTL___S                                                                  30

#define LPASS_SPDIFTX_STAT                                                               (0xFE0B7004)
#define   SPDIFTX_STAT___RWC                                                               QCSR_REG_RO
#define   SPDIFTX_STAT___POR                                                               0x00000000
#define   SPDIFTX_STAT__SOFT_RESET_STAT___M                                                0x00000001
#define   SPDIFTX_STAT__SOFT_RESET_STAT___S                                                0
#define   SPDIFTX_STAT__SOFT_RESET_STAT__NO_SOFT_RESET_PRESENT                             0x0
#define   SPDIFTX_STAT__SOFT_RESET_STAT__SOFT_RESET_PRESENT                                0x1
#define   SPDIFTX_STAT___M                                                                 0x00000001
#define   SPDIFTX_STAT___S                                                                 0

#define LPASS_SPDIFTX_BASE                                                                  (0xFE133000)

#define LPASS_SPDIFTX_VERSION                                                            (0xFE133000)
#define   SPDIFTX_VERSION___RWC                                                            QCSR_REG_RO
#define   SPDIFTX_VERSION___POR                                                            0x10010001
#define   SPDIFTX_VERSION__MAJOR___M                                                       0xF0000000
#define   SPDIFTX_VERSION__MAJOR___S                                                       28
#define   SPDIFTX_VERSION__MINOR___M                                                       0x0FFF0000
#define   SPDIFTX_VERSION__MINOR___S                                                       16
#define   SPDIFTX_VERSION__STEP___M                                                        0x0000FFFF
#define   SPDIFTX_VERSION__STEP___S                                                        0
#define   SPDIFTX_VERSION___M                                                              0xFFFFFFFF
#define   SPDIFTX_VERSION___S                                                              0

#define LPASS_SPDIFTX_CFG                                                                (0xFE133004)
#define   SPDIFTX_CFG___RWC                                                                QCSR_REG_RW
#define   SPDIFTX_CFG___POR                                                                0x000003FF
#define   SPDIFTX_CFG__EN_INH_WTTS___M                                                     0x00020000
#define   SPDIFTX_CFG__EN_INH_WTTS___S                                                     17
#define   SPDIFTX_CFG__EN_INH_WTTS__DISABLE                                                0x0
#define   SPDIFTX_CFG__EN_INH_WTTS__ENABLE                                                 0x1
#define   SPDIFTX_CFG__DROP_LATE_BLOCKS___M                                                0x00010000
#define   SPDIFTX_CFG__DROP_LATE_BLOCKS___S                                                16
#define   SPDIFTX_CFG__DROP_LATE_BLOCKS__DISABLE                                           0x0
#define   SPDIFTX_CFG__DROP_LATE_BLOCKS__ENABLE                                            0x1
#define   SPDIFTX_CFG__FRAME_SIZE___M                                                      0x0000FFFF
#define   SPDIFTX_CFG__FRAME_SIZE___S                                                      0
#define   SPDIFTX_CFG___M                                                                  0x0003FFFF
#define   SPDIFTX_CFG___S                                                                  0

#define LPASS_SPDIFTX_PORT_SEL                                                           (0xFE133008)
#define   SPDIFTX_PORT_SEL___RWC                                                           QCSR_REG_RW
#define   SPDIFTX_PORT_SEL___POR                                                           0x00000000
#define   SPDIFTX_PORT_SEL__USER_DATA_DBUFF_EN___M                                         0x00001000
#define   SPDIFTX_PORT_SEL__USER_DATA_DBUFF_EN___S                                         12
#define   SPDIFTX_PORT_SEL__USER_DATA_DBUFF_EN__USER_DATA_DBUFF_EN_IS_DISABLED             0x0
#define   SPDIFTX_PORT_SEL__USER_DATA_DBUFF_EN__USER_DATA_DBUFF_EN_IS_ENABLED              0x1
#define   SPDIFTX_PORT_SEL__PORT_SEL_SPARE___M                                             0x00000E00
#define   SPDIFTX_PORT_SEL__PORT_SEL_SPARE___S                                             9
#define   SPDIFTX_PORT_SEL__CH_STAT_DBUFF_EN___M                                           0x00000100
#define   SPDIFTX_PORT_SEL__CH_STAT_DBUFF_EN___S                                           8
#define   SPDIFTX_PORT_SEL__CH_STAT_DBUFF_EN__CH_STAT_DBUFF_EN_IS_DISABLED                 0x0
#define   SPDIFTX_PORT_SEL__CH_STAT_DBUFF_EN__CH_STAT_DBUFF_EN_IS_ENABLED                  0x1
#define   SPDIFTX_PORT_SEL__PARITY_ERR___M                                                 0x00000080
#define   SPDIFTX_PORT_SEL__PARITY_ERR___S                                                 7
#define   SPDIFTX_PORT_SEL__PARITY_ERR__NO_PARITY_ERROR                                    0x0
#define   SPDIFTX_PORT_SEL__PARITY_ERR__PARITY_ERROR_ENFORCED                              0x1
#define   SPDIFTX_PORT_SEL__PARITY_EN___M                                                  0x00000040
#define   SPDIFTX_PORT_SEL__PARITY_EN___S                                                  6
#define   SPDIFTX_PORT_SEL__PARITY_EN__ENABLED                                             0x0
#define   SPDIFTX_PORT_SEL__PARITY_EN__DISABLED                                            0x1
#define   SPDIFTX_PORT_SEL__PREAMB_POL___M                                                 0x00000020
#define   SPDIFTX_PORT_SEL__PREAMB_POL___S                                                 5
#define   SPDIFTX_PORT_SEL__PREAMB_POL__POSITIVE                                           0x0
#define   SPDIFTX_PORT_SEL__PREAMB_POL__NEGATIVE                                           0x1
#define   SPDIFTX_PORT_SEL__USER_DATA_EN___M                                               0x00000018
#define   SPDIFTX_PORT_SEL__USER_DATA_EN___S                                               3
#define   SPDIFTX_PORT_SEL__CH_STAT_EN___M                                                 0x00000006
#define   SPDIFTX_PORT_SEL__CH_STAT_EN___S                                                 1
#define   SPDIFTX_PORT_SEL__CH_STAT_EN__UNUSED                                             0x0
#define   SPDIFTX_PORT_SEL__CH_STAT_EN__CH1_STATUS_A_CH2_STATUS_B                          0x1
#define   SPDIFTX_PORT_SEL__CH_STAT_EN__CH1_AND_CH2_STATUS_A                               0x2
#define   SPDIFTX_PORT_SEL__CH_STAT_EN__CH1_AND_CH2_STATUS_B                               0x3
#define   SPDIFTX_PORT_SEL__PORT_EN___M                                                    0x00000001
#define   SPDIFTX_PORT_SEL__PORT_EN___S                                                    0
#define   SPDIFTX_PORT_SEL__PORT_EN__TRANSMITTER_DISABLED                                  0x0
#define   SPDIFTX_PORT_SEL__PORT_EN__TRANSMITTER_ENABLED                                   0x1
#define   SPDIFTX_PORT_SEL___M                                                             0x00001FFF
#define   SPDIFTX_PORT_SEL___S                                                             0

#define LPASS_SPDIFTX_CMD                                                                (0xFE13300C)
#define   SPDIFTX_CMD___RWC                                                                QCSR_REG_COMMAND
#define   SPDIFTX_CMD___POR                                                                0x00000000
#define   SPDIFTX_CMD__ABORT_BLOCK___M                                                     0x00000004
#define   SPDIFTX_CMD__ABORT_BLOCK___S                                                     2
#define   SPDIFTX_CMD__SUBBUF_FIFO_CLEAR_ALL___M                                           0x00000002
#define   SPDIFTX_CMD__SUBBUF_FIFO_CLEAR_ALL___S                                           1
#define   SPDIFTX_CMD__PAUSE___M                                                           0x00000001
#define   SPDIFTX_CMD__PAUSE___S                                                           0
#define   SPDIFTX_CMD___M                                                                  0x00000007
#define   SPDIFTX_CMD___S                                                                  0

#define LPASS_SPDIFTX_PORT_CFG                                                           (0xFE133010)
#define   SPDIFTX_PORT_CFG___RWC                                                           QCSR_REG_RW
#define   SPDIFTX_PORT_CFG___POR                                                           0x00000444
#define   SPDIFTX_PORT_CFG__MONO_SEL___M                                                   0x00000400
#define   SPDIFTX_PORT_CFG__MONO_SEL___S                                                   10
#define   SPDIFTX_PORT_CFG__MONO_SEL__BOTH_SAME_INFO                                       0x0
#define   SPDIFTX_PORT_CFG__MONO_SEL__CHANNEL_A_DATA_WHILE_CHANNEL_B_ALL_ZEROS             0x1
#define   SPDIFTX_PORT_CFG__SOFT_MUTE_AFTER_EOF___M                                        0x00000200
#define   SPDIFTX_PORT_CFG__SOFT_MUTE_AFTER_EOF___S                                        9
#define   SPDIFTX_PORT_CFG__SOFT_MUTE_AFTER_EOF__MUTE_RIGHT_AWAY                           0x0
#define   SPDIFTX_PORT_CFG__SOFT_MUTE_AFTER_EOF__MUTE_AFTER_END_OF_FRAME                   0x1
#define   SPDIFTX_PORT_CFG__SOFT_MUTE___M                                                  0x00000100
#define   SPDIFTX_PORT_CFG__SOFT_MUTE___S                                                  8
#define   SPDIFTX_PORT_CFG__SOFT_MUTE__NO_MUTE                                             0x0
#define   SPDIFTX_PORT_CFG__SOFT_MUTE__MUTE                                                0x1
#define   SPDIFTX_PORT_CFG__EMPTY_FIFO_REPEAT_MUTE___M                                     0x000000C0
#define   SPDIFTX_PORT_CFG__EMPTY_FIFO_REPEAT_MUTE___S                                     6
#define   SPDIFTX_PORT_CFG__EMPTY_FIFO_REPEAT_MUTE__ZERO_MUTE_SAMPLE                       0x0
#define   SPDIFTX_PORT_CFG__EMPTY_FIFO_REPEAT_MUTE__REPEAT_LAST_SAMPLE                     0x1
#define   SPDIFTX_PORT_CFG__MONO___M                                                       0x00000030
#define   SPDIFTX_PORT_CFG__MONO___S                                                       4
#define   SPDIFTX_PORT_CFG__MONO__STEREO_TX                                                0x0
#define   SPDIFTX_PORT_CFG__MONO__MONO_TX_SEND_ONE_SAMPLE_ON_BOTH_CHANNELS                 0x1
#define   SPDIFTX_PORT_CFG__FRAMEDATA_WIDTH___M                                            0x0000000F
#define   SPDIFTX_PORT_CFG__FRAMEDATA_WIDTH___S                                            0
#define   SPDIFTX_PORT_CFG__FRAMEDATA_WIDTH__BIT_16                                        0x0
#define   SPDIFTX_PORT_CFG__FRAMEDATA_WIDTH__BIT_17                                        0x1
#define   SPDIFTX_PORT_CFG__FRAMEDATA_WIDTH__BIT_18                                        0x2
#define   SPDIFTX_PORT_CFG__FRAMEDATA_WIDTH__BIT_19                                        0x3
#define   SPDIFTX_PORT_CFG__FRAMEDATA_WIDTH__BIT_20                                        0x4
#define   SPDIFTX_PORT_CFG__FRAMEDATA_WIDTH__BIT_21                                        0x5
#define   SPDIFTX_PORT_CFG__FRAMEDATA_WIDTH__BIT_22                                        0x6
#define   SPDIFTX_PORT_CFG__FRAMEDATA_WIDTH__BIT_23                                        0x7
#define   SPDIFTX_PORT_CFG__FRAMEDATA_WIDTH__BIT_24                                        0x8
#define   SPDIFTX_PORT_CFG___M                                                             0x000007FF
#define   SPDIFTX_PORT_CFG___S                                                             0

#define LPASS_SPDIFTX_FIFO_CNTL                                                          (0xFE133014)
#define   SPDIFTX_FIFO_CNTL___RWC                                                          QCSR_REG_RW
#define   SPDIFTX_FIFO_CNTL___POR                                                          0x000000C0
#define   SPDIFTX_FIFO_CNTL__LJUSTIFIED___M                                                0x00000200
#define   SPDIFTX_FIFO_CNTL__LJUSTIFIED___S                                                9
#define   SPDIFTX_FIFO_CNTL__LJUSTIFIED__RIGHT_JUSTIFIED                                   0x0
#define   SPDIFTX_FIFO_CNTL__LJUSTIFIED__LEFT_JUSTIFIED                                    0x1
#define   SPDIFTX_FIFO_CNTL__FIFP_JUMP_RD_PTR___M                                          0x00000100
#define   SPDIFTX_FIFO_CNTL__FIFP_JUMP_RD_PTR___S                                          8
#define   SPDIFTX_FIFO_CNTL__FIFP_JUMP_RD_PTR__NO_JUMP                                     0x0
#define   SPDIFTX_FIFO_CNTL__FIFP_JUMP_RD_PTR__WHEN_WTTS_IS_SET_JUMP_TO_NEXT_SUBBUFFER_FIFO 0x1
#define   SPDIFTX_FIFO_CNTL__FIFO_PRE_BUF_EN___M                                           0x00000080
#define   SPDIFTX_FIFO_CNTL__FIFO_PRE_BUF_EN___S                                           7
#define   SPDIFTX_FIFO_CNTL__FIFO_PRE_BUF_EN__DISABLE_PRE_BUFFERING                        0x0
#define   SPDIFTX_FIFO_CNTL__FIFO_PRE_BUF_EN__ENABLE_PRE_BUFFERING                         0x1
#define   SPDIFTX_FIFO_CNTL__WATERMARK___M                                                 0x00000078
#define   SPDIFTX_FIFO_CNTL__WATERMARK___S                                                 3
#define   SPDIFTX_FIFO_CNTL__DWORD_WORD_SWAP___M                                           0x00000004
#define   SPDIFTX_FIFO_CNTL__DWORD_WORD_SWAP___S                                           2
#define   SPDIFTX_FIFO_CNTL__DWORD_WORD_SWAP__NO_SWAP                                      0x0
#define   SPDIFTX_FIFO_CNTL__DWORD_WORD_SWAP__SWAP_WORD                                    0x1
#define   SPDIFTX_FIFO_CNTL__WORD_BYTE_SWAP___M                                            0x00000002
#define   SPDIFTX_FIFO_CNTL__WORD_BYTE_SWAP___S                                            1
#define   SPDIFTX_FIFO_CNTL__WORD_BYTE_SWAP__NO_SWAP                                       0x0
#define   SPDIFTX_FIFO_CNTL__WORD_BYTE_SWAP__SWAP_BYTE                                     0x1
#define   SPDIFTX_FIFO_CNTL___M                                                            0x000003FE
#define   SPDIFTX_FIFO_CNTL___S                                                            1

#define LPASS_SPDIFTX_SUBBUF_FIFO                                                        (0xFE133018)
#define   SPDIFTX_SUBBUF_FIFO___RWC                                                        QCSR_REG_COMMAND
#define   SPDIFTX_SUBBUF_FIFO___POR                                                        0x00000000
#define   SPDIFTX_SUBBUF_FIFO__ERR_FLG___M                                                 0x00200000
#define   SPDIFTX_SUBBUF_FIFO__ERR_FLG___S                                                 21
#define   SPDIFTX_SUBBUF_FIFO__DATA_TYPE_DEP_INFO___M                                      0x001F0000
#define   SPDIFTX_SUBBUF_FIFO__DATA_TYPE_DEP_INFO___S                                      16
#define   SPDIFTX_SUBBUF_FIFO__BITSTREAM_NUM___M                                           0x0000E000
#define   SPDIFTX_SUBBUF_FIFO__BITSTREAM_NUM___S                                           13
#define   SPDIFTX_SUBBUF_FIFO__WAIT_TILL_TS_FLAG___M                                       0x00001000
#define   SPDIFTX_SUBBUF_FIFO__WAIT_TILL_TS_FLAG___S                                       12
#define   SPDIFTX_SUBBUF_FIFO__WAIT_TILL_TS_FLAG__PLAY_THE_FRAME_IMMEDIATELY               0x0
#define   SPDIFTX_SUBBUF_FIFO__WAIT_TILL_TS_FLAG__WAIT_TILL_TIME_STAMP                     0x1
#define   SPDIFTX_SUBBUF_FIFO__FRAME_SIZE_ADJUST___M                                       0x00000FFF
#define   SPDIFTX_SUBBUF_FIFO__FRAME_SIZE_ADJUST___S                                       0
#define   SPDIFTX_SUBBUF_FIFO___M                                                          0x003FFFFF
#define   SPDIFTX_SUBBUF_FIFO___S                                                          0

#define LPASS_SPDIFTX_TIME_STAMP_FIFO_1                                                  (0xFE13301C)
#define   SPDIFTX_TIME_STAMP_FIFO_1___RWC                                                  QCSR_REG_WO
#define   SPDIFTX_TIME_STAMP_FIFO_1___POR                                                  0x00000000
#define   SPDIFTX_TIME_STAMP_FIFO_1__TIME_STAMP_LOW_32___M                                 0xFFFFFFFF
#define   SPDIFTX_TIME_STAMP_FIFO_1__TIME_STAMP_LOW_32___S                                 0
#define   SPDIFTX_TIME_STAMP_FIFO_1___M                                                    0xFFFFFFFF
#define   SPDIFTX_TIME_STAMP_FIFO_1___S                                                    0

#define LPASS_SPDIFTX_TIME_STAMP_FIFO_2                                                  (0xFE133020)
#define   SPDIFTX_TIME_STAMP_FIFO_2___RWC                                                  QCSR_REG_WO
#define   SPDIFTX_TIME_STAMP_FIFO_2___POR                                                  0x00000000
#define   SPDIFTX_TIME_STAMP_FIFO_2__TIME_STAMP_UPPER_24___M                               0x00FFFFFF
#define   SPDIFTX_TIME_STAMP_FIFO_2__TIME_STAMP_UPPER_24___S                               0
#define   SPDIFTX_TIME_STAMP_FIFO_2___M                                                    0x00FFFFFF
#define   SPDIFTX_TIME_STAMP_FIFO_2___S                                                    0

#define LPASS_SPDIFTX_SUBBUF_FIFO_STA                                                    (0xFE133024)
#define   SPDIFTX_SUBBUF_FIFO_STA___RWC                                                    QCSR_REG_RO
#define   SPDIFTX_SUBBUF_FIFO_STA___POR                                                    0x00000000
#define   SPDIFTX_SUBBUF_FIFO_STA__FILL_LEVEL_RELEASE___M                                  0x000000F0
#define   SPDIFTX_SUBBUF_FIFO_STA__FILL_LEVEL_RELEASE___S                                  4
#define   SPDIFTX_SUBBUF_FIFO_STA__FILL_LEVEL_READ___M                                     0x0000000F
#define   SPDIFTX_SUBBUF_FIFO_STA__FILL_LEVEL_READ___S                                     0
#define   SPDIFTX_SUBBUF_FIFO_STA___M                                                      0x000000FF
#define   SPDIFTX_SUBBUF_FIFO_STA___S                                                      0

#define LPASS_SPDIFTX_TS_DIFF_1                                                          (0xFE133028)
#define   SPDIFTX_TS_DIFF_1___RWC                                                          QCSR_REG_RO
#define   SPDIFTX_TS_DIFF_1___POR                                                          0x00000000
#define   SPDIFTX_TS_DIFF_1__TS_DIFF_LOW_32___M                                            0xFFFFFFFF
#define   SPDIFTX_TS_DIFF_1__TS_DIFF_LOW_32___S                                            0
#define   SPDIFTX_TS_DIFF_1___M                                                            0xFFFFFFFF
#define   SPDIFTX_TS_DIFF_1___S                                                            0

#define LPASS_SPDIFTX_TS_DIFF_2                                                          (0xFE13302C)
#define   SPDIFTX_TS_DIFF_2___RWC                                                          QCSR_REG_RO
#define   SPDIFTX_TS_DIFF_2___POR                                                          0x00000000
#define   SPDIFTX_TS_DIFF_2__TS_DIFF_UPPER_24___M                                          0x00FFFFFF
#define   SPDIFTX_TS_DIFF_2__TS_DIFF_UPPER_24___S                                          0
#define   SPDIFTX_TS_DIFF_2___M                                                            0x00FFFFFF
#define   SPDIFTX_TS_DIFF_2___S                                                            0

#define LPASS_SPDIFTX_TS_DIFF_ACC_1                                                      (0xFE133030)
#define   SPDIFTX_TS_DIFF_ACC_1___RWC                                                      QCSR_REG_COMMAND
#define   SPDIFTX_TS_DIFF_ACC_1___POR                                                      0x00000000
#define   SPDIFTX_TS_DIFF_ACC_1__TS_DIFF_ACC_LOW_32___M                                    0xFFFFFFFF
#define   SPDIFTX_TS_DIFF_ACC_1__TS_DIFF_ACC_LOW_32___S                                    0
#define   SPDIFTX_TS_DIFF_ACC_1__TS_DIFF_ACC_RESET_ALL_56___M                              0x00000001
#define   SPDIFTX_TS_DIFF_ACC_1__TS_DIFF_ACC_RESET_ALL_56___S                              0
#define   SPDIFTX_TS_DIFF_ACC_1___M                                                        0xFFFFFFFF
#define   SPDIFTX_TS_DIFF_ACC_1___S                                                        0

#define LPASS_SPDIFTX_TS_DIFF_ACC_2                                                      (0xFE133034)
#define   SPDIFTX_TS_DIFF_ACC_2___RWC                                                      QCSR_REG_RO
#define   SPDIFTX_TS_DIFF_ACC_2___POR                                                      0x00000000
#define   SPDIFTX_TS_DIFF_ACC_2__TS_DIFF_ACC_UPPER_24___M                                  0x00FFFFFF
#define   SPDIFTX_TS_DIFF_ACC_2__TS_DIFF_ACC_UPPER_24___S                                  0
#define   SPDIFTX_TS_DIFF_ACC_2___M                                                        0x00FFFFFF
#define   SPDIFTX_TS_DIFF_ACC_2___S                                                        0

#define LPASS_SPDIFTX_MISC_CNTL                                                          (0xFE133038)
#define   SPDIFTX_MISC_CNTL___RWC                                                          QCSR_REG_RW
#define   SPDIFTX_MISC_CNTL___POR                                                          0x00000000
#define   SPDIFTX_MISC_CNTL__SPARE___M                                                     0xFFFFFFE0
#define   SPDIFTX_MISC_CNTL__SPARE___S                                                     5
#define   SPDIFTX_MISC_CNTL__TSIZE___M                                                     0x00000018
#define   SPDIFTX_MISC_CNTL__TSIZE___S                                                     3
#define   SPDIFTX_MISC_CNTL__TSIZE__ONE_DWORD                                              0x0
#define   SPDIFTX_MISC_CNTL__TSIZE__RSRVD                                                  0x1
#define   SPDIFTX_MISC_CNTL__TSIZE__FOUR_DWORDS                                            0x2
#define   SPDIFTX_MISC_CNTL__TSIZE__EIGHT_DWORDS                                           0x3
#define   SPDIFTX_MISC_CNTL__NONLIN_DATA_SWAP_CNTL___M                                     0x00000004
#define   SPDIFTX_MISC_CNTL__NONLIN_DATA_SWAP_CNTL___S                                     2
#define   SPDIFTX_MISC_CNTL__NONLIN_DATA_SWAP_CNTL__ORIGINAL_WAY_WITHOUT_SWAPPING          0x0
#define   SPDIFTX_MISC_CNTL__NONLIN_DATA_SWAP_CNTL__SWAP_PAYLOAD_DATA                      0x1
#define   SPDIFTX_MISC_CNTL__VALID_BIT_BYPASS_VALUE___M                                    0x00000002
#define   SPDIFTX_MISC_CNTL__VALID_BIT_BYPASS_VALUE___S                                    1
#define   SPDIFTX_MISC_CNTL__VALID_BIT_BYPASS_VALUE__OVERWRITE_VALID_BIT_WITH_0            0x0
#define   SPDIFTX_MISC_CNTL__VALID_BIT_BYPASS_VALUE__OVERWRITE_VALID_BIT_WITH_1            0x1
#define   SPDIFTX_MISC_CNTL__SW_NONLINPCM_BYPASS_SUPPORT___M                               0x00000001
#define   SPDIFTX_MISC_CNTL__SW_NONLINPCM_BYPASS_SUPPORT___S                               0
#define   SPDIFTX_MISC_CNTL__SW_NONLINPCM_BYPASS_SUPPORT__HW_NON_LINEAR_MODE_SUPPORT       0x0
#define   SPDIFTX_MISC_CNTL__SW_NONLINPCM_BYPASS_SUPPORT__SW_NON_LINEAR_MODE_SUPPORT       0x1
#define   SPDIFTX_MISC_CNTL___M                                                            0xFFFFFFFF
#define   SPDIFTX_MISC_CNTL___S                                                            0

#define LPASS_SPDIFTX_BUF_PNTR                                                           (0xFE13303C)
#define   SPDIFTX_BUF_PNTR___RWC                                                           QCSR_REG_WO
#define   SPDIFTX_BUF_PNTR___POR                                                           0x00000000
#define   SPDIFTX_BUF_PNTR__PNTR___M                                                       0xFFFFFFFF
#define   SPDIFTX_BUF_PNTR__PNTR___S                                                       0
#define   SPDIFTX_BUF_PNTR___M                                                             0xFFFFFFFF
#define   SPDIFTX_BUF_PNTR___S                                                             0

#define LPASS_SPDIFTX_FIFO_TST_CNTL                                                      (0xFE133040)
#define   SPDIFTX_FIFO_TST_CNTL___RWC                                                      QCSR_REG_RO
#define   SPDIFTX_FIFO_TST_CNTL___POR                                                      0x00000000
#define   SPDIFTX_FIFO_TST_CNTL__FIFO_URUN_LOST_SAMPLES___M                                0x0000FFFF
#define   SPDIFTX_FIFO_TST_CNTL__FIFO_URUN_LOST_SAMPLES___S                                0
#define   SPDIFTX_FIFO_TST_CNTL___M                                                        0x0000FFFF
#define   SPDIFTX_FIFO_TST_CNTL___S                                                        0

#define LPASS_SPDIFTX_STATISTICS                                                         (0xFE133044)
#define   SPDIFTX_STATISTICS___RWC                                                         QCSR_REG_RO
#define   SPDIFTX_STATISTICS___POR                                                         0x00000000
#define   SPDIFTX_STATISTICS__BLOCK_NUM___M                                                0xFFFF0000
#define   SPDIFTX_STATISTICS__BLOCK_NUM___S                                                16
#define   SPDIFTX_STATISTICS__FRAME_NUM___M                                                0x000000FF
#define   SPDIFTX_STATISTICS__FRAME_NUM___S                                                0
#define   SPDIFTX_STATISTICS___M                                                           0xFFFFFFFF
#define   SPDIFTX_STATISTICS___S                                                           0

#define LPASS_SPDIFTX_INT_CNTL                                                           (0xFE133048)
#define   SPDIFTX_INT_CNTL___RWC                                                           QCSR_REG_RW
#define   SPDIFTX_INT_CNTL___POR                                                           0x00000000
#define   SPDIFTX_INT_CNTL__INT_MASK___M                                                   0x00000080
#define   SPDIFTX_INT_CNTL__INT_MASK___S                                                   7
#define   SPDIFTX_INT_CNTL__INT_MASK__Q6_INT_EN_AND_APP_INT_DIS                            0x0
#define   SPDIFTX_INT_CNTL__INT_MASK__Q6_INT_DIS_AND_APP_INT_EN                            0x1
#define   SPDIFTX_INT_CNTL__TX_MC_ERR___M                                                  0x00000040
#define   SPDIFTX_INT_CNTL__TX_MC_ERR___S                                                  6
#define   SPDIFTX_INT_CNTL__TX_MC_ERR__DISABLE                                             0x0
#define   SPDIFTX_INT_CNTL__TX_MC_ERR__ENABLE                                              0x1
#define   SPDIFTX_INT_CNTL__TX_TS_DIFF_INT_EN___M                                          0x00000020
#define   SPDIFTX_INT_CNTL__TX_TS_DIFF_INT_EN___S                                          5
#define   SPDIFTX_INT_CNTL__TX_TS_DIFF_INT_EN__DISABLE                                     0x0
#define   SPDIFTX_INT_CNTL__TX_TS_DIFF_INT_EN__ENABLE                                      0x1
#define   SPDIFTX_INT_CNTL__TX_DROP_LATE_BLOCK_INT_EN___M                                  0x00000010
#define   SPDIFTX_INT_CNTL__TX_DROP_LATE_BLOCK_INT_EN___S                                  4
#define   SPDIFTX_INT_CNTL__TX_DROP_LATE_BLOCK_INT_EN__DISABLE                             0x0
#define   SPDIFTX_INT_CNTL__TX_DROP_LATE_BLOCK_INT_EN__ENABLE                              0x1
#define   SPDIFTX_INT_CNTL__TX_PAUSE_INT_EN___M                                            0x00000008
#define   SPDIFTX_INT_CNTL__TX_PAUSE_INT_EN___S                                            3
#define   SPDIFTX_INT_CNTL__TX_PAUSE_INT_EN__DISABLE                                       0x0
#define   SPDIFTX_INT_CNTL__TX_PAUSE_INT_EN__ENABLE                                        0x1
#define   SPDIFTX_INT_CNTL__TX_IDLE_INT_EN___M                                             0x00000004
#define   SPDIFTX_INT_CNTL__TX_IDLE_INT_EN___S                                             2
#define   SPDIFTX_INT_CNTL__TX_IDLE_INT_EN__DISABLE                                        0x0
#define   SPDIFTX_INT_CNTL__TX_IDLE_INT_EN__ENABLE                                         0x1
#define   SPDIFTX_INT_CNTL__TX_FIFO_UNDERFLOW_INT_EN___M                                   0x00000002
#define   SPDIFTX_INT_CNTL__TX_FIFO_UNDERFLOW_INT_EN___S                                   1
#define   SPDIFTX_INT_CNTL__TX_FIFO_UNDERFLOW_INT_EN__DISABLE                              0x0
#define   SPDIFTX_INT_CNTL__TX_FIFO_UNDERFLOW_INT_EN__ENABLE                               0x1
#define   SPDIFTX_INT_CNTL__TX_BLOCK_DONE_INT_EN___M                                       0x00000001
#define   SPDIFTX_INT_CNTL__TX_BLOCK_DONE_INT_EN___S                                       0
#define   SPDIFTX_INT_CNTL__TX_BLOCK_DONE_INT_EN__DISABLE                                  0x0
#define   SPDIFTX_INT_CNTL__TX_BLOCK_DONE_INT_EN__ENABLE                                   0x1
#define   SPDIFTX_INT_CNTL___M                                                             0x000000FF
#define   SPDIFTX_INT_CNTL___S                                                             0

#define LPASS_SPDIFTX_INT_STATUS                                                         (0xFE13304C)
#define   SPDIFTX_INT_STATUS___RWC                                                         QCSR_REG_COMMAND
#define   SPDIFTX_INT_STATUS___POR                                                         0x00000004
#define   SPDIFTX_INT_STATUS__TX_MC_ERR_ACK___M                                            0x00000040
#define   SPDIFTX_INT_STATUS__TX_MC_ERR_ACK___S                                            6
#define   SPDIFTX_INT_STATUS__TX_MC_ERR_ACK__NO_EFFECT                                     0x0
#define   SPDIFTX_INT_STATUS__TX_MC_ERR_ACK__CLEAR_STATUS                                  0x1
#define   SPDIFTX_INT_STATUS__TX_MC_ERR_STA___M                                            0x00000040
#define   SPDIFTX_INT_STATUS__TX_MC_ERR_STA___S                                            6
#define   SPDIFTX_INT_STATUS__TX_MC_ERR_STA__NO_EVENT                                      0x0
#define   SPDIFTX_INT_STATUS__TX_MC_ERR_STA__DIFFERENCE_BETWEEN_TIME_STAMP_AND_ACTUAL_PRESENTATION_TIME_LATCHED 0x1
#define   SPDIFTX_INT_STATUS__TX_TS_DIFF_ACK___M                                           0x00000020
#define   SPDIFTX_INT_STATUS__TX_TS_DIFF_ACK___S                                           5
#define   SPDIFTX_INT_STATUS__TX_TS_DIFF_ACK__NO_EFFECT                                    0x0
#define   SPDIFTX_INT_STATUS__TX_TS_DIFF_ACK__CLEAR_STATUS                                 0x1
#define   SPDIFTX_INT_STATUS__TX_TS_DIFF_STA___M                                           0x00000020
#define   SPDIFTX_INT_STATUS__TX_TS_DIFF_STA___S                                           5
#define   SPDIFTX_INT_STATUS__TX_TS_DIFF_STA__NO_EVENT                                     0x0
#define   SPDIFTX_INT_STATUS__TX_TS_DIFF_STA__DIFFERENCE_BETWEEN_TIME_STAMP_AND_ACTUAL_PRESENTATION_TIME_LATCHED 0x1
#define   SPDIFTX_INT_STATUS__TX_DROP_LATE_BLOCK_ACK___M                                   0x00000010
#define   SPDIFTX_INT_STATUS__TX_DROP_LATE_BLOCK_ACK___S                                   4
#define   SPDIFTX_INT_STATUS__TX_DROP_LATE_BLOCK_ACK__NO_EFFECT                            0x0
#define   SPDIFTX_INT_STATUS__TX_DROP_LATE_BLOCK_ACK__CLEAR_STATUS                         0x1
#define   SPDIFTX_INT_STATUS__TX_DROP_LATE_BLOCK_STA___M                                   0x00000010
#define   SPDIFTX_INT_STATUS__TX_DROP_LATE_BLOCK_STA___S                                   4
#define   SPDIFTX_INT_STATUS__TX_DROP_LATE_BLOCK_STA__NO_EVENT                             0x0
#define   SPDIFTX_INT_STATUS__TX_DROP_LATE_BLOCK_STA__FRAME_WITH_PRESENTATION_TIME_PASSED_WAS_DROPPED 0x1
#define   SPDIFTX_INT_STATUS__TX_PAUSE_ACK___M                                             0x00000008
#define   SPDIFTX_INT_STATUS__TX_PAUSE_ACK___S                                             3
#define   SPDIFTX_INT_STATUS__TX_PAUSE_ACK__NO_EFFECT                                      0x0
#define   SPDIFTX_INT_STATUS__TX_PAUSE_ACK__CLEAR_STATUS                                   0x1
#define   SPDIFTX_INT_STATUS__TX_PAUSE_STA___M                                             0x00000008
#define   SPDIFTX_INT_STATUS__TX_PAUSE_STA___S                                             3
#define   SPDIFTX_INT_STATUS__TX_PAUSE_STA__TRANSMITTER_IS_ACTIVE                          0x0
#define   SPDIFTX_INT_STATUS__TX_PAUSE_STA__TRANSMITTER_IS_IN_THE_PAUSE_STATE              0x1
#define   SPDIFTX_INT_STATUS__TX_IDLE_ACK___M                                              0x00000004
#define   SPDIFTX_INT_STATUS__TX_IDLE_ACK___S                                              2
#define   SPDIFTX_INT_STATUS__TX_IDLE_ACK__NO_EFFECT                                       0x0
#define   SPDIFTX_INT_STATUS__TX_IDLE_ACK__CLEAR_STATUS                                    0x1
#define   SPDIFTX_INT_STATUS__TX_IDLE_STA___M                                              0x00000004
#define   SPDIFTX_INT_STATUS__TX_IDLE_STA___S                                              2
#define   SPDIFTX_INT_STATUS__TX_IDLE_STA__TRANSMITTER_IS_BUSY                             0x0
#define   SPDIFTX_INT_STATUS__TX_IDLE_STA__TRANSMITTER_IS_IDLE                             0x1
#define   SPDIFTX_INT_STATUS__TX_FIFO_UNDERFLOW_ACK___M                                    0x00000002
#define   SPDIFTX_INT_STATUS__TX_FIFO_UNDERFLOW_ACK___S                                    1
#define   SPDIFTX_INT_STATUS__TX_FIFO_UNDERFLOW_ACK__NO_EFFECT                             0x0
#define   SPDIFTX_INT_STATUS__TX_FIFO_UNDERFLOW_ACK__CLEAR_STATUS                          0x1
#define   SPDIFTX_INT_STATUS__TX_FIFO_UNDERFLOW_STA___M                                    0x00000002
#define   SPDIFTX_INT_STATUS__TX_FIFO_UNDERFLOW_STA___S                                    1
#define   SPDIFTX_INT_STATUS__TX_FIFO_UNDERFLOW_STA__NO_EVENT                              0x0
#define   SPDIFTX_INT_STATUS__TX_FIFO_UNDERFLOW_STA__TRANSMIT_FIFO_UNDERFLOW_OCCURRED      0x1
#define   SPDIFTX_INT_STATUS__TX_BLOCK_DONE_ACK___M                                        0x00000001
#define   SPDIFTX_INT_STATUS__TX_BLOCK_DONE_ACK___S                                        0
#define   SPDIFTX_INT_STATUS__TX_BLOCK_DONE_ACK__NO_EFFECT                                 0x0
#define   SPDIFTX_INT_STATUS__TX_BLOCK_DONE_ACK__CLEAR_STATUS                              0x1
#define   SPDIFTX_INT_STATUS__TX_BLOCK_DONE_STA___M                                        0x00000001
#define   SPDIFTX_INT_STATUS__TX_BLOCK_DONE_STA___S                                        0
#define   SPDIFTX_INT_STATUS__TX_BLOCK_DONE_STA__NO_EVENT                                  0x0
#define   SPDIFTX_INT_STATUS__TX_BLOCK_DONE_STA__AUDIO_BLOCK_IS_TRANSMITTED                0x1
#define   SPDIFTX_INT_STATUS___M                                                           0x0000007F
#define   SPDIFTX_INT_STATUS___S                                                           0

#define LPASS_SPDIFTX_CH_STAT                                                            (0xFE133050)
#define   SPDIFTX_CH_STAT___RWC                                                            QCSR_REG_RW
#define   SPDIFTX_CH_STAT___POR                                                            0x000A0000
#define   SPDIFTX_CH_STAT__CLK_ACC___M                                                     0x003C0000
#define   SPDIFTX_CH_STAT__CLK_ACC___S                                                     18
#define   SPDIFTX_CH_STAT__CLK_ACC__LEVEL_II                                               0x0
#define   SPDIFTX_CH_STAT__CLK_ACC__LEVEL_I                                                0x1
#define   SPDIFTX_CH_STAT__CLK_ACC__LEVEL_III                                              0x2
#define   SPDIFTX_CH_STAT__CLK_ACC__IFR_NOT_MATCHED                                        0x3
#define   SPDIFTX_CH_STAT__SAMPLE_FREQ___M                                                 0x0003C000
#define   SPDIFTX_CH_STAT__SAMPLE_FREQ___S                                                 14
#define   SPDIFTX_CH_STAT__SAMPLE_FREQ__NOT_INDICATED                                      0x0
#define   SPDIFTX_CH_STAT__SAMPLE_FREQ__F_22_05KHZ                                         0x1
#define   SPDIFTX_CH_STAT__SAMPLE_FREQ__F_44_1KHZ                                          0x2
#define   SPDIFTX_CH_STAT__SAMPLE_FREQ__F_88_2KHZ                                          0x3
#define   SPDIFTX_CH_STAT__SAMPLE_FREQ__F_176_4KHZ                                         0x4
#define   SPDIFTX_CH_STAT__SAMPLE_FREQ__F_24KHZ                                            0x5
#define   SPDIFTX_CH_STAT__SAMPLE_FREQ__F_192KHZ                                           0x6
#define   SPDIFTX_CH_STAT__SAMPLE_FREQ__F_32KHZ                                            0x7
#define   SPDIFTX_CH_STAT__CAT_CODE___M                                                    0x00003FC0
#define   SPDIFTX_CH_STAT__CAT_CODE___S                                                    6
#define   SPDIFTX_CH_STAT__CAT_CODE__NO_INDICATION                                         0x00
#define   SPDIFTX_CH_STAT__CAT_CODE__ORIGINAL_COMMERCIAL_PRE_RECORDED_DATA                 0x01
#define   SPDIFTX_CH_STAT__CH_STAT_CNTL___M                                                0x0000003F
#define   SPDIFTX_CH_STAT__CH_STAT_CNTL___S                                                0
#define   SPDIFTX_CH_STAT___M                                                              0x003FFFFF
#define   SPDIFTX_CH_STAT___S                                                              0

#define LPASS_SPDIFTX_CHA_STAT_BUF0                                                      (0xFE133054)
#define   SPDIFTX_CHA_STAT_BUF0___RWC                                                      QCSR_REG_RW
#define   SPDIFTX_CHA_STAT_BUF0___POR                                                      0x00000000
#define   SPDIFTX_CHA_STAT_BUF0__CHASTAT___M                                               0xFFFFFFFF
#define   SPDIFTX_CHA_STAT_BUF0__CHASTAT___S                                               0
#define   SPDIFTX_CHA_STAT_BUF0___M                                                        0xFFFFFFFF
#define   SPDIFTX_CHA_STAT_BUF0___S                                                        0

#define LPASS_SPDIFTX_CHA_STAT_BUF1                                                      (0xFE133058)
#define   SPDIFTX_CHA_STAT_BUF1___RWC                                                      QCSR_REG_RW
#define   SPDIFTX_CHA_STAT_BUF1___POR                                                      0x00000000
#define   SPDIFTX_CHA_STAT_BUF1__CHASTAT___M                                               0xFFFFFFFF
#define   SPDIFTX_CHA_STAT_BUF1__CHASTAT___S                                               0
#define   SPDIFTX_CHA_STAT_BUF1___M                                                        0xFFFFFFFF
#define   SPDIFTX_CHA_STAT_BUF1___S                                                        0

#define LPASS_SPDIFTX_CHA_STAT_BUF2                                                      (0xFE13305C)
#define   SPDIFTX_CHA_STAT_BUF2___RWC                                                      QCSR_REG_RW
#define   SPDIFTX_CHA_STAT_BUF2___POR                                                      0x00000000
#define   SPDIFTX_CHA_STAT_BUF2__CHASTAT___M                                               0xFFFFFFFF
#define   SPDIFTX_CHA_STAT_BUF2__CHASTAT___S                                               0
#define   SPDIFTX_CHA_STAT_BUF2___M                                                        0xFFFFFFFF
#define   SPDIFTX_CHA_STAT_BUF2___S                                                        0

#define LPASS_SPDIFTX_CHA_STAT_BUF3                                                      (0xFE133060)
#define   SPDIFTX_CHA_STAT_BUF3___RWC                                                      QCSR_REG_RW
#define   SPDIFTX_CHA_STAT_BUF3___POR                                                      0x00000000
#define   SPDIFTX_CHA_STAT_BUF3__CHASTAT___M                                               0xFFFFFFFF
#define   SPDIFTX_CHA_STAT_BUF3__CHASTAT___S                                               0
#define   SPDIFTX_CHA_STAT_BUF3___M                                                        0xFFFFFFFF
#define   SPDIFTX_CHA_STAT_BUF3___S                                                        0

#define LPASS_SPDIFTX_CHA_STAT_BUF4                                                      (0xFE133064)
#define   SPDIFTX_CHA_STAT_BUF4___RWC                                                      QCSR_REG_RW
#define   SPDIFTX_CHA_STAT_BUF4___POR                                                      0x00000000
#define   SPDIFTX_CHA_STAT_BUF4__CHASTAT___M                                               0xFFFFFFFF
#define   SPDIFTX_CHA_STAT_BUF4__CHASTAT___S                                               0
#define   SPDIFTX_CHA_STAT_BUF4___M                                                        0xFFFFFFFF
#define   SPDIFTX_CHA_STAT_BUF4___S                                                        0

#define LPASS_SPDIFTX_CHA_STAT_BUF5                                                      (0xFE133068)
#define   SPDIFTX_CHA_STAT_BUF5___RWC                                                      QCSR_REG_RW
#define   SPDIFTX_CHA_STAT_BUF5___POR                                                      0x00000000
#define   SPDIFTX_CHA_STAT_BUF5__CHASTAT___M                                               0xFFFFFFFF
#define   SPDIFTX_CHA_STAT_BUF5__CHASTAT___S                                               0
#define   SPDIFTX_CHA_STAT_BUF5___M                                                        0xFFFFFFFF
#define   SPDIFTX_CHA_STAT_BUF5___S                                                        0

#define LPASS_SPDIFTX_CHB_STAT_BUF0                                                      (0xFE13306C)
#define   SPDIFTX_CHB_STAT_BUF0___RWC                                                      QCSR_REG_RW
#define   SPDIFTX_CHB_STAT_BUF0___POR                                                      0x00000000
#define   SPDIFTX_CHB_STAT_BUF0__CHBSTAT___M                                               0xFFFFFFFF
#define   SPDIFTX_CHB_STAT_BUF0__CHBSTAT___S                                               0
#define   SPDIFTX_CHB_STAT_BUF0___M                                                        0xFFFFFFFF
#define   SPDIFTX_CHB_STAT_BUF0___S                                                        0

#define LPASS_SPDIFTX_CHB_STAT_BUF1                                                      (0xFE133070)
#define   SPDIFTX_CHB_STAT_BUF1___RWC                                                      QCSR_REG_RW
#define   SPDIFTX_CHB_STAT_BUF1___POR                                                      0x00000000
#define   SPDIFTX_CHB_STAT_BUF1__CHBSTAT___M                                               0xFFFFFFFF
#define   SPDIFTX_CHB_STAT_BUF1__CHBSTAT___S                                               0
#define   SPDIFTX_CHB_STAT_BUF1___M                                                        0xFFFFFFFF
#define   SPDIFTX_CHB_STAT_BUF1___S                                                        0

#define LPASS_SPDIFTX_CHB_STAT_BUF2                                                      (0xFE133074)
#define   SPDIFTX_CHB_STAT_BUF2___RWC                                                      QCSR_REG_RW
#define   SPDIFTX_CHB_STAT_BUF2___POR                                                      0x00000000
#define   SPDIFTX_CHB_STAT_BUF2__CHBSTAT___M                                               0xFFFFFFFF
#define   SPDIFTX_CHB_STAT_BUF2__CHBSTAT___S                                               0
#define   SPDIFTX_CHB_STAT_BUF2___M                                                        0xFFFFFFFF
#define   SPDIFTX_CHB_STAT_BUF2___S                                                        0

#define LPASS_SPDIFTX_CHB_STAT_BUF3                                                      (0xFE133078)
#define   SPDIFTX_CHB_STAT_BUF3___RWC                                                      QCSR_REG_RW
#define   SPDIFTX_CHB_STAT_BUF3___POR                                                      0x00000000
#define   SPDIFTX_CHB_STAT_BUF3__CHBSTAT___M                                               0xFFFFFFFF
#define   SPDIFTX_CHB_STAT_BUF3__CHBSTAT___S                                               0
#define   SPDIFTX_CHB_STAT_BUF3___M                                                        0xFFFFFFFF
#define   SPDIFTX_CHB_STAT_BUF3___S                                                        0

#define LPASS_SPDIFTX_CHB_STAT_BUF4                                                      (0xFE13307C)
#define   SPDIFTX_CHB_STAT_BUF4___RWC                                                      QCSR_REG_RW
#define   SPDIFTX_CHB_STAT_BUF4___POR                                                      0x00000000
#define   SPDIFTX_CHB_STAT_BUF4__CHBSTAT___M                                               0xFFFFFFFF
#define   SPDIFTX_CHB_STAT_BUF4__CHBSTAT___S                                               0
#define   SPDIFTX_CHB_STAT_BUF4___M                                                        0xFFFFFFFF
#define   SPDIFTX_CHB_STAT_BUF4___S                                                        0

#define LPASS_SPDIFTX_CHB_STAT_BUF5                                                      (0xFE133080)
#define   SPDIFTX_CHB_STAT_BUF5___RWC                                                      QCSR_REG_RW
#define   SPDIFTX_CHB_STAT_BUF5___POR                                                      0x00000000
#define   SPDIFTX_CHB_STAT_BUF5__CHBSTAT___M                                               0xFFFFFFFF
#define   SPDIFTX_CHB_STAT_BUF5__CHBSTAT___S                                               0
#define   SPDIFTX_CHB_STAT_BUF5___M                                                        0xFFFFFFFF
#define   SPDIFTX_CHB_STAT_BUF5___S                                                        0

#define LPASS_SPDIFTX_USERA_DATA_BUF0                                                    (0xFE133084)
#define   SPDIFTX_USERA_DATA_BUF0___RWC                                                    QCSR_REG_RW
#define   SPDIFTX_USERA_DATA_BUF0___POR                                                    0x00000000
#define   SPDIFTX_USERA_DATA_BUF0__CHAUD___M                                               0xFFFFFFFF
#define   SPDIFTX_USERA_DATA_BUF0__CHAUD___S                                               0
#define   SPDIFTX_USERA_DATA_BUF0___M                                                      0xFFFFFFFF
#define   SPDIFTX_USERA_DATA_BUF0___S                                                      0

#define LPASS_SPDIFTX_USERA_DATA_BUF1                                                    (0xFE133088)
#define   SPDIFTX_USERA_DATA_BUF1___RWC                                                    QCSR_REG_RW
#define   SPDIFTX_USERA_DATA_BUF1___POR                                                    0x00000000
#define   SPDIFTX_USERA_DATA_BUF1__CHAUD___M                                               0xFFFFFFFF
#define   SPDIFTX_USERA_DATA_BUF1__CHAUD___S                                               0
#define   SPDIFTX_USERA_DATA_BUF1___M                                                      0xFFFFFFFF
#define   SPDIFTX_USERA_DATA_BUF1___S                                                      0

#define LPASS_SPDIFTX_USERA_DATA_BUF2                                                    (0xFE13308C)
#define   SPDIFTX_USERA_DATA_BUF2___RWC                                                    QCSR_REG_RW
#define   SPDIFTX_USERA_DATA_BUF2___POR                                                    0x00000000
#define   SPDIFTX_USERA_DATA_BUF2__CHAUD___M                                               0xFFFFFFFF
#define   SPDIFTX_USERA_DATA_BUF2__CHAUD___S                                               0
#define   SPDIFTX_USERA_DATA_BUF2___M                                                      0xFFFFFFFF
#define   SPDIFTX_USERA_DATA_BUF2___S                                                      0

#define LPASS_SPDIFTX_USERA_DATA_BUF3                                                    (0xFE133090)
#define   SPDIFTX_USERA_DATA_BUF3___RWC                                                    QCSR_REG_RW
#define   SPDIFTX_USERA_DATA_BUF3___POR                                                    0x00000000
#define   SPDIFTX_USERA_DATA_BUF3__CHAUD___M                                               0xFFFFFFFF
#define   SPDIFTX_USERA_DATA_BUF3__CHAUD___S                                               0
#define   SPDIFTX_USERA_DATA_BUF3___M                                                      0xFFFFFFFF
#define   SPDIFTX_USERA_DATA_BUF3___S                                                      0

#define LPASS_SPDIFTX_USERA_DATA_BUF4                                                    (0xFE133094)
#define   SPDIFTX_USERA_DATA_BUF4___RWC                                                    QCSR_REG_RW
#define   SPDIFTX_USERA_DATA_BUF4___POR                                                    0x00000000
#define   SPDIFTX_USERA_DATA_BUF4__CHAUD___M                                               0xFFFFFFFF
#define   SPDIFTX_USERA_DATA_BUF4__CHAUD___S                                               0
#define   SPDIFTX_USERA_DATA_BUF4___M                                                      0xFFFFFFFF
#define   SPDIFTX_USERA_DATA_BUF4___S                                                      0

#define LPASS_SPDIFTX_USERA_DATA_BUF5                                                    (0xFE133098)
#define   SPDIFTX_USERA_DATA_BUF5___RWC                                                    QCSR_REG_RW
#define   SPDIFTX_USERA_DATA_BUF5___POR                                                    0x00000000
#define   SPDIFTX_USERA_DATA_BUF5__CHAUD___M                                               0xFFFFFFFF
#define   SPDIFTX_USERA_DATA_BUF5__CHAUD___S                                               0
#define   SPDIFTX_USERA_DATA_BUF5___M                                                      0xFFFFFFFF
#define   SPDIFTX_USERA_DATA_BUF5___S                                                      0

#define LPASS_SPDIFTX_USERB_DATA_BUF0                                                    (0xFE13309C)
#define   SPDIFTX_USERB_DATA_BUF0___RWC                                                    QCSR_REG_RW
#define   SPDIFTX_USERB_DATA_BUF0___POR                                                    0x00000000
#define   SPDIFTX_USERB_DATA_BUF0__CHBUD___M                                               0xFFFFFFFF
#define   SPDIFTX_USERB_DATA_BUF0__CHBUD___S                                               0
#define   SPDIFTX_USERB_DATA_BUF0___M                                                      0xFFFFFFFF
#define   SPDIFTX_USERB_DATA_BUF0___S                                                      0

#define LPASS_SPDIFTX_USERB_DATA_BUF1                                                    (0xFE1330A0)
#define   SPDIFTX_USERB_DATA_BUF1___RWC                                                    QCSR_REG_RW
#define   SPDIFTX_USERB_DATA_BUF1___POR                                                    0x00000000
#define   SPDIFTX_USERB_DATA_BUF1__CHBUD___M                                               0xFFFFFFFF
#define   SPDIFTX_USERB_DATA_BUF1__CHBUD___S                                               0
#define   SPDIFTX_USERB_DATA_BUF1___M                                                      0xFFFFFFFF
#define   SPDIFTX_USERB_DATA_BUF1___S                                                      0

#define LPASS_SPDIFTX_USERB_DATA_BUF2                                                    (0xFE1330A4)
#define   SPDIFTX_USERB_DATA_BUF2___RWC                                                    QCSR_REG_RW
#define   SPDIFTX_USERB_DATA_BUF2___POR                                                    0x00000000
#define   SPDIFTX_USERB_DATA_BUF2__CHBUD___M                                               0xFFFFFFFF
#define   SPDIFTX_USERB_DATA_BUF2__CHBUD___S                                               0
#define   SPDIFTX_USERB_DATA_BUF2___M                                                      0xFFFFFFFF
#define   SPDIFTX_USERB_DATA_BUF2___S                                                      0

#define LPASS_SPDIFTX_USERB_DATA_BUF3                                                    (0xFE1330A8)
#define   SPDIFTX_USERB_DATA_BUF3___RWC                                                    QCSR_REG_RW
#define   SPDIFTX_USERB_DATA_BUF3___POR                                                    0x00000000
#define   SPDIFTX_USERB_DATA_BUF3__CHBUD___M                                               0xFFFFFFFF
#define   SPDIFTX_USERB_DATA_BUF3__CHBUD___S                                               0
#define   SPDIFTX_USERB_DATA_BUF3___M                                                      0xFFFFFFFF
#define   SPDIFTX_USERB_DATA_BUF3___S                                                      0

#define LPASS_SPDIFTX_USERB_DATA_BUF4                                                    (0xFE1330AC)
#define   SPDIFTX_USERB_DATA_BUF4___RWC                                                    QCSR_REG_RW
#define   SPDIFTX_USERB_DATA_BUF4___POR                                                    0x00000000
#define   SPDIFTX_USERB_DATA_BUF4__CHBUD___M                                               0xFFFFFFFF
#define   SPDIFTX_USERB_DATA_BUF4__CHBUD___S                                               0
#define   SPDIFTX_USERB_DATA_BUF4___M                                                      0xFFFFFFFF
#define   SPDIFTX_USERB_DATA_BUF4___S                                                      0

#define LPASS_SPDIFTX_USERB_DATA_BUF5                                                    (0xFE1330B0)
#define   SPDIFTX_USERB_DATA_BUF5___RWC                                                    QCSR_REG_RW
#define   SPDIFTX_USERB_DATA_BUF5___POR                                                    0x00000000
#define   SPDIFTX_USERB_DATA_BUF5__CHBUD___M                                               0xFFFFFFFF
#define   SPDIFTX_USERB_DATA_BUF5__CHBUD___S                                               0
#define   SPDIFTX_USERB_DATA_BUF5___M                                                      0xFFFFFFFF
#define   SPDIFTX_USERB_DATA_BUF5___S                                                      0

#define LPASS_SPDIFTX_BURST_CNTL                                                         (0xFE1330B4)
#define   SPDIFTX_BURST_CNTL___RWC                                                         QCSR_REG_RW
#define   SPDIFTX_BURST_CNTL___POR                                                         0x00000000
#define   SPDIFTX_BURST_CNTL__REP_PERIOD_PAUSE___M                                         0x01C00000
#define   SPDIFTX_BURST_CNTL__REP_PERIOD_PAUSE___S                                         22
#define   SPDIFTX_BURST_CNTL__REP_PERIOD_DATA_BURST___M                                    0x003FFF80
#define   SPDIFTX_BURST_CNTL__REP_PERIOD_DATA_BURST___S                                    7
#define   SPDIFTX_BURST_CNTL__REF_POINT___M                                                0x00000060
#define   SPDIFTX_BURST_CNTL__REF_POINT___S                                                5
#define   SPDIFTX_BURST_CNTL__DATA_TYPE___M                                                0x0000001F
#define   SPDIFTX_BURST_CNTL__DATA_TYPE___S                                                0
#define   SPDIFTX_BURST_CNTL___M                                                           0x01FFFFFF
#define   SPDIFTX_BURST_CNTL___S                                                           0

#define LPASS_SPDIFTX_BURST_MISC                                                         (0xFE1330B8)
#define   SPDIFTX_BURST_MISC___RWC                                                         QCSR_REG_RW
#define   SPDIFTX_BURST_MISC___POR                                                         0x00000000
#define   SPDIFTX_BURST_MISC__AUDIO_GAP___M                                                0xFFFF0000
#define   SPDIFTX_BURST_MISC__AUDIO_GAP___S                                                16
#define   SPDIFTX_BURST_MISC__EXTENDED_DATA_TYPE___M                                       0x0000FFFF
#define   SPDIFTX_BURST_MISC__EXTENDED_DATA_TYPE___S                                       0
#define   SPDIFTX_BURST_MISC___M                                                           0xFFFFFFFF
#define   SPDIFTX_BURST_MISC___S                                                           0

#define LPASS_SPDIFTX_DEBUG_PKT_TRIG                                                     (0xFE1330BC)
#define   SPDIFTX_DEBUG_PKT_TRIG___RWC                                                     QCSR_REG_WO
#define   SPDIFTX_DEBUG_PKT_TRIG___POR                                                     0x00000000
#define   SPDIFTX_DEBUG_PKT_TRIG__PKT_CNT_TRIG_EN___M                                      0x80000000
#define   SPDIFTX_DEBUG_PKT_TRIG__PKT_CNT_TRIG_EN___S                                      31
#define   SPDIFTX_DEBUG_PKT_TRIG__PKT_CNT___M                                              0x000000FF
#define   SPDIFTX_DEBUG_PKT_TRIG__PKT_CNT___S                                              0
#define   SPDIFTX_DEBUG_PKT_TRIG___M                                                       0xFFFFFFFF
#define   SPDIFTX_DEBUG_PKT_TRIG___S                                                       0

#define LPASS_SPDIFTX_DEBUG_DATA_PAT_TRIG                                                (0xFE1330C0)
#define   SPDIFTX_DEBUG_DATA_PAT_TRIG___RWC                                                QCSR_REG_RW
#define   SPDIFTX_DEBUG_DATA_PAT_TRIG___POR                                                0x00000000
#define   SPDIFTX_DEBUG_DATA_PAT_TRIG__DATA_PAT_TRIG_EN___M                                0x80000000
#define   SPDIFTX_DEBUG_DATA_PAT_TRIG__DATA_PAT_TRIG_EN___S                                31
#define   SPDIFTX_DEBUG_DATA_PAT_TRIG__NUM_OF_OCCUR___M                                    0x7F000000
#define   SPDIFTX_DEBUG_DATA_PAT_TRIG__NUM_OF_OCCUR___S                                    24
#define   SPDIFTX_DEBUG_DATA_PAT_TRIG__DATA_PATTERN___M                                    0x00FFFFFF
#define   SPDIFTX_DEBUG_DATA_PAT_TRIG__DATA_PATTERN___S                                    0
#define   SPDIFTX_DEBUG_DATA_PAT_TRIG___M                                                  0xFFFFFFFF
#define   SPDIFTX_DEBUG_DATA_PAT_TRIG___S                                                  0

#define LPASS_SPDIFTX_DEBUG_CRC_CNTL                                                     (0xFE1330C4)
#define   SPDIFTX_DEBUG_CRC_CNTL___RWC                                                     QCSR_REG_RW
#define   SPDIFTX_DEBUG_CRC_CNTL___POR                                                     0x00000000
#define   SPDIFTX_DEBUG_CRC_CNTL__CRC_VAL_READY___M                                        0x00000008
#define   SPDIFTX_DEBUG_CRC_CNTL__CRC_VAL_READY___S                                        3
#define   SPDIFTX_DEBUG_CRC_CNTL__TRIG_READY___M                                           0x00000004
#define   SPDIFTX_DEBUG_CRC_CNTL__TRIG_READY___S                                           2
#define   SPDIFTX_DEBUG_CRC_CNTL__CRC_CLEAR___M                                            0x00000002
#define   SPDIFTX_DEBUG_CRC_CNTL__CRC_CLEAR___S                                            1
#define   SPDIFTX_DEBUG_CRC_CNTL__CRC_ENABLE___M                                           0x00000001
#define   SPDIFTX_DEBUG_CRC_CNTL__CRC_ENABLE___S                                           0
#define   SPDIFTX_DEBUG_CRC_CNTL___M                                                       0x0000000F
#define   SPDIFTX_DEBUG_CRC_CNTL___S                                                       0

#define LPASS_SPDIFTX_DEBUG_CRC_RAW                                                      (0xFE1330C8)
#define   SPDIFTX_DEBUG_CRC_RAW___RWC                                                      QCSR_REG_RO
#define   SPDIFTX_DEBUG_CRC_RAW___POR                                                      0x00000000
#define   SPDIFTX_DEBUG_CRC_RAW__CRC32___M                                                 0xFFFFFFFF
#define   SPDIFTX_DEBUG_CRC_RAW__CRC32___S                                                 0
#define   SPDIFTX_DEBUG_CRC_RAW___M                                                        0xFFFFFFFF
#define   SPDIFTX_DEBUG_CRC_RAW___S                                                        0

#define LPASS_SPDIFTX_DEBUG_CRC_ASM                                                      (0xFE1330CC)
#define   SPDIFTX_DEBUG_CRC_ASM___RWC                                                      QCSR_REG_RO
#define   SPDIFTX_DEBUG_CRC_ASM___POR                                                      0x00000000
#define   SPDIFTX_DEBUG_CRC_ASM__CRC32___M                                                 0xFFFFFFFF
#define   SPDIFTX_DEBUG_CRC_ASM__CRC32___S                                                 0
#define   SPDIFTX_DEBUG_CRC_ASM___M                                                        0xFFFFFFFF
#define   SPDIFTX_DEBUG_CRC_ASM___S                                                        0

#define LPASS_SPDIFTX_DEBUG_CRC_COUNT                                                    (0xFE1330D0)
#define   SPDIFTX_DEBUG_CRC_COUNT___RWC                                                    QCSR_REG_RW
#define   SPDIFTX_DEBUG_CRC_COUNT___POR                                                    0x00000000
#define   SPDIFTX_DEBUG_CRC_COUNT__MC_DWORD_COUNT___M                                      0xFFFFFF00
#define   SPDIFTX_DEBUG_CRC_COUNT__MC_DWORD_COUNT___S                                      8
#define   SPDIFTX_DEBUG_CRC_COUNT__BLOCK_COUNT___M                                         0x000000FF
#define   SPDIFTX_DEBUG_CRC_COUNT__BLOCK_COUNT___S                                         0
#define   SPDIFTX_DEBUG_CRC_COUNT___M                                                      0xFFFFFFFF
#define   SPDIFTX_DEBUG_CRC_COUNT___S                                                      0

#define LPASS_SPDIFTX_DEBUG_CNTL                                                         (0xFE1330D4)
#define   SPDIFTX_DEBUG_CNTL___RWC                                                         QCSR_REG_RW
#define   SPDIFTX_DEBUG_CNTL___POR                                                         0x00000000
#define   SPDIFTX_DEBUG_CNTL__DEBUG_EN___M                                                 0x00000040
#define   SPDIFTX_DEBUG_CNTL__DEBUG_EN___S                                                 6
#define   SPDIFTX_DEBUG_CNTL__DEBUG_SEL___M                                                0x0000003F
#define   SPDIFTX_DEBUG_CNTL__DEBUG_SEL___S                                                0
#define   SPDIFTX_DEBUG_CNTL___M                                                           0x0000007F
#define   SPDIFTX_DEBUG_CNTL___S                                                           0

#define LPASS_SPDIFTX_PWR_MGMT_CNTL                                                      (0xFE1330D8)
#define   SPDIFTX_PWR_MGMT_CNTL___RWC                                                      QCSR_REG_RW
#define   SPDIFTX_PWR_MGMT_CNTL___POR                                                      0x00000003
#define   SPDIFTX_PWR_MGMT_CNTL__HYST_SEL___M                                              0x000000C0
#define   SPDIFTX_PWR_MGMT_CNTL__HYST_SEL___S                                              6
#define   SPDIFTX_PWR_MGMT_CNTL__HYST_SEL__N_4_CLOCKS                                      0x0
#define   SPDIFTX_PWR_MGMT_CNTL__HYST_SEL__N_8_CLOCKS                                      0x1
#define   SPDIFTX_PWR_MGMT_CNTL__HYST_SEL__N_16_CLOCKS                                     0x2
#define   SPDIFTX_PWR_MGMT_CNTL__HYST_SEL__N_32_CLOCKS                                     0x3
#define   SPDIFTX_PWR_MGMT_CNTL__AHBM_SCLK_FORCE_OFF___M                                   0x00000020
#define   SPDIFTX_PWR_MGMT_CNTL__AHBM_SCLK_FORCE_OFF___S                                   5
#define   SPDIFTX_PWR_MGMT_CNTL__AHBM_SCLK_FORCE_ON___M                                    0x00000010
#define   SPDIFTX_PWR_MGMT_CNTL__AHBM_SCLK_FORCE_ON___S                                    4
#define   SPDIFTX_PWR_MGMT_CNTL__AHBS_REGCLK_FORCE_OFF___M                                 0x00000008
#define   SPDIFTX_PWR_MGMT_CNTL__AHBS_REGCLK_FORCE_OFF___S                                 3
#define   SPDIFTX_PWR_MGMT_CNTL__AHBS_REGCLK_FORCE_ON___M                                  0x00000004
#define   SPDIFTX_PWR_MGMT_CNTL__AHBS_REGCLK_FORCE_ON___S                                  2
#define   SPDIFTX_PWR_MGMT_CNTL__TIMER_PWR_MGN_EN___M                                      0x00000002
#define   SPDIFTX_PWR_MGMT_CNTL__TIMER_PWR_MGN_EN___S                                      1
#define   SPDIFTX_PWR_MGMT_CNTL__TX_PWR_MGN_EN___M                                         0x00000001
#define   SPDIFTX_PWR_MGMT_CNTL__TX_PWR_MGN_EN___S                                         0
#define   SPDIFTX_PWR_MGMT_CNTL___M                                                        0x000000FF
#define   SPDIFTX_PWR_MGMT_CNTL___S                                                        0

#define LPASS_SPDIFTX_INT_CNTL_APP                                                       (0xFE1330DC)
#define   SPDIFTX_INT_CNTL_APP___RWC                                                       QCSR_REG_RW
#define   SPDIFTX_INT_CNTL_APP___POR                                                       0x00000000
#define   SPDIFTX_INT_CNTL_APP__APP_TX_MC_ERR___M                                          0x00000040
#define   SPDIFTX_INT_CNTL_APP__APP_TX_MC_ERR___S                                          6
#define   SPDIFTX_INT_CNTL_APP__APP_TX_MC_ERR__DISABLE                                     0x0
#define   SPDIFTX_INT_CNTL_APP__APP_TX_MC_ERR__ENABLE                                      0x1
#define   SPDIFTX_INT_CNTL_APP__APP_TX_TS_DIFF_INT_EN___M                                  0x00000020
#define   SPDIFTX_INT_CNTL_APP__APP_TX_TS_DIFF_INT_EN___S                                  5
#define   SPDIFTX_INT_CNTL_APP__APP_TX_TS_DIFF_INT_EN__DISABLE                             0x0
#define   SPDIFTX_INT_CNTL_APP__APP_TX_TS_DIFF_INT_EN__ENABLE                              0x1
#define   SPDIFTX_INT_CNTL_APP__APP_TX_DROP_LATE_BLOCK_INT_EN___M                          0x00000010
#define   SPDIFTX_INT_CNTL_APP__APP_TX_DROP_LATE_BLOCK_INT_EN___S                          4
#define   SPDIFTX_INT_CNTL_APP__APP_TX_DROP_LATE_BLOCK_INT_EN__DISABLE                     0x0
#define   SPDIFTX_INT_CNTL_APP__APP_TX_DROP_LATE_BLOCK_INT_EN__ENABLE                      0x1
#define   SPDIFTX_INT_CNTL_APP__APP_TX_PAUSE_INT_EN___M                                    0x00000008
#define   SPDIFTX_INT_CNTL_APP__APP_TX_PAUSE_INT_EN___S                                    3
#define   SPDIFTX_INT_CNTL_APP__APP_TX_PAUSE_INT_EN__DISABLE                               0x0
#define   SPDIFTX_INT_CNTL_APP__APP_TX_PAUSE_INT_EN__ENABLE                                0x1
#define   SPDIFTX_INT_CNTL_APP__APP_TX_IDLE_INT_EN___M                                     0x00000004
#define   SPDIFTX_INT_CNTL_APP__APP_TX_IDLE_INT_EN___S                                     2
#define   SPDIFTX_INT_CNTL_APP__APP_TX_IDLE_INT_EN__DISABLE                                0x0
#define   SPDIFTX_INT_CNTL_APP__APP_TX_IDLE_INT_EN__ENABLE                                 0x1
#define   SPDIFTX_INT_CNTL_APP__APP_TX_FIFO_UNDERFLOW_INT_EN___M                           0x00000002
#define   SPDIFTX_INT_CNTL_APP__APP_TX_FIFO_UNDERFLOW_INT_EN___S                           1
#define   SPDIFTX_INT_CNTL_APP__APP_TX_FIFO_UNDERFLOW_INT_EN__DISABLE                      0x0
#define   SPDIFTX_INT_CNTL_APP__APP_TX_FIFO_UNDERFLOW_INT_EN__ENABLE                       0x1
#define   SPDIFTX_INT_CNTL_APP__APP_TX_BLOCK_DONE_INT_EN___M                               0x00000001
#define   SPDIFTX_INT_CNTL_APP__APP_TX_BLOCK_DONE_INT_EN___S                               0
#define   SPDIFTX_INT_CNTL_APP__APP_TX_BLOCK_DONE_INT_EN__DISABLE                          0x0
#define   SPDIFTX_INT_CNTL_APP__APP_TX_BLOCK_DONE_INT_EN__ENABLE                           0x1
#define   SPDIFTX_INT_CNTL_APP___M                                                         0x0000007F
#define   SPDIFTX_INT_CNTL_APP___S                                                         0

#define LPASS_SPDIFTX_INT_STATUS_APP                                                     (0xFE1330E0)
#define   SPDIFTX_INT_STATUS_APP___RWC                                                     QCSR_REG_COMMAND
#define   SPDIFTX_INT_STATUS_APP___POR                                                     0x00000004
#define   SPDIFTX_INT_STATUS_APP__APP_TX_MC_ERR_ACK___M                                    0x00000040
#define   SPDIFTX_INT_STATUS_APP__APP_TX_MC_ERR_ACK___S                                    6
#define   SPDIFTX_INT_STATUS_APP__APP_TX_MC_ERR_ACK__NO_EFFECT                             0x0
#define   SPDIFTX_INT_STATUS_APP__APP_TX_MC_ERR_ACK__CLEAR_STATUS                          0x1
#define   SPDIFTX_INT_STATUS_APP__APP_TX_MC_ERR_STA___M                                    0x00000040
#define   SPDIFTX_INT_STATUS_APP__APP_TX_MC_ERR_STA___S                                    6
#define   SPDIFTX_INT_STATUS_APP__APP_TX_MC_ERR_STA__NO_EVENT                              0x0
#define   SPDIFTX_INT_STATUS_APP__APP_TX_MC_ERR_STA__DIFFERENCE_BETWEEN_TIME_STAMP_AND_ACTUAL_PRESENTATION_TIME_LATCHED 0x1
#define   SPDIFTX_INT_STATUS_APP__APP_TX_TS_DIFF_ACK___M                                   0x00000020
#define   SPDIFTX_INT_STATUS_APP__APP_TX_TS_DIFF_ACK___S                                   5
#define   SPDIFTX_INT_STATUS_APP__APP_TX_TS_DIFF_ACK__NO_EFFECT                            0x0
#define   SPDIFTX_INT_STATUS_APP__APP_TX_TS_DIFF_ACK__CLEAR_STATUS                         0x1
#define   SPDIFTX_INT_STATUS_APP__APP_TX_TS_DIFF_STA___M                                   0x00000020
#define   SPDIFTX_INT_STATUS_APP__APP_TX_TS_DIFF_STA___S                                   5
#define   SPDIFTX_INT_STATUS_APP__APP_TX_TS_DIFF_STA__NO_EVENT                             0x0
#define   SPDIFTX_INT_STATUS_APP__APP_TX_TS_DIFF_STA__DIFFERENCE_BETWEEN_TIME_STAMP_AND_ACTUAL_PRESENTATION_TIME_LATCHED 0x1
#define   SPDIFTX_INT_STATUS_APP__APP_TX_DROP_LATE_BLOCK_ACK___M                           0x00000010
#define   SPDIFTX_INT_STATUS_APP__APP_TX_DROP_LATE_BLOCK_ACK___S                           4
#define   SPDIFTX_INT_STATUS_APP__APP_TX_DROP_LATE_BLOCK_ACK__NO_EFFECT                    0x0
#define   SPDIFTX_INT_STATUS_APP__APP_TX_DROP_LATE_BLOCK_ACK__CLEAR_STATUS                 0x1
#define   SPDIFTX_INT_STATUS_APP__APP_TX_DROP_LATE_BLOCK_STA___M                           0x00000010
#define   SPDIFTX_INT_STATUS_APP__APP_TX_DROP_LATE_BLOCK_STA___S                           4
#define   SPDIFTX_INT_STATUS_APP__APP_TX_DROP_LATE_BLOCK_STA__NO_EVENT                     0x0
#define   SPDIFTX_INT_STATUS_APP__APP_TX_DROP_LATE_BLOCK_STA__FRAME_WITH_PRESENTATION_TIME_PASSED_WAS_DROPPED 0x1
#define   SPDIFTX_INT_STATUS_APP__APP_TX_PAUSE_ACK___M                                     0x00000008
#define   SPDIFTX_INT_STATUS_APP__APP_TX_PAUSE_ACK___S                                     3
#define   SPDIFTX_INT_STATUS_APP__APP_TX_PAUSE_ACK__NO_EFFECT                              0x0
#define   SPDIFTX_INT_STATUS_APP__APP_TX_PAUSE_ACK__CLEAR_STATUS                           0x1
#define   SPDIFTX_INT_STATUS_APP__APP_TX_PAUSE_STA___M                                     0x00000008
#define   SPDIFTX_INT_STATUS_APP__APP_TX_PAUSE_STA___S                                     3
#define   SPDIFTX_INT_STATUS_APP__APP_TX_PAUSE_STA__TRANSMITTER_IS_ACTIVE                  0x0
#define   SPDIFTX_INT_STATUS_APP__APP_TX_PAUSE_STA__TRANSMITTER_IS_IN_THE_PAUSE_STATE      0x1
#define   SPDIFTX_INT_STATUS_APP__APP_TX_IDLE_ACK___M                                      0x00000004
#define   SPDIFTX_INT_STATUS_APP__APP_TX_IDLE_ACK___S                                      2
#define   SPDIFTX_INT_STATUS_APP__APP_TX_IDLE_ACK__NO_EFFECT                               0x0
#define   SPDIFTX_INT_STATUS_APP__APP_TX_IDLE_ACK__CLEAR_STATUS                            0x1
#define   SPDIFTX_INT_STATUS_APP__APP_TX_IDLE_STA___M                                      0x00000004
#define   SPDIFTX_INT_STATUS_APP__APP_TX_IDLE_STA___S                                      2
#define   SPDIFTX_INT_STATUS_APP__APP_TX_IDLE_STA__TRANSMITTER_IS_BUSY                     0x0
#define   SPDIFTX_INT_STATUS_APP__APP_TX_IDLE_STA__TRANSMITTER_IS_IDLE                     0x1
#define   SPDIFTX_INT_STATUS_APP__APP_TX_FIFO_UNDERFLOW_ACK___M                            0x00000002
#define   SPDIFTX_INT_STATUS_APP__APP_TX_FIFO_UNDERFLOW_ACK___S                            1
#define   SPDIFTX_INT_STATUS_APP__APP_TX_FIFO_UNDERFLOW_ACK__NO_EFFECT                     0x0
#define   SPDIFTX_INT_STATUS_APP__APP_TX_FIFO_UNDERFLOW_ACK__CLEAR_STATUS                  0x1
#define   SPDIFTX_INT_STATUS_APP__APP_TX_FIFO_UNDERFLOW_STA___M                            0x00000002
#define   SPDIFTX_INT_STATUS_APP__APP_TX_FIFO_UNDERFLOW_STA___S                            1
#define   SPDIFTX_INT_STATUS_APP__APP_TX_FIFO_UNDERFLOW_STA__NO_EVENT                      0x0
#define   SPDIFTX_INT_STATUS_APP__APP_TX_FIFO_UNDERFLOW_STA__TRANSMIT_FIFO_UNDERFLOW_OCCURRED 0x1
#define   SPDIFTX_INT_STATUS_APP__APP_TX_BLOCK_DONE_ACK___M                                0x00000001
#define   SPDIFTX_INT_STATUS_APP__APP_TX_BLOCK_DONE_ACK___S                                0
#define   SPDIFTX_INT_STATUS_APP__APP_TX_BLOCK_DONE_ACK__NO_EFFECT                         0x0
#define   SPDIFTX_INT_STATUS_APP__APP_TX_BLOCK_DONE_ACK__CLEAR_STATUS                      0x1
#define   SPDIFTX_INT_STATUS_APP__APP_TX_BLOCK_DONE_STA___M                                0x00000001
#define   SPDIFTX_INT_STATUS_APP__APP_TX_BLOCK_DONE_STA___S                                0
#define   SPDIFTX_INT_STATUS_APP__APP_TX_BLOCK_DONE_STA__NO_EVENT                          0x0
#define   SPDIFTX_INT_STATUS_APP__APP_TX_BLOCK_DONE_STA__AUDIO_BLOCK_IS_TRANSMITTED        0x1
#define   SPDIFTX_INT_STATUS_APP___M                                                       0x0000007F
#define   SPDIFTX_INT_STATUS_APP___S                                                       0

////////////////////////////////////////////////////////////////////////// END
#endif

