//////////////////////////////////////////////////////////////////////////////
// LPASS_ADDRESS_FILE.h generated by: GenArmCHeader.pl
//////////////////////////////////////////////////////////////////////////////
// **** W A R N I N G ****  THIS FILE IS AUTO GENERATED!! PLEASE DO NOT EDIT!!
//////////////////////////////////////////////////////////////////////////////
// QUALCOMM Proprietary
// Copyright Qualcomm Technologies Incorporated.  All rights reserved.
//
// All data and information contained in or disclosed by this document are
// confidential and proprietary information of Qualcomm Technologies Incorporated, and
// all rights therein are expressly reserved. By accepting this material,
// the recipient agrees that this material and the information contained
// therein are held in confidence and in trust and will not be used,
// copied, reproduced in whole or in part, nor its contents revealed in
// any manner to others without the express written permission of QUALCOMM
// Incorporated.
//
// This technology was exported from the United States in accordance with
// the Export Administration Regulations. Diversion contrary to U.S. law
// prohibited.
//////////////////////////////////////////////////////////////////////////////
// RCS File        : -USE CVS LOG-
// Revision        : -USE CVS LOG-
// Last Check In   : -USE CVS LOG-
//////////////////////////////////////////////////////////////////////////////
// Description     : Constants related to Hardware Registers
//
// Byte Addresses are used for all BASES and ADDRESSES
//////////////////////////////////////////////////////////////////////////////
#ifndef _LPASS_ADDRESS_FILE_TS_V1_H_
#define _LPASS_ADDRESS_FILE_TS_V1_H_

#define LPASS_VFR_IRQ_MUX_CTL_V1                 (0x0908F000)

#define LPASS_VFR_IRQ_MUX_CTL                     (0x0908F000)
#define   LPASS_VFR_IRQ_MUX_CTL___RWC               QCSR_REG_RW    
#define   LPASS_VFR_IRQ_MUX_CTL___POR            0x00000000
#define   LPASS_VFR_IRQ_MUX_CTL__VFR___POR       0x0
#define   LPASS_VFR_IRQ_MUX_CTL__SEL___POR       0x00
#define   LPASS_VFR_IRQ_MUX_CTL__VFR___M         0x00000100
#define   LPASS_VFR_IRQ_MUX_CTL__VFR___S                       8
#define   LPASS_VFR_IRQ_MUX_CTL__VFR__QTMR                   0x0
#define   LPASS_VFR_IRQ_MUX_CTL__VFR__AVTIMER                0x1
#define   LPASS_VFR_IRQ_MUX_CTL__SEL___M         0x0000001F
#define   LPASS_VFR_IRQ_MUX_CTL__SEL___S                       0
#define   LPASS_VFR_IRQ_MUX_CTL__SEL__INTERNAL_VFR            0x00
#define   LPASS_VFR_IRQ_MUX_CTL__SEL__EXTENAL_VFR            0x01
#define   LPASS_VFR_IRQ_MUX_CTL__SEL__DIR_CONN_0            0x02
#define   LPASS_VFR_IRQ_MUX_CTL__SEL__DIR_CONN_1            0x03
#define   LPASS_VFR_IRQ_MUX_CTL__SEL__DIR_CONN_2            0x04
#define   LPASS_VFR_IRQ_MUX_CTL__SEL__DIR_CONN_3            0x05
#define   LPASS_VFR_IRQ_MUX_CTL__SEL__DIR_CONN_4            0x06
#define   LPASS_VFR_IRQ_MUX_CTL__SEL__INTERNAL_VFR_2            0x07
#define   LPASS_VFR_IRQ_MUX_CTL__SEL__DIR_CONN_5            0x08
#define   LPASS_VFR_IRQ_MUX_CTL__SEL__SENSOR_VFR_0            0x10
#define   LPASS_VFR_IRQ_MUX_CTL__SEL__SENSOR_VFR_1            0x11
#define   LPASS_VFR_IRQ_MUX_CTL__SEL__SENSOR_VFR_2            0x12
#define   LPASS_VFR_IRQ_MUX_CTL__SEL__SENSOR_VFR_3            0x13
#define   LPASS_VFR_IRQ_MUX_CTL__SEL__SENSOR_VFR_4            0x14
#define   LPASS_VFR_IRQ_MUX_CTL__SEL__SENSOR_VFR_5            0x15
#define   LPASS_VFR_IRQ_MUX_CTL__SEL__SENSOR_VFR_6            0x16
#define   LPASS_VFR_IRQ_MUX_CTL__SEL__SENSOR_VFR_7            0x17
#define   LPASS_VFR_IRQ_MUX_CTL__SEL__SENSOR_VFR_8            0x18
#define   LPASS_VFR_IRQ_MUX_CTL__SEL__SENSOR_VFR_9            0x19
#define   LPASS_VFR_IRQ_MUX_CTL__SEL__FM_VFR                0x1A
#define   LPASS_VFR_IRQ_MUX_CTL__SEL__BLUETOOTH_VFR_0            0x1B
#define   LPASS_VFR_IRQ_MUX_CTL__SEL__BLUETOOTH_VFR_1            0x1C
#define   LPASS_VFR_IRQ_MUX_CTL___M              0x0000011F   
#define   LPASS_VFR_IRQ_MUX_CTL___S                            0

#define LPASS_VFR_STC_MSB                         (0x0908F004)
#define   LPASS_VFR_STC_MSB___RWC                   QCSR_REG_RO    
#define   LPASS_VFR_STC_MSB___POR                0x00000000
#define   LPASS_VFR_STC_MSB__MSB___POR           0x000000
#define   LPASS_VFR_STC_MSB__MSB___M             0x00FFFFFF
#define   LPASS_VFR_STC_MSB__MSB___S                           0
#define   LPASS_VFR_STC_MSB___M                  0x00FFFFFF   
#define   LPASS_VFR_STC_MSB___S                                0

#define LPASS_VFR_STC_LSB                         (0x0908F008)
#define   LPASS_VFR_STC_LSB___RWC                   QCSR_REG_RO    
#define   LPASS_VFR_STC_LSB___POR                0x00000000
#define   LPASS_VFR_STC_LSB__LSB___POR           0x00000000
#define   LPASS_VFR_STC_LSB__LSB___M             0xFFFFFFFF
#define   LPASS_VFR_STC_LSB__LSB___S                           0
#define   LPASS_VFR_STC_LSB___M                  0xFFFFFFFF   
#define   LPASS_VFR_STC_LSB___S                                0

#define LPASS_VFR_IRQ_MUX_CTL_1                   (0x09092000)
#define   LPASS_VFR_IRQ_MUX_CTL_1___RWC             QCSR_REG_RW    
#define   LPASS_VFR_IRQ_MUX_CTL_1___POR          0x00000000
#define   LPASS_VFR_IRQ_MUX_CTL_1__VFR___POR     0x0
#define   LPASS_VFR_IRQ_MUX_CTL_1__SEL___POR     0x00
#define   LPASS_VFR_IRQ_MUX_CTL_1__VFR___M       0x00000100
#define   LPASS_VFR_IRQ_MUX_CTL_1__VFR___S                     8
#define   LPASS_VFR_IRQ_MUX_CTL_1__VFR__QTMR                 0x0
#define   LPASS_VFR_IRQ_MUX_CTL_1__VFR__AVTIMER              0x1
#define   LPASS_VFR_IRQ_MUX_CTL_1__SEL___M       0x0000001F
#define   LPASS_VFR_IRQ_MUX_CTL_1__SEL___S                     0
#define   LPASS_VFR_IRQ_MUX_CTL_1__SEL__INTERNAL_VFR            0x00
#define   LPASS_VFR_IRQ_MUX_CTL_1__SEL__EXTENAL_VFR            0x01
#define   LPASS_VFR_IRQ_MUX_CTL_1__SEL__DIR_CONN_0            0x02
#define   LPASS_VFR_IRQ_MUX_CTL_1__SEL__DIR_CONN_1            0x03
#define   LPASS_VFR_IRQ_MUX_CTL_1__SEL__DIR_CONN_2            0x04
#define   LPASS_VFR_IRQ_MUX_CTL_1__SEL__DIR_CONN_3            0x05
#define   LPASS_VFR_IRQ_MUX_CTL_1__SEL__DIR_CONN_4            0x06
#define   LPASS_VFR_IRQ_MUX_CTL_1__SEL__INTERNAL_VFR_2            0x07
#define   LPASS_VFR_IRQ_MUX_CTL_1__SEL__DIR_CONN_5            0x08
#define   LPASS_VFR_IRQ_MUX_CTL_1__SEL__SENSOR_VFR_0            0x10
#define   LPASS_VFR_IRQ_MUX_CTL_1__SEL__SENSOR_VFR_1            0x11
#define   LPASS_VFR_IRQ_MUX_CTL_1__SEL__SENSOR_VFR_2            0x12
#define   LPASS_VFR_IRQ_MUX_CTL_1__SEL__SENSOR_VFR_3            0x13
#define   LPASS_VFR_IRQ_MUX_CTL_1__SEL__SENSOR_VFR_4            0x14
#define   LPASS_VFR_IRQ_MUX_CTL_1__SEL__SENSOR_VFR_5            0x15
#define   LPASS_VFR_IRQ_MUX_CTL_1__SEL__SENSOR_VFR_6            0x16
#define   LPASS_VFR_IRQ_MUX_CTL_1__SEL__SENSOR_VFR_7            0x17
#define   LPASS_VFR_IRQ_MUX_CTL_1__SEL__SENSOR_VFR_8            0x18
#define   LPASS_VFR_IRQ_MUX_CTL_1__SEL__SENSOR_VFR_9            0x19
#define   LPASS_VFR_IRQ_MUX_CTL_1__SEL__FM_VFR              0x1A
#define   LPASS_VFR_IRQ_MUX_CTL_1__SEL__BLUETOOTH_VFR_0            0x1B
#define   LPASS_VFR_IRQ_MUX_CTL_1__SEL__BLUETOOTH_VFR_1            0x1C
#define   LPASS_VFR_IRQ_MUX_CTL_1___M            0x0000011F   
#define   LPASS_VFR_IRQ_MUX_CTL_1___S                          0

#define LPASS_VFR_STC_MSB_1                       (0x09092004)
#define   LPASS_VFR_STC_MSB_1___RWC                 QCSR_REG_RO    
#define   LPASS_VFR_STC_MSB_1___POR              0x00000000
#define   LPASS_VFR_STC_MSB_1__MSB___POR         0x000000
#define   LPASS_VFR_STC_MSB_1__MSB___M           0x00FFFFFF
#define   LPASS_VFR_STC_MSB_1__MSB___S                         0
#define   LPASS_VFR_STC_MSB_1___M                0x00FFFFFF   
#define   LPASS_VFR_STC_MSB_1___S                              0

#define LPASS_VFR_STC_LSB_1                       (0x09092008)
#define   LPASS_VFR_STC_LSB_1___RWC                 QCSR_REG_RO    
#define   LPASS_VFR_STC_LSB_1___POR              0x00000000
#define   LPASS_VFR_STC_LSB_1__LSB___POR         0x00000000
#define   LPASS_VFR_STC_LSB_1__LSB___M           0xFFFFFFFF
#define   LPASS_VFR_STC_LSB_1__LSB___S                         0
#define   LPASS_VFR_STC_LSB_1___M                0xFFFFFFFF   
#define   LPASS_VFR_STC_LSB_1___S                              0

#define LPASS_GP_IRQ_TS_MUX_CTL_0                 (0x09094000)
#define   LPASS_GP_IRQ_TS_MUX_CTL_0___RWC           QCSR_REG_RW    
#define   LPASS_GP_IRQ_TS_MUX_CTL_0___POR        0x00000000
#define   LPASS_GP_IRQ_TS_MUX_CTL_0__VFR___POR   0x0
#define   LPASS_GP_IRQ_TS_MUX_CTL_0__SEL___POR   0x00
#define   LPASS_GP_IRQ_TS_MUX_CTL_0__VFR___M     0x00000100
#define   LPASS_GP_IRQ_TS_MUX_CTL_0__VFR___S                   8
#define   LPASS_GP_IRQ_TS_MUX_CTL_0__VFR__QTMR               0x0
#define   LPASS_GP_IRQ_TS_MUX_CTL_0__VFR__AVTIMER             0x1
#define   LPASS_GP_IRQ_TS_MUX_CTL_0__SEL___M     0x000000FF
#define   LPASS_GP_IRQ_TS_MUX_CTL_0__SEL___S                   0
#define   LPASS_GP_IRQ_TS_MUX_CTL_0__SEL__INTERNAL_VFR            0x00
#define   LPASS_GP_IRQ_TS_MUX_CTL_0__SEL__EXTENAL_VFR            0x01
#define   LPASS_GP_IRQ_TS_MUX_CTL_0__SEL__DIR_CONN_0            0x02
#define   LPASS_GP_IRQ_TS_MUX_CTL_0__SEL__DIR_CONN_1            0x03
#define   LPASS_GP_IRQ_TS_MUX_CTL_0__SEL__DIR_CONN_2            0x04
#define   LPASS_GP_IRQ_TS_MUX_CTL_0__SEL__DIR_CONN_3            0x05
#define   LPASS_GP_IRQ_TS_MUX_CTL_0__SEL__DIR_CONN_4            0x06
#define   LPASS_GP_IRQ_TS_MUX_CTL_0__SEL__INTERNAL_VFR_2            0x07
#define   LPASS_GP_IRQ_TS_MUX_CTL_0__SEL__DIR_CONN_5            0x08
#define   LPASS_GP_IRQ_TS_MUX_CTL_0__SEL__SENSOR_VFR_0            0x10
#define   LPASS_GP_IRQ_TS_MUX_CTL_0__SEL__SENSOR_VFR_1            0x11
#define   LPASS_GP_IRQ_TS_MUX_CTL_0__SEL__SENSOR_VFR_2            0x12
#define   LPASS_GP_IRQ_TS_MUX_CTL_0__SEL__SENSOR_VFR_3            0x13
#define   LPASS_GP_IRQ_TS_MUX_CTL_0__SEL__SENSOR_VFR_4            0x14
#define   LPASS_GP_IRQ_TS_MUX_CTL_0__SEL__SENSOR_VFR_5            0x15
#define   LPASS_GP_IRQ_TS_MUX_CTL_0__SEL__SENSOR_VFR_6            0x16
#define   LPASS_GP_IRQ_TS_MUX_CTL_0__SEL__SENSOR_VFR_7            0x17
#define   LPASS_GP_IRQ_TS_MUX_CTL_0__SEL__SENSOR_VFR_8            0x18
#define   LPASS_GP_IRQ_TS_MUX_CTL_0__SEL__SENSOR_VFR_9            0x19
#define   LPASS_GP_IRQ_TS_MUX_CTL_0__SEL__FM_VFR            0x1A
#define   LPASS_GP_IRQ_TS_MUX_CTL_0__SEL__BLUETOOTH_VFR_0            0x1B
#define   LPASS_GP_IRQ_TS_MUX_CTL_0__SEL__BLUETOOTH_VFR_1            0x1C
#define   LPASS_GP_IRQ_TS_MUX_CTL_0___M          0x000001FF   
#define   LPASS_GP_IRQ_TS_MUX_CTL_0___S                        0

#define LPASS_GP_IRQ_STC_MSB_0                    (0x09094004)
#define   LPASS_GP_IRQ_STC_MSB_0___RWC              QCSR_REG_RO    
#define   LPASS_GP_IRQ_STC_MSB_0___POR           0x00000000
#define   LPASS_GP_IRQ_STC_MSB_0__MSB___POR      0x000000
#define   LPASS_GP_IRQ_STC_MSB_0__MSB___M        0x00FFFFFF
#define   LPASS_GP_IRQ_STC_MSB_0__MSB___S                      0
#define   LPASS_GP_IRQ_STC_MSB_0___M             0x00FFFFFF   
#define   LPASS_GP_IRQ_STC_MSB_0___S                           0

#define LPASS_GP_IRQ_STC_LSB_0                    (0x09094008)
#define   LPASS_GP_IRQ_STC_LSB_0___RWC              QCSR_REG_RO    
#define   LPASS_GP_IRQ_STC_LSB_0___POR           0x00000000
#define   LPASS_GP_IRQ_STC_LSB_0__LSB___POR      0x00000000
#define   LPASS_GP_IRQ_STC_LSB_0__LSB___M        0xFFFFFFFF
#define   LPASS_GP_IRQ_STC_LSB_0__LSB___S                      0
#define   LPASS_GP_IRQ_STC_LSB_0___M             0xFFFFFFFF   
#define   LPASS_GP_IRQ_STC_LSB_0___S                           0

#define LPASS_GP_IRQ_TS_MUX_CTL_1                 (0x09095000)
#define   LPASS_GP_IRQ_TS_MUX_CTL_1___RWC           QCSR_REG_RW    
#define   LPASS_GP_IRQ_TS_MUX_CTL_1___POR        0x00000000
#define   LPASS_GP_IRQ_TS_MUX_CTL_1__VFR___POR   0x0
#define   LPASS_GP_IRQ_TS_MUX_CTL_1__SEL___POR   0x00
#define   LPASS_GP_IRQ_TS_MUX_CTL_1__VFR___M     0x00000100
#define   LPASS_GP_IRQ_TS_MUX_CTL_1__VFR___S                   8
#define   LPASS_GP_IRQ_TS_MUX_CTL_1__VFR__QTMR               0x0
#define   LPASS_GP_IRQ_TS_MUX_CTL_1__VFR__AVTIMER             0x1
#define   LPASS_GP_IRQ_TS_MUX_CTL_1__SEL___M     0x000000FF
#define   LPASS_GP_IRQ_TS_MUX_CTL_1__SEL___S                   0
#define   LPASS_GP_IRQ_TS_MUX_CTL_1__SEL__INTERNAL_VFR            0x00
#define   LPASS_GP_IRQ_TS_MUX_CTL_1__SEL__EXTENAL_VFR            0x01
#define   LPASS_GP_IRQ_TS_MUX_CTL_1__SEL__DIR_CONN_0            0x02
#define   LPASS_GP_IRQ_TS_MUX_CTL_1__SEL__DIR_CONN_1            0x03
#define   LPASS_GP_IRQ_TS_MUX_CTL_1__SEL__DIR_CONN_2            0x04
#define   LPASS_GP_IRQ_TS_MUX_CTL_1__SEL__DIR_CONN_3            0x05
#define   LPASS_GP_IRQ_TS_MUX_CTL_1__SEL__DIR_CONN_4            0x06
#define   LPASS_GP_IRQ_TS_MUX_CTL_1__SEL__INTERNAL_VFR_2            0x07
#define   LPASS_GP_IRQ_TS_MUX_CTL_1__SEL__DIR_CONN_5            0x08
#define   LPASS_GP_IRQ_TS_MUX_CTL_1__SEL__SENSOR_VFR_0            0x10
#define   LPASS_GP_IRQ_TS_MUX_CTL_1__SEL__SENSOR_VFR_1            0x11
#define   LPASS_GP_IRQ_TS_MUX_CTL_1__SEL__SENSOR_VFR_2            0x12
#define   LPASS_GP_IRQ_TS_MUX_CTL_1__SEL__SENSOR_VFR_3            0x13
#define   LPASS_GP_IRQ_TS_MUX_CTL_1__SEL__SENSOR_VFR_4            0x14
#define   LPASS_GP_IRQ_TS_MUX_CTL_1__SEL__SENSOR_VFR_5            0x15
#define   LPASS_GP_IRQ_TS_MUX_CTL_1__SEL__SENSOR_VFR_6            0x16
#define   LPASS_GP_IRQ_TS_MUX_CTL_1__SEL__SENSOR_VFR_7            0x17
#define   LPASS_GP_IRQ_TS_MUX_CTL_1__SEL__SENSOR_VFR_8            0x18
#define   LPASS_GP_IRQ_TS_MUX_CTL_1__SEL__SENSOR_VFR_9            0x19
#define   LPASS_GP_IRQ_TS_MUX_CTL_1__SEL__FM_VFR            0x1A
#define   LPASS_GP_IRQ_TS_MUX_CTL_1__SEL__BLUETOOTH_VFR_0            0x1B
#define   LPASS_GP_IRQ_TS_MUX_CTL_1__SEL__BLUETOOTH_VFR_1            0x1C
#define   LPASS_GP_IRQ_TS_MUX_CTL_1___M          0x000001FF   
#define   LPASS_GP_IRQ_TS_MUX_CTL_1___S                        0

#define LPASS_GP_IRQ_STC_MSB_1                    (0x09095004)
#define   LPASS_GP_IRQ_STC_MSB_1___RWC              QCSR_REG_RO    
#define   LPASS_GP_IRQ_STC_MSB_1___POR           0x00000000
#define   LPASS_GP_IRQ_STC_MSB_1__MSB___POR      0x000000
#define   LPASS_GP_IRQ_STC_MSB_1__MSB___M        0x00FFFFFF
#define   LPASS_GP_IRQ_STC_MSB_1__MSB___S                      0
#define   LPASS_GP_IRQ_STC_MSB_1___M             0x00FFFFFF   
#define   LPASS_GP_IRQ_STC_MSB_1___S                           0

#define LPASS_GP_IRQ_STC_LSB_1                    (0x09095008)
#define   LPASS_GP_IRQ_STC_LSB_1___RWC              QCSR_REG_RO    
#define   LPASS_GP_IRQ_STC_LSB_1___POR           0x00000000
#define   LPASS_GP_IRQ_STC_LSB_1__LSB___POR      0x00000000
#define   LPASS_GP_IRQ_STC_LSB_1__LSB___M        0xFFFFFFFF
#define   LPASS_GP_IRQ_STC_LSB_1__LSB___S                      0
#define   LPASS_GP_IRQ_STC_LSB_1___M             0xFFFFFFFF   
#define   LPASS_GP_IRQ_STC_LSB_1___S                           0


#endif