#pragma once
/*=============================================================================
  @file sns_sensor_event.h

  An output generated by a Sensor.  The Event may contain multiple
  logical sensor samples.  The Framework will ensure samples can be
  fed into the client individually.

  Copyright (c) 2016 Qualcomm Technologies, Inc.
  All Rights Reserved.
  Confidential and Proprietary - Qualcomm Technologies, Inc.

  $Id: //components/rel/ssc.slpi/3.2/inc/sns_sensor_event.h#1 $
  $DateTime: 2018/02/01 03:15:18 $
  $Change: 15367748 $
  ===========================================================================*/


#include <inttypes.h>
#include "sns_time.h"

typedef struct sns_sensor_event {
  sns_time timestamp;
  uint32_t message_id;
  uint32_t event_len;
  uint64_t event[1];
} sns_sensor_event;
