#===============================================================================
#
# HDCP SRM Service
#
# GENERAL DESCRIPTION
#    build script
#
# Copyright (c) 2014,2016-2017 by QUALCOMM Technologies, Incorporated.
# All Rights Reserved.
# Qualcomm Technologies Confidential and Proprietary
#
#-------------------------------------------------------------------------------
#
#  $Header: //components/rel/apps.tz/2.0.2/securemsm/trustzone/qsapps/tzdrm/tzcommon/hdcpsrmlib/shared/src/SConscript#1 $
#  $DateTime: 2018/02/06 03:27:17 $
#  $Author: pwbldsvc $
#  $Change: 15400261 $
#                      EDIT HISTORY FOR FILE
#
#  This section contains comments describing changes made to the module.
#  Notice that changes are listed in reverse chronological order.
# when       who     what, where, why
# --------   ---     ---------------------------------------------------------
#===============================================================================
Import('env')
env = env.Clone()

#-------------------------------------------------------------------------------
# Source PATH
#-------------------------------------------------------------------------------
libname = 'sme_tzcommon_hdcp_srm_shared_lib'

# do not generate thumb code for inline assembler code
env.Append(ARMCC_OPT = ' -marm')
#-------------------------------------------------------------------------------
# Internal depends within TZ Common Libs
#-------------------------------------------------------------------------------
includes = [
  "${BUILD_ROOT}/core/api/services/",
  "${BUILD_ROOT}/ssg/api/securemsm/trustzone/qsee",
  "${BUILD_ROOT}/ssg/securemsm/secrsa/shared/inc",
  "${BUILD_ROOT}/ssg/securemsm/secmath/shared/inc",
  "${BUILD_ROOT}/ssg/api/securemsm/crypto",
  "${BUILD_ROOT}/ssg/securemsm/trustzone/qsapps/libs/applib/qsee/src",
  "${BUILD_ROOT}/apps/securemsm/trustzone/qsapps/tzdrm/hdcpsrm/idl",
  "${BUILD_ROOT}/apps/securemsm/trustzone/qsapps/tzdrm/tzcommon/hdcpsrmlib/shared/src/",
  "${BUILD_ROOT}/apps/securemsm/trustzone/qsapps/tzdrm/tzcommon/common/shared/inc/",
  "${BUILD_ROOT}/apps/securemsm/trustzone/qsapps/tzdrm/tzcommon/scheduler/shared/src/",
  "${BUILD_ROOT}/apps/securemsm/trustzone/qsapps/tzdrm/tzcommon/scheduler/shared/inc/",
  "${BUILD_ROOT}/ssg/securemsm/trustzone/qsee/mink/include"
]

env.Append(CPPPATH = includes)
#----------------------------------------------------------------------------
# TZCOMMON Shared Library
#----------------------------------------------------------------------------   

sources = [
  'hdcp_srm_lib.c',
  'dsa_sig.c'
]

#-------------------------------------------------------------------------------
# Add Libraries to image
#-------------------------------------------------------------------------------
lib = env.SecureAppLibBuilder(includes, sources, libname)
env.Deploy([lib, 'SConscript', 'hdcp_srm_lib.h'])
noship_files = sources
noship_files += ['hdcp_srm_lib.h', 'dsa_sig.h']
env.CleanPack(env['APP_NAME'], noship_files)

Return('lib')
