#===============================================================================
#
# Secure DSP Demo App
#
# GENERAL DESCRIPTION
#    build script
#
# Copyright (c) 2018 by QUALCOMM, Incorporated.
# All Rights Reserved.
# QUALCOMM Proprietary/GTDR
#
#-------------------------------------------------------------------------------
#
#  $Header: //components/rel/apps.tz/2.0.2/securemsm/trustzone/qsapps/secdspdemo/SConscript#3 $
#  $DateTime: 2018/08/30 08:33:33 $
#  $Author: pwbldsvc $
#  $Change: 17004987 $
#                      EDIT HISTORY FOR FILE
#
#  This section contains schedulerents describing changes made to the module.
#  Notice that changes are listed in reverse chronological order.
# when      who      what
#-------------------------------------------------------------------------------
#
##===============================================================================
import os
Import('env')
env = env.Clone()

env.Append(CCFLAGS = ' -Werror')
env.Append(CCFLAGS = ' -fno-vectorize-loops')

includes = [
    '${BUILD_ROOT}/apps/securemsm/trustzone/qsapps/ipprotectorlib',
    '${BUILD_ROOT}/apps/securemsm/trustzone/qsapps/secdsplib',
    '${BUILD_ROOT}/core/kernel/smmu/ACv3.0/common/inc',
    '${BUILD_ROOT}/core/api/kernel/libstd/stringl',
]

#----------------------------------------------------------------------------
# App core Objects
#----------------------------------------------------------------------------
sources = Glob('*.c')
sources_header = Glob('*.h')

#-------------------------------------------------------------------------------
# Add metadata to image
#-------------------------------------------------------------------------------

if env['PROC'] == 'scorpion':
  app_name = 'secdspdemo'
else:
  app_name = 'secdspdemo64'

# TO-DO: These are warnings present in other modules that need to be fixed.
# This is done just so Werror is enabled for this app
env.Append(CCFLAGS = " -O3 -Wall -Werror")
md = {
  'appName': app_name,
  #'privileges': ['default', 'IPProtector', 'DSPSharedChannel', 'ComputeDSPSecureMemAccess'],
  'privileges': ['default', 'DSPSharedChannel', 'ComputeDSPSecureMemAccess'],
  # Using default heap size of 0xE000
  # Using default stack size of 0x8000
}

#-------------------------------------------------------------------------------
# Add Libraries to image
#-------------------------------------------------------------------------------
dsclib = [env.SConscript('${BUILD_ROOT}/apps/securemsm/trustzone/qsapps/secdsplib/SConscript', exports='env')]
#ipplib = [env.SConscript('${BUILD_ROOT}/apps/securemsm/trustzone/qsapps/ipprotectorlib/SConscript', exports='env')]

#libs = [dsclib, ipplib]
libs = [dsclib]

app_units = env.SecureAppBuilder(
  sources = sources,
  includes = includes,
  user_libs = libs,
  metadata = md,
  image = app_name,
  qti_doublesign = True,
  deploy_variants = env.GetDefaultPublicVariants()
)

op = env.Alias(app_name, app_units)

#env.CleanPack(app_name, sources)
env.Deploy([sources, 'SConscript', sources_header])
Return('app_units')
