#ifndef RPC_VERSION_IDL
#define RPC_VERSION_IDL

#include "AEEStdDef.idl"

interface rpcversion{
    uint32 get(rout string version);
    uint32 getSerialNum(rout long snum);
    uint32 getSerialAndOEMId(rout long snum, rout uint16 oemid);
};

#endif
