/*
===========================================================================
*/
/**
  @file msmhwiomap.h 
  @brief Auto-generated HWIO base map include file.
*/
/*
  ===========================================================================

  Copyright (c) 2017 Qualcomm Technologies Incorporated.
  All Rights Reserved.
  Qualcomm Confidential and Proprietary

  Export of this technology or software is regulated by the U.S. Government.
  Diversion contrary to U.S. law prohibited.

  All ideas, data and information contained in or disclosed by
  this document are confidential and proprietary information of
  Qualcomm Technologies Incorporated and all rights therein are expressly reserved.
  By accepting this material the recipient agrees that this material
  and the information contained therein are held in confidence and in
  trust and will not be used, copied, reproduced in whole or in part,
  nor its contents revealed in any manner to others without the express
  written permission of Qualcomm Technologies Incorporated.

  ===========================================================================

  $Header: //components/rel/boot.xf/2.1/QcomPkg/SDM670Pkg/Include/msmhwiomap.h#1 $
  $DateTime: 2017/09/18 09:26:13 $
  $Author: pwbldsvc $

  ===========================================================================
*/

/*----------------------------------------------------------------------------
 * Declare supported bases using user-defined HWIO_MAP_ENTRY macro.
 *--------------------------------------------------------------------------*/

HWIO_MAP_ENTRY(AOP_SS_MSG_RAM_DRV0)
HWIO_MAP_ENTRY(AOP_SS_MSG_RAM_DRV1)
HWIO_MAP_ENTRY(AOP_SS_MSG_RAM_DRV2)
HWIO_MAP_ENTRY(AOP_SS_MSG_RAM_DRV3)
HWIO_MAP_ENTRY(AOP_SS_MSG_RAM_DRV4)
HWIO_MAP_ENTRY(SSC_MPU_CFG_SSC_MPU_WRAPPER)
HWIO_MAP_ENTRY(AOP_SS_MSG_RAM_DRV5)
HWIO_MAP_ENTRY(AOP_SS_MSG_RAM_DRV6)
HWIO_MAP_ENTRY(AOP_SS_MSG_RAM_DRV7)
HWIO_MAP_ENTRY(AOP_SS_MSG_RAM_DRV8)
HWIO_MAP_ENTRY(AOP_SS_MSG_RAM_DRV9)
HWIO_MAP_ENTRY(AOP_SS_MSG_RAM_DRV10)
HWIO_MAP_ENTRY(AOP_SS_MSG_RAM_DRV11)
HWIO_MAP_ENTRY(AOP_SS_MSG_RAM_DRV12)
HWIO_MAP_ENTRY(AOP_SS_MSG_RAM_DRV13)
HWIO_MAP_ENTRY(AOP_SS_MSG_RAM_DRV14)
HWIO_MAP_ENTRY(AOP_SS_MSG_RAM_DRV15)
HWIO_MAP_ENTRY(CLK_CTL)
HWIO_MAP_ENTRY(BOOT_ROM_START_ADDRESS)
HWIO_MAP_ENTRY(BOOT_ROM)
HWIO_MAP_ENTRY(RAMBLUR_PIMEM)
HWIO_MAP_ENTRY(OCIMEM_WRAPPER_CSR)
HWIO_MODULE_MAP_ENTRY(OCIMEM_MPU)
HWIO_MAP_ENTRY(SPDM_WRAPPER_TOP)
HWIO_MAP_ENTRY(CX_CPR3)
HWIO_MAP_ENTRY(MX_CPR3)
HWIO_MAP_ENTRY(SECURITY_CONTROL)
HWIO_MAP_ENTRY(PRNG_CFG_PRNG_TOP)
HWIO_MAP_ENTRY(GLM_WRAPPER)
HWIO_MAP_ENTRY(PERIPH_SS_SDC1_SDCC5_TOP)
HWIO_MAP_ENTRY(QUPV3_0_QUPV3_ID_1)
HWIO_MAP_ENTRY(QUPV3_1_QUPV3_ID_1)
HWIO_MAP_ENTRY(AHB2PHY_SOUTH)
HWIO_MAP_ENTRY(TITAN_THROTTLE_THROTTLE_WRAPPER_3)
HWIO_MAP_ENTRY(MDSS_THROTTLE_THROTTLE_WRAPPER_3)
HWIO_MAP_ENTRY(VIDEO_THROTTLE_THROTTLE_BWMON_WRAPPER_2_VENUS)
HWIO_MAP_ENTRY(DCC_RAM_START_ADDRESS)
HWIO_MAP_ENTRY(QC_DCC_CSAFB9399A)
HWIO_MAP_ENTRY(QM)
HWIO_MAP_ENTRY(QM_MPU_CFG_QM_MPU_WRAPPER)
HWIO_MAP_ENTRY(DDR_SS)
HWIO_MAP_ENTRY(CONFIG_NOC_WRAPPER)
HWIO_MAP_ENTRY(SYSTEM_NOC)
HWIO_MAP_ENTRY(AGGRE_NOC_AGGRE_NOC)
HWIO_MAP_ENTRY(MMSS_NOC)
HWIO_MAP_ENTRY(UFS_MEM_UFS_1LANE_REGS)
HWIO_MAP_ENTRY(CRYPTO0_CRYPTO_TOP)
HWIO_MAP_ENTRY(IPA_0_IPA_WRAPPER)
HWIO_MAP_ENTRY(CORE_TOP_CSR)
HWIO_MAP_ENTRY(TLMM)
HWIO_MAP_ENTRY(MODEM_TOP)
HWIO_MAP_ENTRY(MSS_QDSP6_TCM)
HWIO_MAP_ENTRY(GFX)
HWIO_MAP_ENTRY(GDPM_RAM_START_ADDRESS)
HWIO_MAP_ENTRY(GPUCX_ITCM)
HWIO_MAP_ENTRY(GPUCX_DTCM)
HWIO_MAP_ENTRY(QDSS_SOC_DBG)
HWIO_MAP_ENTRY(TURING)
HWIO_MAP_ENTRY(PERIPH_SS_SDC2_SDCC5_TOP)
HWIO_MAP_ENTRY(PERIPH_SS_SDC4_SDCC5_TOP)
HWIO_MAP_ENTRY(PERIPH_SS_TSIF_TSIF_12SEG_WRAPPER)
HWIO_MAP_ENTRY(VSENSE_CONTROLLER)
HWIO_MAP_ENTRY(PERIPH_SS_PDM_PERPH_WEB)
HWIO_MAP_ENTRY(PERIPH_SS_AHB2PHY_NORTH)
HWIO_MAP_ENTRY(USB3_PRI_USB30_PRIM)
HWIO_MAP_ENTRY(VIDEO_SS_WRAPPER)
HWIO_MAP_ENTRY(TITAN_SS)
HWIO_MAP_ENTRY(MDSS)
HWIO_MAP_ENTRY(AOP_CODE_RAM_START_ADDRESS)
HWIO_MAP_ENTRY(AOSS)
HWIO_MODULE_MAP_ENTRY(TSENS0)
HWIO_MODULE_MAP_ENTRY(TSENS1)
HWIO_MODULE_MAP_ENTRY(TSENS0_TM)
HWIO_MODULE_MAP_ENTRY(TSENS1_TM)
HWIO_MAP_ENTRY(AOP_DATA_RAM_START_ADDRESS)
HWIO_MAP_ENTRY(AOP_SS_MSG_RAM_START_ADDRESS)
HWIO_MAP_ENTRY(MODEM)
HWIO_MAP_ENTRY(MSS_NAV_MS_MPU_CFG_MPU32Q2N7S1V0_8_CL36M35L12_AHB)
HWIO_MAP_ENTRY(A1_NOC_MS_MPU_CFG_MPU32Q2N7S1V0_8_CL36M35L12_AHB)
HWIO_MAP_ENTRY(A2_NOC_MS_MPU_CFG_MPU32Q2N7S1V0_16_CL36M35L12_AHB)
HWIO_MAP_ENTRY(SYSTEM_IMEM)
HWIO_MAP_ENTRY(BOOT_IMEM)
HWIO_MAP_ENTRY(SMMU_500_APPS_REG_WRAPPER)
HWIO_MAP_ENTRY(SC_TCM)
HWIO_MAP_ENTRY(QDSS_STM)
HWIO_MAP_ENTRY(APSS_HM)
HWIO_MAP_ENTRY(WCSS_WRAPPER)
HWIO_MAP_ENTRY(PIMEM)
HWIO_MAP_ENTRY(SSC_QDSP6_TCM)
HWIO_MAP_ENTRY(LPASS)
HWIO_MAP_ENTRY(SDC_CODE_RAM_START_ADDRESS)
HWIO_MAP_ENTRY(SDC_DATA_RAM_START_ADDRESS)
HWIO_MAP_ENTRY(SSC_RAM_START_ADDRESS)
HWIO_MAP_ENTRY(LPASS_LPM)
HWIO_MAP_ENTRY(DDR_SPACE)

