/*===========================================================================

   Contains implementation for some of the APIs exposed by shared_lib_api.h

------------------------------------------------------------------------
   Copyright (c) 2014, 2017 QUALCOMM Technologies, Incorporated.
   All Rights Reserved.
   QUALCOMM Technologies Proprietary.
--------------------------------------------------------------------------

                      EDIT HISTORY FOR FILE

This section contains comments describing changes made to this file.
Notice that changes are listed in reverse chronological order.

$Header: //components/rel/avs.adsp/2.8.5/elite/module_interfaces/shared_lib_api/src/shared_lib_api.cpp#1 $

when       who          what, where, why
--------   ---          ----------------------------------------------------------
08-29-2014 rbhatnk      Created file
===========================================================================*/

#include "shared_lib_api.h"

#ifdef AVS_BUILD_SOS

/** Including Autogenerated version file containing :
 *
 *    SHARED_LIB_API__HEXAGON_TOOLS_VERSION, SHARED_LIB_API__LIB_MAJOR_VERSION,
 *    SHARED_LIB_API__LIB_MINOR_VERSION,
 *    SHARED_LIB_API__IS_QURT_USED_IN_LIB
 *    */
#include "so_version.h"

const shared_lib_build_property_v2_t shared_lib_build_property = {
      SHARED_LIB_API__SHARED_LIB_BUILD_PROPERTY_VERSION_V2, //uint16_t build_property_version;
      SHARED_LIB_API__API_MAJOR_VERSION,                 //uint16_t api_major_version;
      SHARED_LIB_API__API_MINOR_VERSION,                 //uint16_t api_minor_version;
      SHARED_LIB_API__LIB_MAJOR_VERSION,                 //uint16_t lib_major_version;
      SHARED_LIB_API__LIB_MINOR_VERSION,                 //uint16_t lib_minor_version;
      SHARED_LIB_API__IS_QURT_USED_IN_LIB,               //uint16_t is_qurt_used;
      QURT_API_VERSION,                                  //uint16_t qurt_api_version;
      0,                                                 //uint16_t reserved;
      SHARED_LIB_API__HEXAGON_TOOLS_VERSION,             //uint32_t hexagon_tools_version;
};

const char shared_lib_engineering_build_id[] = ENGG_TIMESTAMP;
const char shared_lib_qualcomm_build_id[] = QCOM_TIMESTAMP;

#else //AVS_BUILD_SOS

/** Including Autogenerated version file containing :
 *
 *  contains SHARED_LIB_API__HEXAGON_TOOLS_VERSION (32 bit num: xx.yy.zz=00xxyyzz)
 *  */
#include "dsp_version.h"

const adsp_avs_build_property_t adsp_avs_build_property = {
      SHARED_LIB_API__ADSP_BUILD_PROPERTY_VERSION,       //uint16_t build_property_version;
      SHARED_LIB_API__API_MAJOR_VERSION,                 //uint16_t api_major_version;
      SHARED_LIB_API__API_MINOR_VERSION,                 //uint16_t api_minor_version;
      QURT_API_VERSION,                                  //uint16_t qurt_api_version;
      (uint32_t)SHARED_LIB_API__HEXAGON_TOOLS_VERSION,             //uint32_t hexagon_tools_version;
};

#endif //AVS_BUILD_SOS
