// Copyright (c) 2015 Qualcomm Technologies, Inc.  All Rights Reserved.
// Qualcomm Technologies Proprietary and Confidential.

interface ITestSandbox {
  /**< Test sandbox violations. */
  const uint32 TEST_VIOLATIONS = 1;

  /**< Test sandbox access. */
  const uint32 TEST_ACCESS = 2;

  /**
   * Sandbox Test control channel
   *
   * @param [in] Test case id
   *
   * @return Object_OK on success; Object_ERROR on test case failure
   */
  method test(in uint32 id);
};
