#pragma once
// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

// Copyright (c) 2015 Qualcomm Technologies, Inc.  All Rights Reserved.

// Qualcomm Technologies Proprietary and Confidential.

#define ITestSandbox_TEST_VIOLATIONS UINT32_C(1)
#define ITestSandbox_TEST_ACCESS UINT32_C(2)

#define ITestSandbox_OP_test 0

static inline int32_t
ITestSandbox_release(Object self)
{
  return Object_invoke(self, Object_OP_release, 0, 0);
}

static inline int32_t
ITestSandbox_retain(Object self)
{
  return Object_invoke(self, Object_OP_retain, 0, 0);
}

static inline int32_t
ITestSandbox_test(Object self, uint32_t id_val)
{
  ObjectArg a[1];
  a[0].b = (ObjectBuf) { &id_val, sizeof(uint32_t) };

  return Object_invoke(self, ITestSandbox_OP_test, a, ObjectCounts_pack(1, 0, 0, 0));
}



