'''
   CoreBSP Preprocessor cleaner
'''
#===============================================================================
#
# CoreBSP Preprocessor cleaner
#
# GENERAL DESCRIPTION
#    celans junk generated by preprocessor
#
# Copyright (c) 2011,2014-16 by Qualcomm Technologies Inc.
# All Rights Reserved.
# QUALCOMM Proprietary/GTDR#
#
#===============================================================================
#import os
import re
import sys
from optparse import OptionParser

#------------------------------------------------------------------------------
# Parse command line arguments
#------------------------------------------------------------------------------
def parse_args():
    '''
       parse_args

       Parse command line arguments
    '''
    usage = "usage: %prog [options]"
    version = "%prog 1.0"
   
    parser = OptionParser(usage=usage, version=version)
    parser.add_option("-f", "--ppfile", dest="pp_filename",
                      help="Read preprocess data from FILE", metavar="FILE")
    parser.add_option("-o", "--outfile", dest="output_filename",
                      help="Write output to FILE", metavar="FILE")
          
    (options, args) = parser.parse_args()
   
    if options.pp_filename is None:
        parser.error("-f option must be defined")
        sys.exit(2)
                  
                  
    return (options, args)
   
#------------------------------------------------------------------------------
# main
#------------------------------------------------------------------------------
def main():
    '''
       main
    '''
    # get args from cmd line
    (options, args) = parse_args()
   
    file_item = open(options.pp_filename, 'r')
    data = file_item.readlines()
    file_item.close()
   
    if options.output_filename is None:
        file_item = sys.stdout
    else:
        file_item = open(options.output_filename, 'w')
   
    re_bad_line = re.compile('(^\s*#line.*$)|(^\s*#\s\d.*$)|(^\s*$)')
   
    for line in data:
        if re_bad_line.match(line) is None:
            file_item.write(line)

    file_item.close()
   
main()