#include "AEEStdDef.idl"
interface apps_remotectl {
	 long open(in string name, rout long handle, rout sequence<char> dlerror, rout long nErr);
	 long close(in long handle, rout sequence<char> dlerror, rout long nErr);
};
