/* Autogenerated file, do not edit */

#ifndef __RELEASE_INFO__
#define __RELEASE_INFO__

#include "../../Include/BuildVersion.h"

#define REL_LABEL_FIELD "UEFI LABEL: "
#define REL_LABEL "UEFI.4.1.$Change: 14402555 $"

#define REL_DATE_FIELD "LABEL DATE: "
#define REL_DATE "$Date: 2017/09/18 $"

#define REL_INFO_STR REL_LABEL_FIELD REL_LABEL "\n"

#define BUILD_VER_FIELD "FW_VER: "
#define BUILD_VER1 "4.1."
#define BUILD_VER2 __DATE__
#define BUILD_VER3 "."
#define BUILD_VER4 UEFI_BUILD_VERSION

#define BUILD_DATE_FIELD "BUILD_DATE: "
#define BUILD_DATE __DATE__

#define BUILD_TIME_FIELD "BUILD_TIME: "
#define BUILD_TIME __TIME__

#endif /* __RELEASE_INFO_H__ */
