
/*=============================================================================
            Copyright (c) 2015-2017 Qualcomm Technologies, Inc.
                         All Rights Reserved.
          Qualcomm Technologies Proprietary and Confidential
==============================================================================*/

#ifndef _TRACER_EVENT_TBL_H
#define _TRACER_EVENT_TBL_H

// File autogenerated by swe_builder.

#include "tracer_event_ids.h"

#ifndef EVENT_TABLE_TAG
#define EVENT_TABLE_TAG "0000A7E7428B"
#define EVENT_PROCESSOR "BOOT"
#define EVENT_SUBSYSTEM BOOT
#endif

typedef struct _tracer_event_item {
  enum tracer_event_id_enum evt_id;
  char *evt_str;
  char pre_enable;
} tracer_event_item;

tracer_event_item tracer_event_tbl[] = {
  {TRACER_EVENT_RESERVE_0,"Tracer reserve0",'0'},
  {QDSS_INITIALIZED,"QDSS Initialized",'1'},
  {TRACER_EVENT_TEST,"Tracer test event one",'0'},
  {TRACER_EVENT_TEST2,"Tracer test event 2 %d %d",'0'},
  {CLOCK_EVENT_INIT,"Clock Initialize",'1'},
  {CLOCK_EVENT_CLOCK_STATUS,"Clock handle %d  reference count %d",'1'},
  {CLOCK_EVENT_CLOCK_FREQ,"Clock %d Frequency %d",'1'},
  {CLOCK_EVENT_SOURCE_STATUS,"Clock Source %d %d",'1'},
  {CLOCK_EVENT_SOURCE_FREQ,"Source ID %d Frequency %d",'1'},
  {CLOCK_EVENT_SOURCE_CONFIG,"Could not find matching freq config for source %d",'1'},
  {CLOCK_EVENT_CLOCK_VOLTAGE,"Clock %s Voltage %d",'1'},
  {CLOCK_EVENT_CPU_FREQ,"CPU ID %d Frequency %d",'1'},
  {TRACER_EVENT_ID_MAX,"Tracer event MAX",'0'}
};

#endif // _TRACER_EVENT_TBL_H

