#===============================================================================
# GENERAL DESCRIPTION
#     DevCfg Artifacts build script
##
# Copyright (c) 2011,2014-16 by Qualcomm Technologies Inc.
# All Rights Reserved.
# QUALCOMM Proprietary/GTDR
#===================================================================================
Import('env')
import os, glob
env = env.Clone()

env.Replace(BUILDPATH = '${{DEVCFG_ROOT}}/build/{}'.format(env.subst('$BUILDPATH')))
#env.VariantDir('${BUILDPATH}', SRCPATH, duplicate=0) 
config = env.get('DEVCFG')

#Set CPPDEFINES for sources
if config.propsMemoryOptimise == 'true':  
   env.Append(CPPDEFINES = ['DEVCFG__PROPS_MEMORY_OPTIMISE'])
if config.structSize == 'true':  
   env.Append(CPPDEFINES = ['DEVCFG__STRUCT_SIZE'])
env.Append(CPPDEFINES = ['DEVCFG_TCSR_SOC_HW_ADDR='+config.tcsrSsocHwVersionAddr])

#load data scons
if os.path.isfile("data/SConscript"):
    env.SConscript("data/SConscript", exports='env')

#load manager scons
if os.path.isfile("manager/SConscript"):
    env.SConscript("manager/SConscript", exports='env')

#load service scons
if os.path.isfile("service/SConscript"):
    env.SConscript("service/SConscript", exports='env')

#Return('return_list')
